// Class 11 Physics questions imported from PDF via OCR.
// Source: phy pt1 (pt1)_merged (1)_compressed.pdf (96 pages)
// These questions were extracted using Tesseract OCR and may contain OCR artifacts.
// Users can review/edit them in the PDF Import Review mode.

import type { PracticeQuestion } from "./question-bank";

export const PHYSICS_PDF_QUESTIONS: PracticeQuestion[] = [
  {
    id: "pdf_p4_q2_1",
    number: 1,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Fillin the blanks > weksehavbionne knvV/hr? b) 6.67x19-1 Nm/kg?= oes g'cm? s? Ans: a) 3.0 m/st= knv/he We have, 1 m= 103 km =3600s 5 1",
    answer: "Review needed",
    explanation: "Imported from PDF page 4. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p4_q3_2",
    number: 2,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Calculate the length of the arc of a circle of radius 31.0 cm which subtends an an- gle of 7/6 at the centre. - ag l BOARD QUESTION",
    answer: "Review needed",
    explanation: "Imported from PDF page 4. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p4_q4_3",
    number: 3,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Define S. I. unit of solid angle. Ams: The SI unit of solid angle is steradian. One stera dian is defined as the angle made by a sphericg plan e of unit square meter area at the centre of, sphere with radius of unit length. ag ' BOARD QUESTION",
    answer: "Review needed",
    explanation: "Imported from PDF page 4. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p4_q5_4",
    number: 4,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Calculate the solid angle subtended by the; periphery of an area of 1 cm* at a poing situated ‘symmetrically at a distance of 5 cm from the area A. ABS ‘ __Area__ As solid angle Q = aistance? [Area = 1 cm’, distance = 5 cm] __ lem ~ (Sem) i",
    answer: "Review needed",
    explanation: "Imported from PDF page 4. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p5_q3_5",
    number: 5,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Fillin the blanks: a) The volume of a cube of side 1 cm is equal tO.......000 m’, b) The surface area of a solid cylinder of radius 2.0 cm and height 10.0 em is equal to........... mm’, c) A vehicle moving with a speed of 18 kmh\" covers......000 minis. d) The relative density of lead is 11.3.",
    answer: "Review needed",
    explanation: "Imported from PDF page 5. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p5_q4_6",
    number: 6,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Define radian. Space for keynote:",
    answer: "Review needed",
    explanation: "Imported from PDF page 5. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p6_q1_7",
    number: 7,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "mcq",
    question: "Area = Length x breadth = m?",
    options: ["Volume = Length x breadth x height = m? ity = Mass _ 4", "Density = Volume = kgm", "Speed or velocity = Distance =ms!. Change in velocity"],
    answer: "Review needed",
    answerIndex: 0,
    explanation: "Imported from PDF page 6. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p8_q1_8",
    number: 8,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Derive S. I. unit of Joule (a) in. fundamental units, sy Ans: Joule is a unit of work. Using the relation, Work = force = displacement",
    answer: "Review needed",
    explanation: "Imported from PDF page 8. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p8_q2_9",
    number: 9,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "What is a prefix? Give some commy prefixes for multiples and submultiples Ans: Prefix is used to increase or decrease the valu of a fundamental or derived unit as per practica requirements Multiples Submultiples Exa(E) = 18 atto(a) = 10°",
    answer: "Review needed",
    explanation: "Imported from PDF page 8. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p9_q5_10",
    number: 10,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Express unified atomic mass unit in kg Ans: 1;. atomic Mass unit = 7 of mass of, C atom Mass of 1 mole of, C'? atom = 12 g No. of atom in 1 mole = Avogadro number 12 g 6.023 x 10”",
    answer: "Review needed",
    explanation: "Imported from PDF page 9. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p9_q5_11",
    number: 11,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Derive S. I unit of newton (N) in terms of fundamental units. a e or ele",
    answer: "Review needed",
    explanation: "Imported from PDF page 9. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p9_q6_12",
    number: 12,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "What is the difference between and nm? mN, Nm",
    answer: "Review needed",
    explanation: "Imported from PDF page 9. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p10_q97_13",
    number: 13,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "mcq",
    question: "Which of the following are not a unit ue time?",
    options: ["second 2) parsec", "year 4) light year S J ME] TRY Your seLr"],
    answer: "Review needed",
    answerIndex: 0,
    explanation: "Imported from PDF page 10. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p10_q8_14",
    number: 14,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "mcq",
    question: "Which of the following ratios express eireenies?",
    options: ["Force/Area 2) Energy/Volume", "Energy/Area 4) Force / Volume = ) ae, TRY Your SELF ~"],
    answer: "Review needed",
    answerIndex: 0,
    explanation: "Imported from PDF page 10. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p10_q9_15",
    number: 15,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "What do you understand by the following: a) Century b) Shake ¢). Lunar month d) Leap year €) Tropical year. ( space for keynote: aN",
    answer: "Review needed",
    explanation: "Imported from PDF page 10. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p14_q4_16",
    number: 16,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "The length and breadth of a rectangult sheet are 16.2 cm and 10.1 cm, resptt tively. The area of the sheet in appropti ate significant figures is a) 164 cm? b) 163.62 cm’ c) 163.6 cm? d) 163.62 em? =a Ans: Option (a) is correct,",
    answer: "Review needed",
    explanation: "Imported from PDF page 14. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p15_q5_17",
    number: 17,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Mass of an object is 11.25 g and its vol- 06. Give the order of the following ume is 2cm*. What should be the most a) 1 significant representation of its density? b) 499 a) 5.625 g/cm’ b) 5.63 g/cm? c) 501 c) 6 g/em! d) 5.62 g/cm’ d) 1 A(10-°m) e) Gravitational constant (6.67*10\" N-m?/kg’) Ans: ¢ ' Mod During multiplication and division the signif- 5 pane ri eta iat ) /s)",
    answer: "Review needed",
    explanation: "Imported from PDF page 15. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p15_q10_18",
    number: 18,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "State the number of significant figures in on } This gives an approximate value like 10°, where nis called the order of magnitude of the quantity. the following: a) 0.007 m’ b) 2.64 x 10* kg Order of magnitude of some values can be deter- c) 0.2370 gem d) 6.320 J mined as follows: e) 6.032Nm- f) 0.0006032 m’",
    answer: "Review needed",
    explanation: "Imported from PDF page 15. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p15_q2_19",
    number: 19,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "mcq",
    question: "51=5.1x 10! Order of magnitude = 2",
    options: ["0.0049 = 4.9 x 103 Order of magnitude = -3", "0.0050 = 5.0 x 10° Order of magnitude = -3"],
    answer: "Review needed",
    answerIndex: 0,
    explanation: "Imported from PDF page 15. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p16_q12_20",
    number: 20,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "The sum of the numbers 436,32, 227.2 i) yo. and 0.301 in appropriate significant fig- ures is Nz f % ~ Sw A) 663.821 B) 664 mar 4 C) 663.8 D) 663.82 a BD tte ey ty l ae l TRY YOUR SELF x d my",
    answer: "Review needed",
    explanation: "Imported from PDF page 16. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p16_q13_21",
    number: 21,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "The radius of atom is of the order of 1 G A and radius of nucleus is of the order € & 5S -_- of fermi. How many magnitudes higher l - x ~ is the volume of atom as compared to the Ny volume of nucleus? A) 10! B) 10\" “2 Xs C) 107 D) 10\" 16",
    answer: "Review needed",
    explanation: "Imported from PDF page 16. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p18_q5_22",
    number: 22,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "mcq",
    question: "Acceleration = some derived quan- tities",
    options: ["Area = Length x Breadth [A] = [L] x [L] [A] = [L?] or [A]=[M° L? T']", "Volume = Length = Breadth = Height [V] = [LE] (L}*(L]"],
    answer: "Review needed",
    answerIndex: 0,
    explanation: "Imported from PDF page 18. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p20_q41_23",
    number: 23,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Stefan's constant = req x time * (temp tional constant 2p? 1K] a) _Gravita dutus Seta Stefan's constant = Mt i T) [Mr K pb) Young's mo aby oy 4 f je? (KR }*(T) ¢) Coefficient of viscosity. Energy. l",
    answer: "Review needed",
    explanation: "Imported from PDF page 20. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p20_q42_24",
    number: 24,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Solar constant = Ayeq x time Ans: re [ML? T?] T?] a) rede constan l Solar constant = (L? tT =[M. Force x distance! l =7 = “mass",
    answer: "Review needed",
    explanation: "Imported from PDF page 20. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p20_q43_25",
    number: 25,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Mechanical equivalent of heat = J =H _ l L* \\.. [ML? T?] _ yo Lo T°] [G]= ([MLT?)[L\"] = [MLT?]*[L?] x [Ma l Mechanical equivalent = Mr Ty = [M’ [M]x[M] l =. = [M'L? T7] l ), _ Stress f PHYSICAL QUANTITIES HAVING NO ~i) b) Young's Modulus = Strain DIMENSION AND NO UNIT (ML! T?] _ [ML T3] [Y]= o Change in Dimension (Length) [L] = [M°L° T°]",
    answer: "Review needed",
    explanation: "Imported from PDF page 20. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p20_q3_26",
    number: 26,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Which of the following pairs of physi BUT NO DIMENSION oe ana quantities does not have same dime v Plane angle al formula? Y Solid Angle a) Work and torque. v Angular Displacement ] b) Angular momentum and Planck's q stant. c) Tension and surface tension. ~ d) Impulse and linear momentum.",
    answer: "Review needed",
    explanation: "Imported from PDF page 20. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p20_q1_27",
    number: 27,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Will the dimensions of a physical quan- Ans. q tity be same, whatever be the units in which it is measured? Why? Option (c) is correct. Explanation: Ans::; Tension = Force = [MLT?] Yes, the dimensions don't depend on the system Ss ion = a!",
    answer: "Review needed",
    explanation: "Imported from PDF page 20. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p21_q4_28",
    number: 28,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "In the expression P = EL’ m* G*, Here,. Em, L and G denote energy, mass, an- tum and gravitational con- s gular moment on We, TRYY ) stant, respectively. Show that P is a di- oun mensionless quantity. 14. Give an example of a) a physical quantity which has a unit Ans:.. but no dimensions. since, E, L and G have dimensional formulas: b) aphysical quantity which has neither",
    answer: "Review needed",
    explanation: "Imported from PDF page 21. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p21_q3_29",
    number: 29,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "=[ML? T? unit nor dimensions. (E}=t c) aconstant which has a unit. [L] = (ML? T\"] [G] = [L? M'T\"] Hence, P = EL? m* G? will have dimensions: [P] = [ML? T2][M2 L* T?)/[M°][L$ M2 T+] =(M°L°T] Thus, P is dimensionless quantity.",
    answer: "Review needed",
    explanation: "Imported from PDF page 21. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p22_q17_30",
    number: 30,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Mention some physical quantities having same dimensional formulae but different units. te",
    answer: "Review needed",
    explanation: "Imported from PDF page 22. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p23_q1_31",
    number: 31,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Let us consider an equation - mv’ = mgh where m is the mass of the body, v its ve- locity, g is the acceleration due to gravity and h is the height. Check whether this equation is dimensionally correct AT! [mv?]=[M]lL’T?] =(ML? T? ] [mgh]=[MLT?]x[L] = [ML? T? ] Since L. H. S = R. H. S",
    answer: "Review needed",
    explanation: "Imported from PDF page 23. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p24_q3_32",
    number: 32,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "The displacement of a progressive wave is\\ represented by y =A sin(wt -k x), where x is distance and t is time. Write the dimen- sional formula of (i) and (ii) k. Ans: -lL_pp K=p j=) \\. fo. DEDUCING RELATION AMONG THE",
    answer: "Review needed",
    explanation: "Imported from PDF page 24. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p25_q4_33",
    number: 33,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "Derive the equation for kinetic energy (E) of a body of mass m moving with velocity v Ni 05. [M'",
    answer: "Review needed",
    explanation: "Imported from PDF page 25. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p26_q18_34",
    number: 34,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "The escape velocity v of a body depends on: the acceleration due to ory & ei the planet and the radius R of the P -: ( Establish dimensionally the relation fo sy the escape velocity. & TRY YOUR SELF sereeescenetgeishott 20. If the centripetal force i, BM eee m’* vr‘, find the values of ab alt. t ) a Me, TRY YOuR SELF -",
    answer: "Review needed",
    explanation: "Imported from PDF page 26. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p26_q19_35",
    number: 35,
    chapter: "Units and Measurement",
    subject: "physics",
    type: "subjective",
    question: "The SI unit of energy is J = kgm’s”; that of speed v is ms“ and of acceleration a is ms”, Which of the formulae for Kinetic energy l (__ (K) given below can you rule out on the ba- sis of dimensional arguments (m stands for e the mass of the body): aig DETOUR SELE a) K=m? y3 b) K = (1/2)mv? 21. Magnitude of force experienced by c)K=ma d) K = (3/16)my? object moving with Speed v is giv e) K = (1/2)mv? + ma F= kv’, Find dimensions of k Ps Mo _ > JIL 26",
    answer: "Review needed",
    explanation: "Imported from PDF page 26. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p32_q2_36",
    number: 36,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A man has to go 50 m due north, 40m due east to reach a field. What is his distance and displacement from his house to the field? Answer: B 6m < 50m A",
    answer: "Review needed",
    explanation: "Imported from PDF page 32. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p32_q4_37",
    number: 37,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A particle moves on a circular path of; dius ‘r’, I¢ completes one revolution in4 Calculate distance and displacementi min 20s. Answer: Total time = 2min 20 5 =140s To complete 3 revolutions Time taken = 40 x 3 = 120s Displacement = 0, Distance = 6ar In the remain 20s sec.",
    answer: "Review needed",
    explanation: "Imported from PDF page 32. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p36_q2_38",
    number: 38,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A man walks on a straight road from his home to a market 2.5 km away with a speed of 5 kmh”. Finding the market closed, he instantly turns and walks back home with a speed of 7.5 kmh\". What is the a) magnitude of average velocity, and b) average speed of the man over the in- terval of time (i)0 to 30 min, (ii) 0 to 50 min, (iii) 0 to 40 min?",
    answer: "Review needed",
    explanation: "Imported from PDF page 36. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p36_q3_39",
    number: 39,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A body moves in a straight line along x axis, its distance from the origin is given by the equation x = 8t?- 3t?+ 2t, where xis in 'm' and t in 's'. Find the average veloc- ity of the body in the time interval from t=Otot=I1s. Answer: AX~t_ Ps V t=0s, x(0)=0 Ab t=1s, x(1)=8-3+2=7 Vog=@ ORO =e -1ms \\",
    answer: "Review needed",
    explanation: "Imported from PDF page 36. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p36_q4_40",
    number: 40,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A particle moves on a straight line in such way that it covers 1 half distance with Speed 3m/s and next half distance in 2 equal time intervals with speeds 4.5 m/s and 7.5 m/s respectively. Find average Speed of the particle, 8 4 Answer: bt 4 > For 2\" half distance anh Us 1,",
    answer: "Review needed",
    explanation: "Imported from PDF page 36. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p37_q5_41",
    number: 41,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "The position-time (x-t) grephe for ces children A and B returning from their school O to their homes P'and Q re- - spectively are shown in thé given figure. Ff Choose the correct entries in the brack- 04. A woman starts from her home at 9.00; ets below; can am, walks with a speed of 5 kmh-' on a F ‘ straight road up to her office 2.5 km away, a) ) lives closer to the school stays at the office up to 5.00 pm, and re- than HA). _ - turns home by an auto with a speed of: ct ‘ 3 Ce",
    answer: "Review needed",
    explanation: "Imported from PDF page 37. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p38_q7_42",
    number: 42,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "If a particle travels with speed of 40 m/s l during first half time interval and with \\",
    answer: "Review needed",
    explanation: "Imported from PDF page 38. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p41_q2_43",
    number: 43,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "The given figure is an x-t graph of the mo- tion of a particle.; Q Bp R f S i) At which of the points P, Q, R and S is the velocity v, positive? At which points is the velocity negative? At which points is the velocity zero? At which of the points P, Q, R, and S is",
    answer: "Review needed",
    explanation: "Imported from PDF page 41. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p42_q4_44",
    number: 44,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "The displacement (in metre) of a particle moving along x-axis is given by x = 18t + \" \\. (Af) = BOARD QUESTION",
    answer: "Review needed",
    explanation: "Imported from PDF page 42. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p43_q10_45",
    number: 45,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "The displacement (in meteres) of a body varies with time t (in seconds) is x = t?-2t-3. The velocity at time t=3 s is found to be ~ la Space for keynote: 43",
    answer: "Review needed",
    explanation: "Imported from PDF page 43. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p45_q1_46",
    number: 46,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "Velocity -Time Relation (v = u + at) Velocity after a certain time. By definition, Acceleration = Change in velocity Time taken v-u a at=v-u",
    answer: "Review needed",
    explanation: "Imported from PDF page 45. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p47_q3_47",
    number: 47,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "Figure gives a speed-time graph of a par ticle in motion along a constant direction, Three equal intervals of time are shown, i) lnwhich interval is the average accel- cration greatest in magnitude? ii) In which interval is the average speed greatest? Choosing the positive direction as the constant direction of motion, give the",
    answer: "Review needed",
    explanation: "Imported from PDF page 47. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p48_q1_48",
    number: 48,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "Velocity - time relation _ dv an “at dv=adt Integrating both sides i dv =J; a dt i dv =a in dt (ais constant) [v], =a[t,",
    answer: "Review needed",
    explanation: "Imported from PDF page 48. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p48_q2_49",
    number: 49,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "Position- time relation _ dx ~ dt dx =v dt Integrating both sides x 1 J,, ax= Jovdt Jk dx = J, (u+ atyat",
    answer: "Review needed",
    explanation: "Imported from PDF page 48. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p48_q4_50",
    number: 50,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "Determine the equation of motion using (;, position - velocity relation at dv dx _ dv dy =v ox aa dx dt vdv=adx",
    answer: "Review needed",
    explanation: "Imported from PDF page 48. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p48_q5_51",
    number: 51,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "= a(X-Xo) v2-u2 = 2a(x-Xo) v= uw? + 2a(X-Xp) The advantage of this method is that it can used for motion with non-uniform acceleras also. Ing)! BOARD QUESTION",
    answer: "Review needed",
    explanation: "Imported from PDF page 48. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p48_q5_52",
    number: 52,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A particle starts from rest, accelerate 2m/s’ for 10 s and then goes with const speed for 30s and then decelerates at ‘ s’ till it stops. Find i. What is the maximum velocity. ii. What is the distance travelled by i Answer: i) Velocity after 10 seconds = a x t = 20m Distance mewelleg in 10s",
    answer: "Review needed",
    explanation: "Imported from PDF page 48. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p49_q11_53",
    number: 53,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A body starting from rest accelerates uni- formly along a Straight line at the rate ef 10ms” for 5 seconds. It moves for 2 sec- onds with uniform velocity of 50 ms\", Then it retards uniformly and comes to rest in 3 s. Draw velocity-time graph of the body and find the total distance tray- elled by the body. TRY YOUR SELF",
    answer: "Review needed",
    explanation: "Imported from PDF page 49. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p49_q12_54",
    number: 54,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A bullet travelling with a velocity of 16 ms* penetrates a tree trunk and comes to rest in 0.4 s. The retardation caused by the tree trunk. p",
    answer: "Review needed",
    explanation: "Imported from PDF page 49. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p49_q13_55",
    number: 55,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "Particle starts its journey from rest and moves for Ssec with acceleration 10m/s’, Then it retards with 5m/s? till it stops. Find i. Maximum velocity, ii. Total time taken TRY YOUR SELF “1 TRY YOUR SELF MMe",
    answer: "Review needed",
    explanation: "Imported from PDF page 49. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p49_q14_56",
    number: 56,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A particle starts from rest at t=0 s and undergoes an acceleration a in ms? with time t in seconds which is shown in figure. Draw velocity v in ms” versus time t in second graph for the shown graph? pe a t: ema °°",
    answer: "Review needed",
    explanation: "Imported from PDF page 49. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p50_q1_57",
    number: 57,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A car moving along a Straight highway with speed of 126 kmh: is brought to a stop within a distance of 200 m. What is the retardation of the car (assumed uni- form), and how long does it take for the car to stop? Answer: Speed = 126 x 7 = 35 m/s =v -w 35x35 S= 2a 8S = To",
    answer: "Review needed",
    explanation: "Imported from PDF page 50. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p52_q2_58",
    number: 58,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A stone is dropped from rest from tain height. Determine the veleeite cer. before it reaches the ground a ws e time taken to fall. Answer:",
    answer: "Review needed",
    explanation: "Imported from PDF page 52. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p52_q3_59",
    number: 59,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "32 wb + Kab S 2 AD 4 ay er, C42 > h o rae & r= fae J oS. ee",
    answer: "Review needed",
    explanation: "Imported from PDF page 52. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p55_q3_60",
    number: 60,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A player throws a ball u initial speed of 29.4 a) What is the q during the ball? What are the co tion of the ball its motion? Choose the x = the location an Pwards with an ms\",",
    answer: "Review needed",
    explanation: "Imported from PDF page 55. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p55_q1_61",
    number: 61,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "Upward motion Position - Negative Velocity - Negative Acceleration - Positive",
    answer: "Review needed",
    explanation: "Imported from PDF page 55. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p56_q2_62",
    number: 62,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "Rebound velocity v'= a xy =o x 30V2 =27V2 mis Time to reach highest point = 3y3 + {V2 aN =3v2 +2.7V2 =8.05s > \\. J \\ _ 6",
    answer: "Review needed",
    explanation: "Imported from PDF page 56. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p57_q16_63",
    number: 63,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A stone is dropped from a balloon at an altitude of 300m. How long will the stone take to reach the ground if a) The balloon is ascending with a veloc- ity of Sms\" b) The balloon is descending with a ve- locity of Sms\" c) The balloon is stationary? TRY YOUR SELF",
    answer: "Review needed",
    explanation: "Imported from PDF page 57. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p57_q17_64",
    number: 64,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A body thrown vetically upwards with ve- locity 20 m/s. find the distance and dis- placement after 1 s, 25,3 s and 4s. o.1 TRY YOUR SELF aw",
    answer: "Review needed",
    explanation: "Imported from PDF page 57. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p57_q18_65",
    number: 65,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "An object is thrown vertically upwards with a velocity of 19.6ms\". Calculate the distance and displacement of the object after 3 second?",
    answer: "Review needed",
    explanation: "Imported from PDF page 57. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p59_q1_66",
    number: 66,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "Look at the gra Phs (a) ¢ state, with reasons, whe areal and possibly represent one- tion of a particle,. es (b) Somed.",
    answer: "Review needed",
    explanation: "Imported from PDF page 59. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p64_q1_67",
    number: 67,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "mcq",
    question: "NEGATIVE VECTORS ® Same magnitude but opposite in direction",
    options: ["PARALLEL VECTORS A -- ------p © Having same direction", "ANTI-PARALLEL VECTORS C4 co-PLANAR VECTORS"],
    answer: "Review needed",
    answerIndex: 0,
    explanation: "Imported from PDF page 64. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p67_q2_68",
    number: 68,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "mcq",
    question: "The claim is untrue Because te \" Aleey Wirat ts ite physical significasce 2: 2% mperatur aifferenue can be negative Pp €",
    options: ["The aim is untrue. Because the value of It is defined as a vector having zero magni- gravitational potential energy vary from tude and acting in the arbitrary direction. It point to point in space, is denoted by 8 ale is denoted by 0.", "The claim is true, The value of:, seal; sn! i: change with orientation of tele ar doesn't Properties of null vector:: i) The addition or subtraction of zero vector from a given vector is again the same vec- ~ + 3 o"],
    answer: "Review needed",
    answerIndex: 0,
    explanation: "Imported from PDF page 67. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p68_q5_69",
    number: 69,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "State, for each of the following physical quantities, if itis a scalar or a vector: vo - ume, mass, speed, acceleration, density, number of moles, velocity, angular fre- quency, displacement, angular yee: [NCERT EXERCISE] Ans: Scalar quantities: volume, mass, speed, densi- ty, number of moles.:",
    answer: "Review needed",
    explanation: "Imported from PDF page 68. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p68_q1_70",
    number: 70,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "If fn is a unit vector in the direction of the vector A, then: lal ~_ A C) n=-- D) Fa3x2 IAI ) B=nxA ~\\ 68 eV tay YOUR SELF",
    answer: "Review needed",
    explanation: "Imported from PDF page 68. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p68_q3_71",
    number: 71,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "Threegirlsskating on acircularicegroung of radius 200 m start from a point P on the edge of the ground and reach a point Q diametrically opposite to P following dif. ferent paths as shown. What is the magni- tude of the displacement vector for each? For which girl is this equal to the actual length of path skate? [NCERT EXERCISE] Q 4 A\\ lB",
    answer: "Review needed",
    explanation: "Imported from PDF page 68. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p72_q5_72",
    number: 72,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "Six vectors a to fhave the magnitudes and directions indicated in the figure. Which of the following statements is true? y, ve b - a c ~ --_ d ¢ A) b+c=f B) d+e=f C) dt+e=f D) bte=f",
    answer: "Review needed",
    explanation: "Imported from PDF page 72. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p72_q4_73",
    number: 73,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "What is the differences between the fol- lowing two data? i) 85 km/h east ii) (8 h) x (5 kim/h east). v -_. Find the magnitude and direction of the",
    answer: "Review needed",
    explanation: "Imported from PDF page 72. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p73_q6_74",
    number: 74,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "The resultant of -) two force, ts. one doubl the other in Magnitude, is perpendicular to the smaller of the tw iV i. angle between the forces. Terre Find ie A) 150° c) 90°",
    answer: "Review needed",
    explanation: "Imported from PDF page 73. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p73_q7_75",
    number: 75,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "Which of the following pair of forces will never give resultant force of 2 N: A) 2Nand2N B) l NandiN C) 1Nand3N D) l! Nand4N rc Space for kevnote: vs",
    answer: "Review needed",
    explanation: "Imported from PDF page 73. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p77_q5_76",
    number: 76,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "What is the angle made by vector A=2i+2 j with x-axis? ~ 08. A) B) C) D)",
    answer: "Review needed",
    explanation: "Imported from PDF page 77. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p78_q9_77",
    number: 77,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "If A =3i+2jand B= i-2j+3k, find ~ the magnitudes of A +B and A-B. LS TRY YOUR SELF BL 1A = 3i + 4j then find A",
    answer: "Review needed",
    explanation: "Imported from PDF page 78. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p78_q10_78",
    number: 78,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "If a unit vector is represented by 0.51 + 0.8] + ck, then the value of c is A) l B) von C) al D) 0.39 Ps 1 ‘ A ( - fei TRY YOUR SELF.",
    answer: "Review needed",
    explanation: "Imported from PDF page 78. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p81_q1_79",
    number: 79,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "The position of a particle is given by (¢ = 3.0t i - 2.0t° j + 4.0 k) m where t is in seconds and the coefficients have the proper units for r to be in metres. a) Find the v and a of the particle? b) What is the magnitude and direction of velocity of the particle at t = 2.0 s? [NCERT EXERCISE] Ans; a) v(t)= # = 4 (3.0ti - 2.0tj + 4.0k)",
    answer: "Review needed",
    explanation: "Imported from PDF page 81. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p81_q2_80",
    number: 80,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A particle starts from the origin at t = 0s with a velocity of 10.0j m/s and moves in the x-y plane with a constant acceleration of (8.01 + 2.0j) ms*. a) At what time is the x-coordinate of the particle 16 m? What is the y-coordinate of the particle at that time? b) What is the speed of the particle at that time?",
    answer: "Review needed",
    explanation: "Imported from PDF page 81. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p82_q4_81",
    number: 81,
    chapter: "Motion in a Plane",
    subject: "physics",
    type: "subjective",
    question: "Rain is falling vertically with a speed of 35 m s“. Winds starts blowing af- ter sometime with a speed of 12 ms\" in east to west direction. In which direction should a boy waiting at a bus stop hold his umbrella? km/h km/h",
    answer: "Review needed",
    explanation: "Imported from PDF page 82. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p83_q12_82",
    number: 82,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "The vector joining the points A(J, 1, -1) and B(2, -3, 4) & pointing from A to B is A) -i+ 4] - 5k B) i+ 4j+5k C) i-4j+5k D) -i-4j-5k _ J eq TRY YOUR SELF",
    answer: "Review needed",
    explanation: "Imported from PDF page 83. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p83_q13_83",
    number: 83,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A man is walking on a level road at a speed of 3 km/h. Raindrops fall vertical- ly with a speed of 4 km/h. Find the veloc- ity of raindrops with respect to the men. A) 3km/h B) 4km/h C) Skm/h D) 7km/h &a ~ 83",
    answer: "Review needed",
    explanation: "Imported from PDF page 83. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p84_q15_84",
    number: 84,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A particle starts from origin at t= 0 with a velocity 5.0 i m/s and moves in x-y plane under action of a force which produces a constant acceleration of (3.01 + 2.03) m/s?. A) What is the y-coordinate of the particle at the instant its x-coordinate is 84m? B) What is the speed of the particle at this time? [NCERT EXAMPLE]",
    answer: "Review needed",
    explanation: "Imported from PDF page 84. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p87_q1_85",
    number: 85,
    chapter: "Motion in a Plane",
    subject: "physics",
    type: "subjective",
    question: "A baseball leaves a bat with an initial speed of 37 m/s at an angle of 53°, Find the posi- tion of the ball when t = 2s (treat baseball as a projectile and g = 9.8m/s?) Ans: Along horizontal S,=vVcos 53 x 2=37 x5x2=444m Along vertical S,=vsin 53 x 2+ x 9,8 x 2?=78.8 m",
    answer: "Review needed",
    explanation: "Imported from PDF page 87. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p87_q2_86",
    number: 86,
    chapter: "Motion in a Plane",
    subject: "physics",
    type: "subjective",
    question: "A boy travelling in an open car moving on a levelled road with constant speed tosses a ball vertically up in the air and catches it back. Sketch the motion of the-ball as ob- served by a boy standing on the footpath. Give explanation to support your diagram. [NCERT EXEMPLAR] Ans; The path of the ball observed by a boy stand- ing on the footpath is parabolic. The horizontal",
    answer: "Review needed",
    explanation: "Imported from PDF page 87. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p87_q3_87",
    number: 87,
    chapter: "Motion in a Plane",
    subject: "physics",
    type: "subjective",
    question: "The ceiling of a long hall is 25 m high. What is the maximum horizontal distance that a ball thrown with a speed of 40 m s‘ can go without hitting the ceiling of the hall? [NCERT EXERCISE] Ans: _ usin _ 40° sin’? Binax= 2g >25= 2g sin? 9 = 228 = SONG _ 5 40? 40x40 «(16 sin 0 = YS. = cos 9 = Vi-sin” =“",
    answer: "Review needed",
    explanation: "Imported from PDF page 87. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p87_q4_88",
    number: 88,
    chapter: "Motion in a Plane",
    subject: "physics",
    type: "subjective",
    question: "A cricket ball is thrown at a speed of 28 m s‘in a direction 30° above the hori- noitiel Caleniets A) the maximum height B) the time taken by the ball to return to the same level C) the distance from the thrower to the point where the ball returns to the same level. {[NCERT EXAMPLE] Ans: Here, u= 28 ms\", @ = 30° A) Maximum height,",
    answer: "Review needed",
    explanation: "Imported from PDF page 87. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p88_q16_89",
    number: 89,
    chapter: "Motion in a Plane",
    subject: "physics",
    type: "subjective",
    question: "The path followed by a body projected along y axis is given by y = 3x - (1/2)x2. If g = 10m/s’, then the initial velocity of projectile will be - (x and y are in m ) TRY YOUR SELF > of an oblique - The horizontal",
    answer: "Review needed",
    explanation: "Imported from PDF page 88. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p88_q17_90",
    number: 90,
    chapter: "Motion in a Plane",
    subject: "physics",
    type: "subjective",
    question: "The velocity of projection projectile is (67 + 8j)ms\" range of the projectile is - >» Me, TRY YOUR SELF",
    answer: "Review needed",
    explanation: "Imported from PDF page 88. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p88_q18_91",
    number: 91,
    chapter: "Motion in a Plane",
    subject: "physics",
    type: "subjective",
    question: "The x and y coordinates of the particle i any time are x = 5t-2t* and y = 10t respec. tively, where x and y are in metres and t in seconds. The acceleration of the parti- cle at t= 2 s along x and y axis are ce i 88 e PY d TRY YOUR SELF",
    answer: "Review needed",
    explanation: "Imported from PDF page 88. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p88_q19_92",
    number: 92,
    chapter: "Motion in a Plane",
    subject: "physics",
    type: "subjective",
    question: "A stone of mass m is projected with a ve- locity u at an angle @ with the horizontal. Calculate the value of kinetic energy of the particle at the highest point \\",
    answer: "Review needed",
    explanation: "Imported from PDF page 88. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p89_q1_93",
    number: 93,
    chapter: "Motion in a Plane",
    subject: "physics",
    type: "mcq",
    question: "Displacement a Oe ee 4 7 gt",
    options: ["Trajectory L xX y=7ey", "Time of flight Velocity v= Nu’ + (gt)? v=, where a is the angle between the hor-"],
    answer: "Review needed",
    answerIndex: 0,
    explanation: "Imported from PDF page 89. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p91_q1_94",
    number: 94,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A cricketer can throw a ball to a maxi- mum horizontal distance of 100 m. How much high above the ground can the cricketer throw the same ball? [NCERT EXERCISE] Ans: Let u be the velocity of projection of the ball. The ball will cover maximum horizontal dis- tance when angle of projection with horizontal, 6 =45°.",
    answer: "Review needed",
    explanation: "Imported from PDF page 91. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p91_q2_95",
    number: 95,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A hiker stands on the edge of a cliff 490 m above the ground and throws a stone horizontally with an initial speed of 15 m s', Neglecting air resistance, find the time taken by the stone to reach the ground, and the speed with which it hits the ground. (Take g = 9.8 ms”). [NCERT EXAMPLE] Ans: Time of flight, T = 2B =4 2 awe",
    answer: "Review needed",
    explanation: "Imported from PDF page 91. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p92_q3_96",
    number: 96,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A cyclist starts from the centre O of a circular park of radius 1 km, reaches the edge P of the park, then cycles along the circumference, and returns to the centre along QO as shown in figure. If the round trip takes 10 min, what is the a) net displacement, b) average velocity, and c) average speed of the cyclist? [NCERT EXAMPLE]",
    answer: "Review needed",
    explanation: "Imported from PDF page 92. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p92_q4_97",
    number: 97,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A stone tied to the end of a String 80 cm long is whirled in a horizontal circle with a constant speed. If the stone makes 14 revolutions in 25 s, what is cee magni- tude and direction of acceleration of the stone? [NCERT EXERCISE] > J 92 Ans;",
    answer: "Review needed",
    explanation: "Imported from PDF page 92. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p92_q5_98",
    number: 98,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A body of mass 0.4 kg is whirled in a hori- zontal circle of radius 2 m with a constant speed of 10 ms\". Calculate its i) Angular speed ii) Time period iii) Frequency of revolution iv) Centripetal acceleration. Ans:",
    answer: "Review needed",
    explanation: "Imported from PDF page 92. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p93_q20_99",
    number: 99,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "Two bullets are fired horizontally and si- multaneously towards each other from roof tops of two buildings 100 m apart and of same height of 200 m with the same velocity of 25 m/s. When and where will the two bullets collides. (g = 10 m/s?) ® ae TRY YOUR SELF 21, Find the angle of projection at which the",
    answer: "Review needed",
    explanation: "Imported from PDF page 93. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p93_q22_100",
    number: 100,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "An insect trapped in a circular groove of radius 12 cm moves along the groove stead- ily and completes 7 revolutions in 100 s. a) b) What is the angular speed, and the linear speed of the motion? Is the acceleration vector a constant vec- tor? What is its magnitude?",
    answer: "Review needed",
    explanation: "Imported from PDF page 93. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p93_q23_101",
    number: 101,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A car runs at a constant speed on a cir- cular track of radius 100 m, taking 62.8 s for every circular loop. The average ve- locity and average speed for each circular loop, respectively, is = A) 10 ms, 10 m/s B) 10 m/s, 0 C) 0,0 D) 0,10 m/s a",
    answer: "Review needed",
    explanation: "Imported from PDF page 93. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p94_q1_102",
    number: 102,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A fly wheel rotates about a fixed axis and slows down from 300rpm to 100rpm in 2 minutes. Then its angular retardation in radian/minute’ is fe Because of uniform angular acceleration, we can use the equation of motion in rotation, - O° 0) l 2n(100-300) to 2",
    answer: "Review needed",
    explanation: "Imported from PDF page 94. OCR may contain artifacts. Please review.",
  },
  {
    id: "pdf_p94_q2_103",
    number: 103,
    chapter: "Motion in a Straight Line",
    subject: "physics",
    type: "subjective",
    question: "A car is moving on a circular road of ra. dius 100 m. At some instant its speed fh 20 m/s and is increasing at the rate of 3 m/s’. The magnitude of its acceleration jg Ans: Radius of the circular road, R = 100 m Speed of the car, v = 20 m/s Tangential acceleration, a,= 3 m/s? a= W/R Substituting the known values:",
    answer: "Review needed",
    explanation: "Imported from PDF page 94. OCR may contain artifacts. Please review.",
  },
];

export const PHYSICS_PDF_QUESTION_COUNTS = {
  "Units and Measurement": 35,
  "Motion in a Straight Line": 58,
  "Motion in a Plane": 10
};
