import type { QuizMCQ } from "./quizzes-physics";

export const MATHS_QUIZZES: QuizMCQ[] = [
  // ==================== SETS (m1) — 40 questions ====================
  {
    id: "qmath-m1-001",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Definition of Sets",
    question: "A set is a ___ collection of objects.",
    options: [
      "ordered",
      "unordered but well-defined",
      "random",
      "infinite",
    ],
    correctAnswer: "unordered but well-defined",
    explanation:
      "A set is a well-defined collection of distinct objects; the order of elements does not matter.",
    difficulty: "easy",
    type: "concept",
    tags: ["sets", "definition"],
  },
  {
    id: "qmath-m1-002",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Empty Set",
    question: "The number of elements in the empty set is:",
    options: ["0", "1", "infinite", "undefined"],
    correctAnswer: "0",
    explanation:
      "The empty (null) set ∅ contains no elements; its cardinality is 0.",
    difficulty: "easy",
    type: "concept",
    tags: ["empty set", "cardinality"],
  },
  {
    id: "qmath-m1-003",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Empty Set",
    question: "The empty set is denoted by:",
    options: ["{0}", "∅", "{∅}", "0"],
    correctAnswer: "∅",
    explanation:
      "The empty set is denoted by ∅ (or { }), containing no elements.",
    difficulty: "easy",
    type: "concept",
    tags: ["empty set", "notation"],
  },
  {
    id: "qmath-m1-004",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Singleton Set",
    question: "A set containing exactly one element is called a:",
    options: ["singleton", "empty", "null", "universal"],
    correctAnswer: "singleton",
    explanation:
      "A singleton set has exactly one element, e.g., {5}.",
    difficulty: "easy",
    type: "concept",
    tags: ["singleton set", "types of sets"],
  },
  {
    id: "qmath-m1-005",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Equal Sets",
    question: "Two sets A and B are equal if:",
    options: [
      "n(A) = n(B)",
      "A ⊆ B and B ⊆ A",
      "A ∩ B = ∅",
      "A ∪ B = A",
    ],
    correctAnswer: "A ⊆ B and B ⊆ A",
    explanation:
      "Two sets are equal if and only if each is a subset of the other (A ⊆ B and B ⊆ A).",
    difficulty: "medium",
    type: "concept",
    tags: ["equal sets", "subsets"],
  },
  {
    id: "qmath-m1-006",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Power Set",
    question: "The power set of {1, 2} has how many elements?",
    options: ["2", "4", "8", "1"],
    correctAnswer: "4",
    explanation:
      "If n(A) = 2, then |P(A)| = 2² = 4. The power set is {∅, {1}, {2}, {1,2}}.",
    difficulty: "medium",
    type: "numerical",
    tags: ["power set"],
  },
  {
    id: "qmath-m1-007",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Subsets",
    question: "The number of subsets of a set with n elements is:",
    options: ["n", "2n", "2ⁿ", "n²"],
    correctAnswer: "2ⁿ",
    explanation:
      "A set with n elements has 2ⁿ subsets (including the empty set and the set itself).",
    difficulty: "easy",
    type: "formula",
    tags: ["subsets", "power set"],
  },
  {
    id: "qmath-m1-008",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Power Set",
    question: "The set of all subsets of a set A is called the:",
    options: [
      "universal set",
      "power set",
      "union",
      "intersection",
    ],
    correctAnswer: "power set",
    explanation:
      "The power set P(A) is the set of all subsets of A, including ∅ and A itself.",
    difficulty: "easy",
    type: "concept",
    tags: ["power set", "definition"],
  },
  {
    id: "qmath-m1-009",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Subsets",
    question: "A ⊆ B means:",
    options: [
      "A is a subset of B",
      "B is a subset of A",
      "A equals B",
      "A and B are disjoint",
    ],
    correctAnswer: "A is a subset of B",
    explanation:
      "A ⊆ B reads 'A is a subset of B' — every element of A is also an element of B.",
    difficulty: "easy",
    type: "concept",
    tags: ["subsets", "notation"],
  },
  {
    id: "qmath-m1-010",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Union",
    question: "A ∪ B represents the:",
    options: ["union", "intersection", "difference", "complement"],
    correctAnswer: "union",
    explanation:
      "A ∪ B is the union — the set of all elements that belong to A or B (or both).",
    difficulty: "easy",
    type: "concept",
    tags: ["union", "operations on sets"],
  },
  {
    id: "qmath-m1-011",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Intersection",
    question: "A ∩ B represents the:",
    options: ["union", "intersection", "difference", "complement"],
    correctAnswer: "intersection",
    explanation:
      "A ∩ B is the intersection — the set of elements common to both A and B.",
    difficulty: "easy",
    type: "concept",
    tags: ["intersection", "operations on sets"],
  },
  {
    id: "qmath-m1-012",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Difference of Sets",
    question: "A − B represents:",
    options: [
      "elements in A only",
      "elements in B only",
      "elements in both",
      "elements in neither",
    ],
    correctAnswer: "elements in A only",
    explanation:
      "A − B = {x : x ∈ A and x ∉ B}, the set of elements in A that are not in B.",
    difficulty: "medium",
    type: "concept",
    tags: ["difference", "operations on sets"],
  },
  {
    id: "qmath-m1-013",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Complement",
    question: "A′ represents the:",
    options: [
      "complement of A",
      "union",
      "intersection",
      "power set",
    ],
    correctAnswer: "complement of A",
    explanation:
      "A′ (or Aᶜ) is the complement of A — elements of the universal set U that are not in A.",
    difficulty: "easy",
    type: "concept",
    tags: ["complement", "operations on sets"],
  },
  {
    id: "qmath-m1-014",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "De Morgan's Laws",
    question: "De Morgan's law: (A ∪ B)′ =",
    options: ["A′ ∩ B′", "A′ ∪ B′", "A ∩ B", "A ∪ B"],
    correctAnswer: "A′ ∩ B′",
    explanation:
      "De Morgan's law: complement of union equals intersection of complements: (A ∪ B)′ = A′ ∩ B′.",
    difficulty: "medium",
    type: "formula",
    tags: ["De Morgan's laws", "complement", "union"],
  },
  {
    id: "qmath-m1-015",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "De Morgan's Laws",
    question: "De Morgan's law: (A ∩ B)′ =",
    options: ["A′ ∪ B′", "A′ ∩ B′", "A ∪ B", "A ∩ B"],
    correctAnswer: "A′ ∪ B′",
    explanation:
      "De Morgan's law: complement of intersection equals union of complements: (A ∩ B)′ = A′ ∪ B′.",
    difficulty: "medium",
    type: "formula",
    tags: ["De Morgan's laws", "complement", "intersection"],
  },
  {
    id: "qmath-m1-016",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Cardinality Formula",
    question: "The formula n(A ∪ B) equals:",
    options: [
      "n(A) + n(B) − n(A ∩ B)",
      "n(A) + n(B)",
      "n(A) × n(B)",
      "n(A) − n(B)",
    ],
    correctAnswer: "n(A) + n(B) − n(A ∩ B)",
    explanation:
      "By inclusion-exclusion: n(A ∪ B) = n(A) + n(B) − n(A ∩ B), to avoid double-counting common elements.",
    difficulty: "medium",
    type: "formula",
    tags: ["cardinality", "inclusion-exclusion"],
  },
  {
    id: "qmath-m1-017",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Union",
    question: "If A = {1, 2, 3} and B = {2, 3, 4}, then A ∪ B =",
    options: [
      "{1, 2, 3, 4}",
      "{2, 3}",
      "{1, 4}",
      "∅",
    ],
    correctAnswer: "{1, 2, 3, 4}",
    explanation:
      "A ∪ B contains all elements in either set: {1, 2, 3, 4}.",
    difficulty: "easy",
    type: "numerical",
    tags: ["union", "examples"],
  },
  {
    id: "qmath-m1-018",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Intersection",
    question: "If A = {1, 2, 3} and B = {2, 3, 4}, then A ∩ B =",
    options: [
      "{1, 2, 3, 4}",
      "{2, 3}",
      "{1, 4}",
      "∅",
    ],
    correctAnswer: "{2, 3}",
    explanation:
      "A ∩ B contains elements common to both: {2, 3}.",
    difficulty: "easy",
    type: "numerical",
    tags: ["intersection", "examples"],
  },
  {
    id: "qmath-m1-019",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Difference of Sets",
    question: "If A = {1, 2, 3} and B = {2, 3, 4}, then A − B =",
    options: ["{1}", "{4}", "{1, 2, 3}", "{2, 3}"],
    correctAnswer: "{1}",
    explanation:
      "A − B = elements in A but not in B = {1}.",
    difficulty: "easy",
    type: "numerical",
    tags: ["difference", "examples"],
  },
  {
    id: "qmath-m1-020",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Universal Set",
    question: "The universal set contains:",
    options: [
      "all elements under consideration",
      "only one element",
      "no elements",
      "all subsets",
    ],
    correctAnswer: "all elements under consideration",
    explanation:
      "The universal set U is the base set containing all elements relevant to a particular problem.",
    difficulty: "easy",
    type: "concept",
    tags: ["universal set"],
  },
  {
    id: "qmath-m1-021",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Power Set",
    question: "The number of elements in the power set of {a, b, c} is:",
    options: ["3", "6", "8", "9"],
    correctAnswer: "8",
    explanation:
      "If n(A) = 3, then |P(A)| = 2³ = 8.",
    difficulty: "medium",
    type: "numerical",
    tags: ["power set"],
  },
  {
    id: "qmath-m1-022",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Proper Subsets",
    question: "If n(A) = 5, the number of proper subsets of A is:",
    options: ["32", "31", "5", "10"],
    correctAnswer: "31",
    explanation:
      "Total subsets = 2⁵ = 32. Proper subsets exclude A itself, so 32 − 1 = 31.",
    difficulty: "medium",
    type: "numerical",
    tags: ["proper subsets", "power set"],
  },
  {
    id: "qmath-m1-023",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Finite vs Infinite Sets",
    question: "The set of natural numbers N is:",
    options: ["finite", "infinite", "empty", "singleton"],
    correctAnswer: "infinite",
    explanation:
      "There are infinitely many natural numbers (1, 2, 3, ...), so N is an infinite set.",
    difficulty: "easy",
    type: "concept",
    tags: ["finite sets", "infinite sets", "natural numbers"],
  },
  {
    id: "qmath-m1-024",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Set Builder Form",
    question: "The set {x : x is prime and x ≤ 10} equals:",
    options: [
      "{2, 3, 5, 7}",
      "{1, 2, 3, 5, 7}",
      "{2, 3, 5, 7, 9}",
      "{1, 3, 5, 7}",
    ],
    correctAnswer: "{2, 3, 5, 7}",
    explanation:
      "Primes ≤ 10 are 2, 3, 5, 7. (1 is not prime.)",
    difficulty: "medium",
    type: "numerical",
    tags: ["set builder form", "prime numbers"],
  },
  {
    id: "qmath-m1-025",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Subsets",
    question: "If A = {1, 2} and B = {1, 2, 3}, then A is a ___ of B.",
    options: ["superset", "proper subset", "equal set", "disjoint set"],
    correctAnswer: "proper subset",
    explanation:
      "Every element of A is in B, but A ≠ B, so A is a proper subset of B (A ⊂ B).",
    difficulty: "easy",
    type: "concept",
    tags: ["proper subset"],
  },
  {
    id: "qmath-m1-026",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Disjoint Sets",
    question: "Two sets are disjoint if:",
    options: [
      "A ∩ B = ∅",
      "A ∪ B = ∅",
      "A ⊆ B",
      "A = B",
    ],
    correctAnswer: "A ∩ B = ∅",
    explanation:
      "Disjoint sets have no elements in common, so their intersection is the empty set.",
    difficulty: "easy",
    type: "concept",
    tags: ["disjoint sets"],
  },
  {
    id: "qmath-m1-027",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Idempotent Law",
    question: "A ∪ A equals:",
    options: ["A", "∅", "U", "A′"],
    correctAnswer: "A",
    explanation:
      "Idempotent law: A ∪ A = A (union of a set with itself is the set).",
    difficulty: "easy",
    type: "formula",
    tags: ["idempotent law", "union"],
  },
  {
    id: "qmath-m1-028",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Complement Laws",
    question: "A ∩ A′ equals:",
    options: ["A", "∅", "U", "A′"],
    correctAnswer: "∅",
    explanation:
      "A set and its complement have no common elements, so A ∩ A′ = ∅.",
    difficulty: "easy",
    type: "formula",
    tags: ["complement laws", "intersection"],
  },
  {
    id: "qmath-m1-029",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Complement Laws",
    question: "A ∪ A′ equals:",
    options: ["A", "∅", "U", "A′"],
    correctAnswer: "U",
    explanation:
      "A set together with its complement covers the entire universal set: A ∪ A′ = U.",
    difficulty: "easy",
    type: "formula",
    tags: ["complement laws", "union"],
  },
  {
    id: "qmath-m1-030",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Identity Law",
    question: "A ∪ ∅ equals:",
    options: ["A", "∅", "U", "A′"],
    correctAnswer: "A",
    explanation:
      "Identity law: union with the empty set leaves the set unchanged: A ∪ ∅ = A.",
    difficulty: "easy",
    type: "formula",
    tags: ["identity law", "union", "empty set"],
  },
  {
    id: "qmath-m1-031",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Identity Law",
    question: "A ∩ ∅ equals:",
    options: ["A", "∅", "U", "A′"],
    correctAnswer: "∅",
    explanation:
      "Intersection with the empty set is always empty: A ∩ ∅ = ∅.",
    difficulty: "easy",
    type: "formula",
    tags: ["identity law", "intersection", "empty set"],
  },
  {
    id: "qmath-m1-032",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Difference of Sets",
    question: "The set {x : x ∈ A and x ∉ B} is:",
    options: ["A − B", "A ∪ B", "A ∩ B", "B − A"],
    correctAnswer: "A − B",
    explanation:
      "Elements in A but not in B define the difference A − B.",
    difficulty: "medium",
    type: "concept",
    tags: ["difference of sets"],
  },
  {
    id: "qmath-m1-033",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Cardinality Formula",
    question: "If n(A) = 4, n(B) = 5, and n(A ∩ B) = 2, then n(A ∪ B) =",
    options: ["7", "9", "11", "3"],
    correctAnswer: "7",
    explanation:
      "n(A ∪ B) = n(A) + n(B) − n(A ∩ B) = 4 + 5 − 2 = 7.",
    difficulty: "medium",
    type: "numerical",
    tags: ["cardinality", "inclusion-exclusion"],
  },
  {
    id: "qmath-m1-034",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Word Problems",
    question:
      "In a class, 25 play cricket, 20 play football, and 10 play both. The total number of students is:",
    options: ["35", "55", "45", "25"],
    correctAnswer: "35",
    explanation:
      "n(C ∪ F) = 25 + 20 − 10 = 35 students.",
    difficulty: "medium",
    type: "numerical",
    tags: ["word problems", "inclusion-exclusion"],
  },
  {
    id: "qmath-m1-035",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Distinct Elements",
    question: "The set A = {1, 1, 2, 2, 3} is actually equal to:",
    options: ["{1, 2, 3}", "invalid set", "{1, 1, 2, 2, 3}", "{3, 2, 1}"],
    correctAnswer: "{1, 2, 3}",
    explanation:
      "Sets contain distinct elements; repetitions are ignored, so A = {1, 2, 3}.",
    difficulty: "easy",
    type: "concept",
    tags: ["distinct elements", "definition of sets"],
  },
  {
    id: "qmath-m1-036",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Empty Set",
    question: "The cardinality of ∅ is:",
    options: ["0", "1", "infinite", "undefined"],
    correctAnswer: "0",
    explanation:
      "The empty set has no elements, so n(∅) = 0.",
    difficulty: "easy",
    type: "concept",
    tags: ["empty set", "cardinality"],
  },
  {
    id: "qmath-m1-037",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Equal Sets",
    question: "If A ⊆ B and B ⊆ A, then:",
    options: ["A = B", "A ⊂ B", "B ⊂ A", "A and B are disjoint"],
    correctAnswer: "A = B",
    explanation:
      "If each set is a subset of the other, they contain exactly the same elements, so A = B.",
    difficulty: "medium",
    type: "concept",
    tags: ["equal sets", "subsets"],
  },
  {
    id: "qmath-m1-038",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Set Builder Form",
    question: "The set-builder form of {2, 4, 6, 8} is:",
    options: [
      "{x : x is even and 1 ≤ x ≤ 8}",
      "{x : x < 10}",
      "{x : x is prime}",
      "{x : x is odd}",
    ],
    correctAnswer: "{x : x is even and 1 ≤ x ≤ 8}",
    explanation:
      "The set contains even numbers from 2 to 8, i.e., {x : x is even, 1 ≤ x ≤ 8}.",
    difficulty: "medium",
    type: "concept",
    tags: ["set builder form", "even numbers"],
  },
  {
    id: "qmath-m1-039",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Power Set",
    question: "The power set of the empty set is:",
    options: ["{∅}", "∅", "{0}", "0"],
    correctAnswer: "{∅}",
    explanation:
      "P(∅) = {∅}, since the only subset of ∅ is ∅ itself.",
    difficulty: "hard",
    type: "concept",
    tags: ["power set", "empty set"],
  },
  {
    id: "qmath-m1-040",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m1",
    chapter: "Sets",
    topic: "Involution Law",
    question: "(A′)′ equals:",
    options: ["A", "A′", "U", "∅"],
    correctAnswer: "A",
    explanation:
      "Involution (double complement) law: the complement of the complement of A is A itself.",
    difficulty: "medium",
    type: "formula",
    tags: ["involution law", "complement"],
  },

  // ==================== RELATIONS AND FUNCTIONS (m2) — 35 questions ====================
  {
    id: "qmath-m2-001",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Cartesian Product",
    question: "The Cartesian product A × B is the set of:",
    options: [
      "all ordered pairs (a, b)",
      "all elements of A and B",
      "the intersection",
      "the union",
    ],
    correctAnswer: "all ordered pairs (a, b)",
    explanation:
      "A × B = {(a, b) : a ∈ A, b ∈ B}, the set of all ordered pairs with first element from A and second from B.",
    difficulty: "easy",
    type: "concept",
    tags: ["cartesian product"],
  },
  {
    id: "qmath-m2-002",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Cartesian Product",
    question: "If n(A) = 2 and n(B) = 3, then n(A × B) =",
    options: ["5", "6", "8", "9"],
    correctAnswer: "6",
    explanation: "n(A × B) = n(A) × n(B) = 2 × 3 = 6.",
    difficulty: "easy",
    type: "numerical",
    tags: ["cartesian product", "cardinality"],
  },
  {
    id: "qmath-m2-003",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Relations",
    question: "A relation from A to B is a subset of:",
    options: ["A", "B", "A × B", "A ∪ B"],
    correctAnswer: "A × B",
    explanation:
      "A relation R from A to B is any subset of the Cartesian product A × B.",
    difficulty: "easy",
    type: "concept",
    tags: ["relations", "cartesian product"],
  },
  {
    id: "qmath-m2-004",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Domain and Range",
    question: "The domain of a relation is the set of:",
    options: [
      "first elements",
      "second elements",
      "both",
      "neither",
    ],
    correctAnswer: "first elements",
    explanation:
      "Domain = set of all first elements (a) of the ordered pairs (a, b) in the relation.",
    difficulty: "easy",
    type: "concept",
    tags: ["domain", "relations"],
  },
  {
    id: "qmath-m2-005",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Domain and Range",
    question: "The range of a relation is the set of:",
    options: [
      "first elements",
      "second elements",
      "both",
      "neither",
    ],
    correctAnswer: "second elements",
    explanation:
      "Range = set of all second elements (b) of the ordered pairs (a, b) in the relation.",
    difficulty: "easy",
    type: "concept",
    tags: ["range", "relations"],
  },
  {
    id: "qmath-m2-006",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Functions",
    question: "A function is a relation in which:",
    options: [
      "each first element has exactly one second element",
      "each second element has one first element",
      "no elements are paired",
      "all elements are paired",
    ],
    correctAnswer: "each first element has exactly one second element",
    explanation:
      "A function from A to B is a relation where every element of A has exactly one image in B.",
    difficulty: "medium",
    type: "concept",
    tags: ["functions", "definition"],
  },
  {
    id: "qmath-m2-007",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Number of Functions",
    question:
      "If n(A) = m and n(B) = n, the number of functions from A to B is:",
    options: ["m × n", "n^m", "m^n", "m + n"],
    correctAnswer: "n^m",
    explanation:
      "Each of the m elements of A has n choices in B, so the number of functions = nᵐ.",
    difficulty: "hard",
    type: "formula",
    tags: ["number of functions"],
  },
  {
    id: "qmath-m2-008",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Vertical Line Test",
    question: "The vertical line test is used to check if a relation is a:",
    options: ["function", "set", "sequence", "series"],
    correctAnswer: "function",
    explanation:
      "If every vertical line intersects the graph at most once, the relation is a function.",
    difficulty: "medium",
    type: "concept",
    tags: ["vertical line test", "functions"],
  },
  {
    id: "qmath-m2-009",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Identity Function",
    question: "A function f: A → A such that f(x) = x is called the:",
    options: ["identity", "constant", "onto", "one-one"],
    correctAnswer: "identity",
    explanation:
      "The identity function maps each element to itself: f(x) = x for all x ∈ A.",
    difficulty: "easy",
    type: "concept",
    tags: ["identity function"],
  },
  {
    id: "qmath-m2-010",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Constant Function",
    question: "A function f(x) = c (for some constant c) is called a:",
    options: ["identity", "constant", "one-one", "bijective"],
    correctAnswer: "constant",
    explanation:
      "A constant function assigns the same value c to every input: f(x) = c for all x.",
    difficulty: "easy",
    type: "concept",
    tags: ["constant function"],
  },
  {
    id: "qmath-m2-011",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Number of Relations",
    question: "The number of relations from A to A if n(A) = 2 is:",
    options: ["4", "8", "16", "2"],
    correctAnswer: "16",
    explanation:
      "n(A × A) = 4. Number of relations = 2⁴ = 16 (since each subset of A × A is a relation).",
    difficulty: "hard",
    type: "numerical",
    tags: ["number of relations"],
  },
  {
    id: "qmath-m2-012",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Cartesian Product",
    question: "If A = {1, 2} and B = {a, b}, then A × B =",
    options: [
      "{(1, a), (1, b), (2, a), (2, b)}",
      "{1, 2, a, b}",
      "{(1, 1), (2, 2)}",
      "{(a, 1), (b, 2)}",
    ],
    correctAnswer: "{(1, a), (1, b), (2, a), (2, b)}",
    explanation:
      "A × B contains all ordered pairs with first element from A and second from B.",
    difficulty: "easy",
    type: "numerical",
    tags: ["cartesian product", "examples"],
  },
  {
    id: "qmath-m2-013",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Function Evaluation",
    question: "If f(x) = 2x + 3, then f(2) =",
    options: ["4", "7", "5", "8"],
    correctAnswer: "7",
    explanation: "f(2) = 2(2) + 3 = 4 + 3 = 7.",
    difficulty: "easy",
    type: "numerical",
    tags: ["function evaluation"],
  },
  {
    id: "qmath-m2-014",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Function Evaluation",
    question: "If f(x) = x², then f(−3) =",
    options: ["9", "-9", "6", "-6"],
    correctAnswer: "9",
    explanation: "f(−3) = (−3)² = 9.",
    difficulty: "easy",
    type: "numerical",
    tags: ["function evaluation"],
  },
  {
    id: "qmath-m2-015",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Types of Functions",
    question: "A function that is both one-one and onto is called:",
    options: ["bijective", "surjective", "injective", "identity"],
    correctAnswer: "bijective",
    explanation:
      "A bijection (bijective function) is both injective (one-one) and surjective (onto).",
    difficulty: "medium",
    type: "concept",
    tags: ["bijective", "types of functions"],
  },
  {
    id: "qmath-m2-016",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Domain",
    question: "The domain of f(x) = 1/x is:",
    options: ["R − {0}", "R", "R⁺", "{0}"],
    correctAnswer: "R − {0}",
    explanation:
      "1/x is undefined at x = 0, so the domain is all real numbers except 0.",
    difficulty: "medium",
    type: "concept",
    tags: ["domain", "rational functions"],
  },
  {
    id: "qmath-m2-017",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Domain",
    question: "The domain of f(x) = √x is:",
    options: ["R⁺ ∪ {0}", "R", "R⁻", "R − {0}"],
    correctAnswer: "R⁺ ∪ {0}",
    explanation:
      "Square root is defined only for non-negative numbers, so domain = [0, ∞) = R⁺ ∪ {0}.",
    difficulty: "medium",
    type: "concept",
    tags: ["domain", "square root"],
  },
  {
    id: "qmath-m2-018",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Types of Functions",
    question: "f(x) = x² (over R) is:",
    options: ["one-one", "many-one", "bijective", "constant"],
    correctAnswer: "many-one",
    explanation:
      "Since x² = (−x)², two different inputs give the same output; so f(x) = x² is many-one over R.",
    difficulty: "medium",
    type: "concept",
    tags: ["types of functions", "many-one"],
  },
  {
    id: "qmath-m2-019",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Range",
    question: "The range of f(x) = x² (over R) is:",
    options: ["R", "R⁺ ∪ {0}", "R⁻", "R⁺"],
    correctAnswer: "R⁺ ∪ {0}",
    explanation:
      "Squares are always non-negative, so range = [0, ∞) = R⁺ ∪ {0}.",
    difficulty: "medium",
    type: "concept",
    tags: ["range", "quadratic functions"],
  },
  {
    id: "qmath-m2-020",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Function Evaluation",
    question: "If f(x) = 2x, then f(0) =",
    options: ["0", "1", "2", "undefined"],
    correctAnswer: "0",
    explanation: "f(0) = 2(0) = 0.",
    difficulty: "easy",
    type: "numerical",
    tags: ["function evaluation"],
  },
  {
    id: "qmath-m2-021",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Constant Function",
    question: "A real-valued function f(x) = 5 for all x is a:",
    options: ["constant", "identity", "one-one", "onto"],
    correctAnswer: "constant",
    explanation:
      "Since f(x) = 5 for every x, the function is constant (every input maps to 5).",
    difficulty: "easy",
    type: "concept",
    tags: ["constant function"],
  },
  {
    id: "qmath-m2-022",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Reflexive Relation",
    question: "A relation R on A is reflexive if:",
    options: [
      "(a, a) ∈ R for all a ∈ A",
      "(a, b) ∈ R ⟹ (b, a) ∈ R",
      "(a, b), (b, c) ∈ R ⟹ (a, c) ∈ R",
      "(a, a) ∉ R",
    ],
    correctAnswer: "(a, a) ∈ R for all a ∈ A",
    explanation:
      "Reflexive: every element must be related to itself — (a, a) ∈ R for all a ∈ A.",
    difficulty: "medium",
    type: "concept",
    tags: ["reflexive", "types of relations"],
  },
  {
    id: "qmath-m2-023",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Symmetric Relation",
    question: "A relation R is symmetric if:",
    options: [
      "(a, b) ∈ R ⟹ (b, a) ∈ R",
      "(a, a) ∈ R",
      "(a, b), (b, c) ⟹ (a, c)",
      "always true",
    ],
    correctAnswer: "(a, b) ∈ R ⟹ (b, a) ∈ R",
    explanation:
      "Symmetric: if a is related to b, then b must be related to a.",
    difficulty: "medium",
    type: "concept",
    tags: ["symmetric", "types of relations"],
  },
  {
    id: "qmath-m2-024",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Transitive Relation",
    question: "A relation R is transitive if:",
    options: [
      "(a, b) ∈ R and (b, c) ∈ R ⟹ (a, c) ∈ R",
      "(a, b) ⟹ (b, a)",
      "(a, a) ∈ R",
      "always true",
    ],
    correctAnswer: "(a, b) ∈ R and (b, c) ∈ R ⟹ (a, c) ∈ R",
    explanation:
      "Transitive: if a is related to b and b is related to c, then a must be related to c.",
    difficulty: "medium",
    type: "concept",
    tags: ["transitive", "types of relations"],
  },
  {
    id: "qmath-m2-025",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Equivalence Relation",
    question:
      "A relation that is reflexive, symmetric, and transitive is called:",
    options: ["equivalence", "identity", "function", "empty"],
    correctAnswer: "equivalence",
    explanation:
      "An equivalence relation satisfies all three properties: reflexive, symmetric, and transitive.",
    difficulty: "medium",
    type: "concept",
    tags: ["equivalence relation"],
  },
  {
    id: "qmath-m2-026",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Identity Function",
    question: "The function f: R → R with f(x) = x is of which type?",
    options: ["identity", "constant", "onto only", "one-one only"],
    correctAnswer: "identity",
    explanation:
      "f(x) = x is the identity function (and it is also bijective).",
    difficulty: "easy",
    type: "concept",
    tags: ["identity function"],
  },
  {
    id: "qmath-m2-027",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "One-One Functions",
    question:
      "The number of one-one functions from A to A where n(A) = n is:",
    options: ["n!", "2ⁿ", "n²", "n"],
    correctAnswer: "n!",
    explanation:
      "A one-one function from A to A is a permutation, and there are n! permutations of n elements.",
    difficulty: "hard",
    type: "formula",
    tags: ["one-one functions", "permutations"],
  },
  {
    id: "qmath-m2-028",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Codomain",
    question: "The codomain of a function f: A → B is:",
    options: ["B", "A", "A × B", "a subset of B"],
    correctAnswer: "B",
    explanation:
      "For f: A → B, B is the codomain (the set into which the function maps); the range is a subset of B.",
    difficulty: "medium",
    type: "concept",
    tags: ["codomain", "functions"],
  },
  {
    id: "qmath-m2-029",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Onto Function",
    question: "A function is onto if its range equals its:",
    options: ["codomain", "domain", "A × B", "empty set"],
    correctAnswer: "codomain",
    explanation:
      "A function is onto (surjective) when every element of the codomain is the image of some element, i.e., range = codomain.",
    difficulty: "medium",
    type: "concept",
    tags: ["onto function", "surjective"],
  },
  {
    id: "qmath-m2-030",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Function Evaluation",
    question: "If f(x) = x² + 1, then f(−1) =",
    options: ["2", "0", "1", "-2"],
    correctAnswer: "2",
    explanation: "f(−1) = (−1)² + 1 = 1 + 1 = 2.",
    difficulty: "easy",
    type: "numerical",
    tags: ["function evaluation"],
  },
  {
    id: "qmath-m2-031",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Reflexive Relations",
    question:
      "If A = {1, 2, 3}, the number of reflexive relations on A is:",
    options: ["8", "64", "512", "27"],
    correctAnswer: "64",
    explanation:
      "Total ordered pairs = n² = 9. Reflexive pairs (3) are fixed; remaining 6 can be chosen freely: 2⁶ = 64.",
    difficulty: "hard",
    type: "numerical",
    tags: ["reflexive relations", "counting"],
  },
  {
    id: "qmath-m2-032",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Cartesian Product",
    question: "A × B = ∅ when:",
    options: [
      "A = ∅ or B = ∅",
      "A = B",
      "A ⊂ B",
      "never",
    ],
    correctAnswer: "A = ∅ or B = ∅",
    explanation:
      "If either set is empty, no ordered pairs can be formed, so A × B = ∅.",
    difficulty: "medium",
    type: "concept",
    tags: ["cartesian product", "empty set"],
  },
  {
    id: "qmath-m2-033",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Types of Functions",
    question: "The function f(x) = |x| is:",
    options: ["one-one", "many-one", "onto", "bijective"],
    correctAnswer: "many-one",
    explanation:
      "Since |x| = |−x|, two different inputs can give the same output, so |x| is many-one over R.",
    difficulty: "medium",
    type: "concept",
    tags: ["modulus function", "many-one"],
  },
  {
    id: "qmath-m2-034",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Equivalence Relation",
    question: "The relation 'is equal to' on a set is:",
    options: [
      "equivalence",
      "only reflexive",
      "only symmetric",
      "none",
    ],
    correctAnswer: "equivalence",
    explanation:
      "Equality is reflexive (a = a), symmetric (a = b ⟹ b = a), and transitive (a = b, b = c ⟹ a = c), so it is an equivalence relation.",
    difficulty: "medium",
    type: "concept",
    tags: ["equivalence relation", "equality"],
  },
  {
    id: "qmath-m2-035",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m2",
    chapter: "Relations and Functions",
    topic: "Types of Relations",
    question: "The relation 'is less than' on R is:",
    options: [
      "transitive only",
      "symmetric only",
      "reflexive only",
      "equivalence",
    ],
    correctAnswer: "transitive only",
    explanation:
      "'Less than' is transitive (a < b, b < c ⟹ a < c) but not reflexive (a ≮ a) and not symmetric (a < b ≢ b < a).",
    difficulty: "hard",
    type: "concept",
    tags: ["types of relations", "transitive"],
  },

  // ==================== TRIGONOMETRIC FUNCTIONS (m3) — 40 questions ====================
  {
    id: "qmath-m3-001",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Radian Measure",
    question: "π radians equals how many degrees?",
    options: ["90°", "180°", "270°", "360°"],
    correctAnswer: "180°",
    explanation:
      "π radians = 180°. This is the key conversion between radians and degrees.",
    difficulty: "easy",
    type: "formula",
    tags: ["radian measure", "conversion"],
  },
  {
    id: "qmath-m3-002",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Radian Measure",
    question: "1 radian is approximately equal to:",
    options: ["57.3°", "90°", "45°", "30°"],
    correctAnswer: "57.3°",
    explanation:
      "1 rad = 180°/π ≈ 57.3°.",
    difficulty: "easy",
    type: "formula",
    tags: ["radian measure", "conversion"],
  },
  {
    id: "qmath-m3-003",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Degree-Radian Conversion",
    question: "30° in radians is:",
    options: ["π/6", "π/3", "π/4", "π/2"],
    correctAnswer: "π/6",
    explanation: "30° = 30 × π/180 = π/6 radians.",
    difficulty: "easy",
    type: "numerical",
    tags: ["degree-radian conversion"],
  },
  {
    id: "qmath-m3-004",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Degree-Radian Conversion",
    question: "45° in radians is:",
    options: ["π/6", "π/4", "π/3", "π/2"],
    correctAnswer: "π/4",
    explanation: "45° = 45 × π/180 = π/4 radians.",
    difficulty: "easy",
    type: "numerical",
    tags: ["degree-radian conversion"],
  },
  {
    id: "qmath-m3-005",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Degree-Radian Conversion",
    question: "60° in radians is:",
    options: ["π/3", "π/6", "π/4", "π/2"],
    correctAnswer: "π/3",
    explanation: "60° = 60 × π/180 = π/3 radians.",
    difficulty: "easy",
    type: "numerical",
    tags: ["degree-radian conversion"],
  },
  {
    id: "qmath-m3-006",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Degree-Radian Conversion",
    question: "90° in radians is:",
    options: ["π/2", "π", "2π", "π/4"],
    correctAnswer: "π/2",
    explanation: "90° = 90 × π/180 = π/2 radians.",
    difficulty: "easy",
    type: "numerical",
    tags: ["degree-radian conversion"],
  },
  {
    id: "qmath-m3-007",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Trigonometric Ratios",
    question: "sin 30° =",
    options: ["1/2", "√3/2", "1", "√2/2"],
    correctAnswer: "1/2",
    explanation: "sin 30° = 1/2.",
    difficulty: "easy",
    type: "formula",
    tags: ["trigonometric ratios", "standard angles"],
  },
  {
    id: "qmath-m3-008",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Trigonometric Ratios",
    question: "cos 60° =",
    options: ["1/2", "√3/2", "0", "1"],
    correctAnswer: "1/2",
    explanation: "cos 60° = 1/2.",
    difficulty: "easy",
    type: "formula",
    tags: ["trigonometric ratios", "standard angles"],
  },
  {
    id: "qmath-m3-009",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Trigonometric Ratios",
    question: "tan 45° =",
    options: ["0", "1", "√3", "undefined"],
    correctAnswer: "1",
    explanation: "tan 45° = sin 45°/cos 45° = 1.",
    difficulty: "easy",
    type: "formula",
    tags: ["trigonometric ratios", "standard angles"],
  },
  {
    id: "qmath-m3-010",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Trigonometric Ratios",
    question: "sin 90° =",
    options: ["0", "1/2", "1", "√3/2"],
    correctAnswer: "1",
    explanation: "sin 90° = 1 (maximum value of sine).",
    difficulty: "easy",
    type: "formula",
    tags: ["trigonometric ratios", "standard angles"],
  },
  {
    id: "qmath-m3-011",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Pythagorean Identity",
    question: "sin²θ + cos²θ =",
    options: ["0", "1", "2", "sin 2θ"],
    correctAnswer: "1",
    explanation:
      "The fundamental Pythagorean identity: sin²θ + cos²θ = 1 for all θ.",
    difficulty: "easy",
    type: "formula",
    tags: ["identities", "Pythagorean identity"],
  },
  {
    id: "qmath-m3-012",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Identities",
    question: "1 + tan²θ =",
    options: ["sec²θ", "cosec²θ", "cot²θ", "sin²θ"],
    correctAnswer: "sec²θ",
    explanation:
      "Dividing sin²θ + cos²θ = 1 by cos²θ gives 1 + tan²θ = sec²θ.",
    difficulty: "medium",
    type: "formula",
    tags: ["identities", "secant", "tangent"],
  },
  {
    id: "qmath-m3-013",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Identities",
    question: "1 + cot²θ =",
    options: ["cosec²θ", "sec²θ", "tan²θ", "cos²θ"],
    correctAnswer: "cosec²θ",
    explanation:
      "Dividing sin²θ + cos²θ = 1 by sin²θ gives 1 + cot²θ = cosec²θ.",
    difficulty: "medium",
    type: "formula",
    tags: ["identities", "cosecant", "cotangent"],
  },
  {
    id: "qmath-m3-014",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Allied Angles",
    question: "sin(90° − θ) =",
    options: ["cos θ", "sin θ", "tan θ", "cot θ"],
    correctAnswer: "cos θ",
    explanation:
      "Co-function identity: sin(90° − θ) = cos θ.",
    difficulty: "medium",
    type: "formula",
    tags: ["allied angles", "co-function identity"],
  },
  {
    id: "qmath-m3-015",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Allied Angles",
    question: "cos(90° − θ) =",
    options: ["sin θ", "cos θ", "tan θ", "sec θ"],
    correctAnswer: "sin θ",
    explanation:
      "Co-function identity: cos(90° − θ) = sin θ.",
    difficulty: "medium",
    type: "formula",
    tags: ["allied angles", "co-function identity"],
  },
  {
    id: "qmath-m3-016",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Allied Angles",
    question: "sin(180° − θ) =",
    options: ["sin θ", "-sin θ", "cos θ", "-cos θ"],
    correctAnswer: "sin θ",
    explanation:
      "In Quadrant II (180° − θ), sin is positive, so sin(180° − θ) = sin θ.",
    difficulty: "medium",
    type: "formula",
    tags: ["allied angles", "quadrants"],
  },
  {
    id: "qmath-m3-017",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Allied Angles",
    question: "cos(180° − θ) =",
    options: ["-cos θ", "cos θ", "sin θ", "-sin θ"],
    correctAnswer: "-cos θ",
    explanation:
      "In Quadrant II (180° − θ), cos is negative, so cos(180° − θ) = -cos θ.",
    difficulty: "medium",
    type: "formula",
    tags: ["allied angles", "quadrants"],
  },
  {
    id: "qmath-m3-018",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Allied Angles",
    question: "tan(180° − θ) =",
    options: ["-tan θ", "tan θ", "cot θ", "-cot θ"],
    correctAnswer: "-tan θ",
    explanation:
      "In Quadrant II, tan is negative, so tan(180° − θ) = -tan θ.",
    difficulty: "medium",
    type: "formula",
    tags: ["allied angles", "quadrants"],
  },
  {
    id: "qmath-m3-019",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Odd-Even Functions",
    question: "sin(−θ) =",
    options: ["-sin θ", "sin θ", "cos θ", "-cos θ"],
    correctAnswer: "-sin θ",
    explanation:
      "Sine is an odd function: sin(−θ) = -sin θ.",
    difficulty: "easy",
    type: "formula",
    tags: ["odd-even", "negative angles"],
  },
  {
    id: "qmath-m3-020",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Odd-Even Functions",
    question: "cos(−θ) =",
    options: ["cos θ", "-cos θ", "sin θ", "-sin θ"],
    correctAnswer: "cos θ",
    explanation:
      "Cosine is an even function: cos(−θ) = cos θ.",
    difficulty: "easy",
    type: "formula",
    tags: ["odd-even", "negative angles"],
  },
  {
    id: "qmath-m3-021",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Double Angle Formula",
    question: "sin 2θ =",
    options: [
      "2 sin θ cos θ",
      "sin²θ − cos²θ",
      "2 sin²θ",
      "2 cos²θ",
    ],
    correctAnswer: "2 sin θ cos θ",
    explanation:
      "Double angle identity: sin 2θ = 2 sin θ cos θ.",
    difficulty: "medium",
    type: "formula",
    tags: ["double angle", "identities"],
  },
  {
    id: "qmath-m3-022",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Double Angle Formula",
    question: "cos 2θ =",
    options: [
      "cos²θ − sin²θ",
      "2 sin θ cos θ",
      "sin²θ + cos²θ",
      "2 cos²θ",
    ],
    correctAnswer: "cos²θ − sin²θ",
    explanation:
      "Double angle identity: cos 2θ = cos²θ − sin²θ = 2cos²θ − 1 = 1 − 2sin²θ.",
    difficulty: "medium",
    type: "formula",
    tags: ["double angle", "identities"],
  },
  {
    id: "qmath-m3-023",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Sum Formulas",
    question: "sin(A + B) =",
    options: [
      "sin A cos B + cos A sin B",
      "sin A cos B − cos A sin B",
      "cos A cos B − sin A sin B",
      "cos A cos B + sin A sin B",
    ],
    correctAnswer: "sin A cos B + cos A sin B",
    explanation:
      "Compound angle identity: sin(A + B) = sin A cos B + cos A sin B.",
    difficulty: "medium",
    type: "formula",
    tags: ["sum formulas", "compound angles"],
  },
  {
    id: "qmath-m3-024",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Sum Formulas",
    question: "cos(A + B) =",
    options: [
      "cos A cos B − sin A sin B",
      "cos A cos B + sin A sin B",
      "sin A cos B + cos A sin B",
      "sin A cos B − cos A sin B",
    ],
    correctAnswer: "cos A cos B − sin A sin B",
    explanation:
      "Compound angle identity: cos(A + B) = cos A cos B − sin A sin B.",
    difficulty: "medium",
    type: "formula",
    tags: ["sum formulas", "compound angles"],
  },
  {
    id: "qmath-m3-025",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Signs in Quadrants",
    question: "In which quadrant is sin positive and cos negative?",
    options: ["II", "I", "III", "IV"],
    correctAnswer: "II",
    explanation:
      "Quadrant II: sin positive, cos negative (use 'ASTC' — All, Sin, Tan, Cos).",
    difficulty: "medium",
    type: "concept",
    tags: ["quadrants", "signs of trig functions", "ASTC"],
  },
  {
    id: "qmath-m3-026",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Signs in Quadrants",
    question: "In which quadrant are all trigonometric functions positive?",
    options: ["I", "II", "III", "IV"],
    correctAnswer: "I",
    explanation:
      "In Quadrant I, all trigonometric ratios (sin, cos, tan, etc.) are positive ('A' in ASTC).",
    difficulty: "easy",
    type: "concept",
    tags: ["quadrants", "signs of trig functions", "ASTC"],
  },
  {
    id: "qmath-m3-027",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Signs in Quadrants",
    question: "In which quadrant is tan positive but sin negative?",
    options: ["III", "I", "II", "IV"],
    correctAnswer: "III",
    explanation:
      "Quadrant III: tan positive, sin and cos both negative ('T' in ASTC).",
    difficulty: "medium",
    type: "concept",
    tags: ["quadrants", "signs of trig functions", "ASTC"],
  },
  {
    id: "qmath-m3-028",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Trigonometric Ratios",
    question: "The value of sin 45° is:",
    options: ["√2/2", "1/2", "√3/2", "1"],
    correctAnswer: "√2/2",
    explanation: "sin 45° = 1/√2 = √2/2.",
    difficulty: "easy",
    type: "formula",
    tags: ["trigonometric ratios", "standard angles"],
  },
  {
    id: "qmath-m3-029",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Trigonometric Ratios",
    question: "The value of cos 30° is:",
    options: ["√3/2", "1/2", "√2/2", "1"],
    correctAnswer: "√3/2",
    explanation: "cos 30° = √3/2.",
    difficulty: "easy",
    type: "formula",
    tags: ["trigonometric ratios", "standard angles"],
  },
  {
    id: "qmath-m3-030",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Trigonometric Ratios",
    question: "The value of tan 60° is:",
    options: ["√3", "1/√3", "1", "√2"],
    correctAnswer: "√3",
    explanation: "tan 60° = sin 60°/cos 60° = (√3/2)/(1/2) = √3.",
    difficulty: "easy",
    type: "formula",
    tags: ["trigonometric ratios", "standard angles"],
  },
  {
    id: "qmath-m3-031",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Trigonometric Ratios",
    question: "cos 0° =",
    options: ["0", "1", "√3/2", "1/2"],
    correctAnswer: "1",
    explanation: "cos 0° = 1 (maximum value of cosine).",
    difficulty: "easy",
    type: "formula",
    tags: ["trigonometric ratios", "standard angles"],
  },
  {
    id: "qmath-m3-032",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Range",
    question: "The maximum value of sin θ is:",
    options: ["1", "0", "-1", "2"],
    correctAnswer: "1",
    explanation:
      "sin θ lies in [−1, 1]; its maximum value is 1 (at θ = 90°).",
    difficulty: "easy",
    type: "concept",
    tags: ["range", "sine"],
  },
  {
    id: "qmath-m3-033",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Range",
    question: "The minimum value of cos θ is:",
    options: ["-1", "0", "1", "2"],
    correctAnswer: "-1",
    explanation:
      "cos θ lies in [−1, 1]; its minimum value is -1 (at θ = 180°).",
    difficulty: "easy",
    type: "concept",
    tags: ["range", "cosine"],
  },
  {
    id: "qmath-m3-034",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Periodicity",
    question: "The period of sin x is:",
    options: ["2π", "π", "π/2", "4π"],
    correctAnswer: "2π",
    explanation:
      "sin(x + 2π) = sin x, so the period of sin x is 2π.",
    difficulty: "medium",
    type: "formula",
    tags: ["periodicity", "sine"],
  },
  {
    id: "qmath-m3-035",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Periodicity",
    question: "The period of tan x is:",
    options: ["π", "2π", "π/2", "4π"],
    correctAnswer: "π",
    explanation:
      "tan(x + π) = tan x, so the period of tan x is π (half that of sin/cos).",
    difficulty: "medium",
    type: "formula",
    tags: ["periodicity", "tangent"],
  },
  {
    id: "qmath-m3-036",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Trigonometric Ratios",
    question: "sin 0° =",
    options: ["0", "1", "1/2", "-1"],
    correctAnswer: "0",
    explanation: "sin 0° = 0.",
    difficulty: "easy",
    type: "formula",
    tags: ["trigonometric ratios", "standard angles"],
  },
  {
    id: "qmath-m3-037",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Simple Equations",
    question: "If sin θ = 1/2 and θ is acute, then θ =",
    options: ["30°", "60°", "45°", "90°"],
    correctAnswer: "30°",
    explanation: "sin 30° = 1/2, so the acute angle θ = 30°.",
    difficulty: "easy",
    type: "numerical",
    tags: ["simple equations", "sine"],
  },
  {
    id: "qmath-m3-038",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Identities",
    question: "The value of sin²45° + cos²45° is:",
    options: ["1", "0", "1/2", "2"],
    correctAnswer: "1",
    explanation:
      "By the Pythagorean identity, sin²θ + cos²θ = 1 for any θ, including 45°.",
    difficulty: "easy",
    type: "numerical",
    tags: ["identities", "Pythagorean identity"],
  },
  {
    id: "qmath-m3-039",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Double Angle Application",
    question: "The value of 2 sin 30° cos 30° is:",
    options: ["√3/2", "1/2", "√3", "1"],
    correctAnswer: "√3/2",
    explanation:
      "2 sin 30° cos 30° = sin 60° = √3/2 (by the double-angle identity).",
    difficulty: "medium",
    type: "numerical",
    tags: ["double angle", "identities"],
  },
  {
    id: "qmath-m3-040",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m3",
    chapter: "Trigonometric Functions",
    topic: "Reciprocal Identities",
    question: "tan θ × cot θ =",
    options: ["1", "sin²θ", "cos²θ", "tan²θ"],
    correctAnswer: "1",
    explanation:
      "tan θ × cot θ = (sin θ/cos θ) × (cos θ/sin θ) = 1.",
    difficulty: "easy",
    type: "formula",
    tags: ["reciprocal identities"],
  },

  // ==================== LIMITS AND DERIVATIVES (m13) — 35 questions ====================
  {
    id: "qmath-m13-001",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Limits",
    question: "lim(x→0) (sin x)/x =",
    options: ["0", "1", "∞", "undefined"],
    correctAnswer: "1",
    explanation:
      "This is a fundamental standard limit: lim(x→0) (sin x)/x = 1.",
    difficulty: "easy",
    type: "formula",
    tags: ["standard limits", "sine"],
  },
  {
    id: "qmath-m13-002",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Limits",
    question: "lim(x→0) (1 − cos x)/x =",
    options: ["0", "1", "∞", "1/2"],
    correctAnswer: "0",
    explanation:
      "Using 1 − cos x = 2 sin²(x/2), the limit becomes 2·(x/2)²·(1/x) → 0 as x → 0.",
    difficulty: "hard",
    type: "numerical",
    tags: ["standard limits", "cosine"],
  },
  {
    id: "qmath-m13-003",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Limits",
    question: "lim(x→0) (tan x)/x =",
    options: ["0", "1", "∞", "1/2"],
    correctAnswer: "1",
    explanation:
      "lim(x→0) (tan x)/x = lim (sin x)/(x cos x) = 1 × 1 = 1.",
    difficulty: "medium",
    type: "formula",
    tags: ["standard limits", "tangent"],
  },
  {
    id: "qmath-m13-004",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Limits",
    question: "lim(x→0) (1 + x)^(1/x) =",
    options: ["1", "0", "e", "∞"],
    correctAnswer: "e",
    explanation:
      "This is a standard limit defining e ≈ 2.718: lim(x→0) (1 + x)^(1/x) = e.",
    difficulty: "medium",
    type: "formula",
    tags: ["standard limits", "euler's number"],
  },
  {
    id: "qmath-m13-005",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Derivatives",
    question: "d/dx (xⁿ) =",
    options: [
      "nx^(n−1)",
      "x^(n−1)",
      "nxⁿ",
      "n x^(n+1)",
    ],
    correctAnswer: "nx^(n−1)",
    explanation:
      "Power rule: d/dx (xⁿ) = n·x^(n−1).",
    difficulty: "easy",
    type: "formula",
    tags: ["derivatives", "power rule"],
  },
  {
    id: "qmath-m13-006",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Derivatives",
    question: "d/dx (sin x) =",
    options: ["cos x", "-cos x", "-sin x", "sin x"],
    correctAnswer: "cos x",
    explanation: "The derivative of sin x is cos x.",
    difficulty: "easy",
    type: "formula",
    tags: ["derivatives", "sine"],
  },
  {
    id: "qmath-m13-007",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Derivatives",
    question: "d/dx (cos x) =",
    options: ["-sin x", "sin x", "cos x", "-cos x"],
    correctAnswer: "-sin x",
    explanation: "The derivative of cos x is -sin x.",
    difficulty: "easy",
    type: "formula",
    tags: ["derivatives", "cosine"],
  },
  {
    id: "qmath-m13-008",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Derivatives",
    question: "d/dx (tan x) =",
    options: ["sec²x", "-sec²x", "cosec²x", "tan²x"],
    correctAnswer: "sec²x",
    explanation: "The derivative of tan x is sec²x.",
    difficulty: "medium",
    type: "formula",
    tags: ["derivatives", "tangent"],
  },
  {
    id: "qmath-m13-009",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Derivatives",
    question: "d/dx (constant) =",
    options: ["0", "1", "constant", "undefined"],
    correctAnswer: "0",
    explanation:
      "The derivative of any constant is 0, since constants don't change.",
    difficulty: "easy",
    type: "formula",
    tags: ["derivatives", "constant"],
  },
  {
    id: "qmath-m13-010",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Derivatives",
    question: "d/dx (eˣ) =",
    options: ["eˣ", "1", "xeˣ", "ln x"],
    correctAnswer: "eˣ",
    explanation:
      "The derivative of eˣ is eˣ itself (a unique property of the exponential function).",
    difficulty: "easy",
    type: "formula",
    tags: ["derivatives", "exponential"],
  },
  {
    id: "qmath-m13-011",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Derivatives",
    question: "d/dx (ln x) =",
    options: ["1/x", "x", "ln x", "1"],
    correctAnswer: "1/x",
    explanation:
      "The derivative of ln x (natural log) is 1/x, for x > 0.",
    difficulty: "medium",
    type: "formula",
    tags: ["derivatives", "logarithm"],
  },
  {
    id: "qmath-m13-012",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Interpretation of Derivative",
    question: "The derivative is also called the:",
    options: [
      "instantaneous rate of change",
      "average rate",
      "slope of chord",
      "integral",
    ],
    correctAnswer: "instantaneous rate of change",
    explanation:
      "The derivative f′(x) gives the instantaneous rate of change of f at x.",
    difficulty: "medium",
    type: "concept",
    tags: ["derivative", "rate of change"],
  },
  {
    id: "qmath-m13-013",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Geometric Interpretation",
    question: "The derivative at a point gives the slope of the:",
    options: ["tangent", "chord", "secant", "normal"],
    correctAnswer: "tangent",
    explanation:
      "The derivative f′(a) equals the slope of the tangent line to the curve y = f(x) at x = a.",
    difficulty: "medium",
    type: "concept",
    tags: ["tangent", "slope", "geometric interpretation"],
  },
  {
    id: "qmath-m13-014",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Limits by Factorisation",
    question: "lim(x→1) (x² − 1)/(x − 1) =",
    options: ["2", "0", "1", "undefined"],
    correctAnswer: "2",
    explanation:
      "Factorise: (x²−1)/(x−1) = (x+1), so lim(x→1) (x+1) = 2.",
    difficulty: "medium",
    type: "numerical",
    tags: ["limits", "factorisation"],
  },
  {
    id: "qmath-m13-015",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Limits by Factorisation",
    question: "lim(x→2) (x² − 4)/(x − 2) =",
    options: ["4", "2", "0", "8"],
    correctAnswer: "4",
    explanation:
      "Factorise: (x²−4)/(x−2) = (x+2), so lim(x→2) (x+2) = 4.",
    difficulty: "medium",
    type: "numerical",
    tags: ["limits", "factorisation"],
  },
  {
    id: "qmath-m13-016",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Derivatives",
    question: "d/dx (5) =",
    options: ["0", "5", "1", "25"],
    correctAnswer: "0",
    explanation:
      "5 is a constant, and the derivative of a constant is 0.",
    difficulty: "easy",
    type: "numerical",
    tags: ["derivatives", "constant"],
  },
  {
    id: "qmath-m13-017",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Sum Rule",
    question: "d/dx (3x + 2) =",
    options: ["3", "2", "3x", "5"],
    correctAnswer: "3",
    explanation:
      "By the sum rule: d/dx (3x) + d/dx (2) = 3 + 0 = 3.",
    difficulty: "easy",
    type: "numerical",
    tags: ["derivatives", "sum rule"],
  },
  {
    id: "qmath-m13-018",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Power Rule",
    question: "d/dx (x²) =",
    options: ["2x", "x", "2", "x²"],
    correctAnswer: "2x",
    explanation: "Power rule: d/dx (x²) = 2x.",
    difficulty: "easy",
    type: "numerical",
    tags: ["derivatives", "power rule"],
  },
  {
    id: "qmath-m13-019",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Power Rule",
    question: "d/dx (√x) =",
    options: ["1/(2√x)", "2√x", "1/√x", "√x/2"],
    correctAnswer: "1/(2√x)",
    explanation:
      "√x = x^(1/2); derivative = (1/2)x^(−1/2) = 1/(2√x).",
    difficulty: "medium",
    type: "formula",
    tags: ["derivatives", "power rule", "square root"],
  },
  {
    id: "qmath-m13-020",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Limits",
    question: "lim(x→0) (sin 2x)/x =",
    options: ["2", "1", "0", "1/2"],
    correctAnswer: "2",
    explanation:
      "lim (sin 2x)/x = 2·lim (sin 2x)/(2x) = 2 × 1 = 2.",
    difficulty: "medium",
    type: "numerical",
    tags: ["standard limits", "sine"],
  },
  {
    id: "qmath-m13-021",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "First Principle",
    question: "The first principle of derivatives is given by:",
    options: [
      "lim(h→0) [f(x+h) − f(x)]/h",
      "lim f(x)",
      "f(x+h)",
      "f(x)/h",
    ],
    correctAnswer: "lim(h→0) [f(x+h) − f(x)]/h",
    explanation:
      "By definition (first principle / ab initio), f′(x) = lim(h→0) [f(x+h) − f(x)]/h.",
    difficulty: "medium",
    type: "formula",
    tags: ["first principle", "definition of derivative"],
  },
  {
    id: "qmath-m13-022",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Derivatives",
    question: "d/dx (cot x) =",
    options: ["-cosec²x", "cosec²x", "-sec²x", "sec²x"],
    correctAnswer: "-cosec²x",
    explanation: "The derivative of cot x is -cosec²x.",
    difficulty: "hard",
    type: "formula",
    tags: ["derivatives", "cotangent"],
  },
  {
    id: "qmath-m13-023",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Derivatives",
    question: "d/dx (sec x) =",
    options: ["sec x tan x", "-sec x tan x", "sec²x", "tan²x"],
    correctAnswer: "sec x tan x",
    explanation: "The derivative of sec x is sec x · tan x.",
    difficulty: "hard",
    type: "formula",
    tags: ["derivatives", "secant"],
  },
  {
    id: "qmath-m13-024",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Derivatives",
    question: "d/dx (cosec x) =",
    options: [
      "-cosec x cot x",
      "cosec x cot x",
      "-sec x tan x",
      "sec x tan x",
    ],
    correctAnswer: "-cosec x cot x",
    explanation: "The derivative of cosec x is -cosec x · cot x.",
    difficulty: "hard",
    type: "formula",
    tags: ["derivatives", "cosecant"],
  },
  {
    id: "qmath-m13-025",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Limits by Factorisation",
    question: "lim(x→3) (x² − 9)/(x − 3) =",
    options: ["6", "3", "9", "0"],
    correctAnswer: "6",
    explanation:
      "Factorise: (x²−9)/(x−3) = (x+3), so lim(x→3) (x+3) = 6.",
    difficulty: "medium",
    type: "numerical",
    tags: ["limits", "factorisation"],
  },
  {
    id: "qmath-m13-026",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Slope of Tangent",
    question: "The slope of the line y = 2x + 3 is:",
    options: ["2", "3", "5", "1"],
    correctAnswer: "2",
    explanation:
      "For y = mx + c, m is the slope. Here m = 2.",
    difficulty: "easy",
    type: "numerical",
    tags: ["slope", "tangent"],
  },
  {
    id: "qmath-m13-027",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Sum Rule",
    question: "d/dx (x³ + x²) =",
    options: ["3x² + 2x", "3x² + x", "x² + 2x", "3x + 2"],
    correctAnswer: "3x² + 2x",
    explanation:
      "Apply power rule term-wise: d/dx (x³) + d/dx (x²) = 3x² + 2x.",
    difficulty: "easy",
    type: "numerical",
    tags: ["derivatives", "sum rule", "power rule"],
  },
  {
    id: "qmath-m13-028",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Limits",
    question: "lim(x→0) (eˣ − 1)/x =",
    options: ["1", "0", "e", "∞"],
    correctAnswer: "1",
    explanation:
      "This is a standard limit: lim(x→0) (eˣ − 1)/x = 1.",
    difficulty: "medium",
    type: "formula",
    tags: ["standard limits", "exponential"],
  },
  {
    id: "qmath-m13-029",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Power Rule",
    question: "d/dx (1/x) =",
    options: ["-1/x²", "1/x²", "-1/x", "1/x"],
    correctAnswer: "-1/x²",
    explanation:
      "1/x = x^(−1); derivative = -1·x^(−2) = -1/x².",
    difficulty: "medium",
    type: "formula",
    tags: ["derivatives", "power rule", "reciprocal"],
  },
  {
    id: "qmath-m13-030",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Sum Rule",
    question: "d/dx [f(x) + g(x)] =",
    options: [
      "f′(x) + g′(x)",
      "f′(x) × g′(x)",
      "f′(x) − g′(x)",
      "f(x)g′(x) + g(x)f′(x)",
    ],
    correctAnswer: "f′(x) + g′(x)",
    explanation:
      "Sum rule: the derivative of a sum is the sum of derivatives.",
    difficulty: "easy",
    type: "formula",
    tags: ["sum rule", "rules of differentiation"],
  },
  {
    id: "qmath-m13-031",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Product Rule",
    question: "The product rule: d/dx [f(x)g(x)] =",
    options: [
      "f′(x)g(x) + f(x)g′(x)",
      "f(x)g(x)",
      "f′(x)g(x) − f(x)g′(x)",
      "f′(x) + g′(x)",
    ],
    correctAnswer: "f′(x)g(x) + f(x)g′(x)",
    explanation:
      "Product rule: (fg)′ = f′g + fg′.",
    difficulty: "medium",
    type: "formula",
    tags: ["product rule", "rules of differentiation"],
  },
  {
    id: "qmath-m13-032",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Evaluating Derivatives",
    question:
      "If y = sin x + cos x, then dy/dx at x = 0 is:",
    options: ["1", "0", "2", "-1"],
    correctAnswer: "1",
    explanation:
      "dy/dx = cos x − sin x. At x = 0: cos 0 − sin 0 = 1 − 0 = 1.",
    difficulty: "medium",
    type: "numerical",
    tags: ["derivatives", "evaluation"],
  },
  {
    id: "qmath-m13-033",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Standard Limits",
    question: "lim(x→0) (1 + x/2)^(2/x) equals:",
    options: ["e", "e²", "1", "1/2"],
    correctAnswer: "e",
    explanation:
      "Let y = x/2. Then (1 + y)^(1/y) → e as y → 0 (since 2/x = 1/y).",
    difficulty: "hard",
    type: "numerical",
    tags: ["standard limits", "euler's number"],
  },
  {
    id: "qmath-m13-034",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Product Rule",
    question: "d/dx (x sin x) =",
    options: [
      "sin x + x cos x",
      "sin x − x cos x",
      "cos x + x sin x",
      "x cos x",
    ],
    correctAnswer: "sin x + x cos x",
    explanation:
      "By product rule: d/dx(x)·sin x + x·d/dx(sin x) = 1·sin x + x cos x = sin x + x cos x.",
    difficulty: "hard",
    type: "numerical",
    tags: ["product rule", "derivatives"],
  },
  {
    id: "qmath-m13-035",
    subject: "maths",
    subjectName: "Mathematics",
    chapterId: "m13",
    chapter: "Limits and Derivatives",
    topic: "Application of Derivatives",
    question: "The derivative of position with respect to time gives:",
    options: ["velocity", "acceleration", "displacement", "distance"],
    correctAnswer: "velocity",
    explanation:
      "Velocity is the time derivative of position: v = dx/dt. Acceleration is the derivative of velocity.",
    difficulty: "medium",
    type: "concept",
    tags: ["application", "velocity", "rate of change"],
  },
];
