export interface QuizMCQ {
  id: string;
  subject: "physics" | "chemistry" | "maths" | "cs";
  subjectName: string;
  chapterId: string;
  chapter: string;
  topic: string;
  question: string;
  options: string[]; // exactly 4 options
  correctAnswer: string; // must match one of the options exactly
  explanation: string;
  difficulty: "easy" | "medium" | "hard";
  type: "concept" | "numerical" | "formula" | "output" | "true-false";
  tags: string[];
}

export const PHYSICS_QUIZZES: QuizMCQ[] = [
  // ==================== UNITS AND MEASUREMENTS (p2) — 60 questions ====================
  {
    id: "qphy-p2-001",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "SI Base Units",
    question: "How many base units are there in the SI system?",
    options: ["5", "6", "7", "8"],
    correctAnswer: "7",
    explanation:
      "The SI system has seven base units: metre, kilogram, second, ampere, kelvin, mole, and candela.",
    difficulty: "easy",
    type: "concept",
    tags: ["SI units", "base units", "fundamental quantities"],
  },
  {
    id: "qphy-p2-002",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "SI Base Units",
    question: "The SI unit of luminous intensity is:",
    options: ["lux", "candela", "lumen", "watt"],
    correctAnswer: "candela",
    explanation: "Luminous intensity is measured in candela (cd), one of the seven SI base units.",
    difficulty: "easy",
    type: "concept",
    tags: ["SI units", "luminous intensity", "candela"],
  },
  {
    id: "qphy-p2-003",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Fundamental Quantities",
    question: "Which of the following is a fundamental quantity?",
    options: ["Force", "Velocity", "Mass", "Density"],
    correctAnswer: "Mass",
    explanation:
      "Mass is a fundamental quantity (SI base unit: kilogram). Force, velocity and density are derived quantities.",
    difficulty: "easy",
    type: "concept",
    tags: ["fundamental quantities", "derived quantities"],
  },
  {
    id: "qphy-p2-004",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimensional formula of force is:",
    options: ["[MLT⁻¹]", "[MLT⁻²]", "[ML²T⁻²]", "[M⁻¹LT⁻²]"],
    correctAnswer: "[MLT⁻²]",
    explanation:
      "Force = mass × acceleration = M × LT⁻² = [MLT⁻²].",
    difficulty: "medium",
    type: "formula",
    tags: ["dimensional formula", "force"],
  },
  {
    id: "qphy-p2-005",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "SI Base Units",
    question: "The SI unit of amount of substance is:",
    options: ["gram", "mole", "litre", "kilogram"],
    correctAnswer: "mole",
    explanation: "Amount of substance is measured in mole (mol), one of the seven SI base units.",
    difficulty: "easy",
    type: "concept",
    tags: ["SI units", "mole", "amount of substance"],
  },
  {
    id: "qphy-p2-006",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Units of Length",
    question: "Light year is a unit of:",
    options: ["time", "speed", "distance", "intensity"],
    correctAnswer: "distance",
    explanation:
      "A light year is the distance travelled by light in one year, approximately 9.46 × 10¹⁵ m.",
    difficulty: "easy",
    type: "concept",
    tags: ["light year", "astronomical units", "distance"],
  },
  {
    id: "qphy-p2-007",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensionless Quantities",
    question: "Which of the following is a dimensionless quantity?",
    options: ["Strain", "Stress", "Pressure", "Force"],
    correctAnswer: "Strain",
    explanation:
      "Strain = ΔL/L, ratio of two lengths, so it is dimensionless [M⁰L⁰T⁰].",
    difficulty: "medium",
    type: "concept",
    tags: ["dimensionless", "strain"],
  },
  {
    id: "qphy-p2-008",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Units of Length",
    question: "Parsec is a unit of:",
    options: ["time", "distance", "velocity", "angle"],
    correctAnswer: "distance",
    explanation:
      "A parsec is an astronomical unit of distance, approximately 3.08 × 10¹⁶ m.",
    difficulty: "easy",
    type: "concept",
    tags: ["parsec", "astronomical units", "distance"],
  },
  {
    id: "qphy-p2-009",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimensional formula of work is:",
    options: ["[ML²T⁻²]", "[MLT⁻²]", "[ML²T⁻¹]", "[ML⁻¹T⁻²]"],
    correctAnswer: "[ML²T⁻²]",
    explanation: "Work = force × distance = [MLT⁻²][L] = [ML²T⁻²].",
    difficulty: "medium",
    type: "formula",
    tags: ["dimensional formula", "work", "energy"],
  },
  {
    id: "qphy-p2-010",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Significant Figures",
    question: "The number of significant figures in 0.00400 is:",
    options: ["3", "5", "2", "6"],
    correctAnswer: "3",
    explanation:
      "Leading zeros are not significant; trailing zeros after the decimal point are. So 0.00400 has 3 significant figures (4, 0, 0).",
    difficulty: "medium",
    type: "numerical",
    tags: ["significant figures"],
  },
  {
    id: "qphy-p2-011",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Units of Length",
    question: "Which unit is convenient for measuring nuclear sizes?",
    options: ["angstrom", "fermi", "micron", "nanometre"],
    correctAnswer: "fermi",
    explanation:
      "Nuclear sizes (~10⁻¹⁵ m) are measured in fermi (1 fermi = 10⁻¹⁵ m).",
    difficulty: "easy",
    type: "concept",
    tags: ["fermi", "nuclear sizes", "units of length"],
  },
  {
    id: "qphy-p2-012",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimensional formula of pressure is:",
    options: ["[ML⁻¹T⁻²]", "[MLT⁻²]", "[ML²T⁻²]", "[ML⁻¹T⁻¹]"],
    correctAnswer: "[ML⁻¹T⁻²]",
    explanation: "Pressure = force/area = [MLT⁻²]/[L²] = [ML⁻¹T⁻²].",
    difficulty: "medium",
    type: "formula",
    tags: ["dimensional formula", "pressure"],
  },
  {
    id: "qphy-p2-013",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "Which of the following pairs has the same dimensions?",
    options: ["Force and Energy", "Work and Torque", "Power and Momentum", "Pressure and Force"],
    correctAnswer: "Work and Torque",
    explanation:
      "Both work (force × distance) and torque (force × perpendicular distance) have dimensions [ML²T⁻²].",
    difficulty: "medium",
    type: "concept",
    tags: ["dimensional analysis", "work", "torque"],
  },
  {
    id: "qphy-p2-014",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Units of Length",
    question: "1 fermi is equal to:",
    options: ["10⁻¹⁰ m", "10⁻¹³ m", "10⁻¹⁵ m", "10⁻⁶ m"],
    correctAnswer: "10⁻¹⁵ m",
    explanation: "1 fermi (femtometre) = 10⁻¹⁵ m, used to measure nuclear distances.",
    difficulty: "easy",
    type: "formula",
    tags: ["fermi", "unit conversion"],
  },
  {
    id: "qphy-p2-015",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Units of Length",
    question: "1 angstrom is equal to:",
    options: ["10⁻⁸ m", "10⁻¹⁰ m", "10⁻¹² m", "10⁻⁶ m"],
    correctAnswer: "10⁻¹⁰ m",
    explanation: "1 angstrom (Å) = 10⁻¹⁰ m, used to measure atomic sizes.",
    difficulty: "easy",
    type: "formula",
    tags: ["angstrom", "unit conversion"],
  },
  {
    id: "qphy-p2-016",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Units of Length",
    question: "1 light year is approximately equal to:",
    options: ["9.46 × 10¹¹ m", "9.46 × 10¹⁵ m", "3 × 10⁸ m", "1.5 × 10¹¹ m"],
    correctAnswer: "9.46 × 10¹⁵ m",
    explanation:
      "1 light year = speed of light × 1 year = 3 × 10⁸ × 365.25 × 86400 ≈ 9.46 × 10¹⁵ m.",
    difficulty: "medium",
    type: "formula",
    tags: ["light year", "astronomical units"],
  },
  {
    id: "qphy-p2-017",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimensional formula of power is:",
    options: ["[ML²T⁻³]", "[ML²T⁻²]", "[MLT⁻³]", "[ML⁻¹T⁻²]"],
    correctAnswer: "[ML²T⁻³]",
    explanation: "Power = work/time = [ML²T⁻²]/[T] = [ML²T⁻³].",
    difficulty: "medium",
    type: "formula",
    tags: ["dimensional formula", "power"],
  },
  {
    id: "qphy-p2-018",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimensional formula of impulse is:",
    options: ["[MLT⁻¹]", "[MLT⁻²]", "[ML²T⁻¹]", "[ML⁻¹T⁻¹]"],
    correctAnswer: "[MLT⁻¹]",
    explanation: "Impulse = force × time = [MLT⁻²][T] = [MLT⁻¹], same as momentum.",
    difficulty: "medium",
    type: "formula",
    tags: ["dimensional formula", "impulse"],
  },
  {
    id: "qphy-p2-019",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Fundamental vs Derived Units",
    question: "Which of the following is NOT a fundamental unit?",
    options: ["kilogram", "second", "newton", "mole"],
    correctAnswer: "newton",
    explanation:
      "Newton is a derived unit (kg·m/s²) of force. Kilogram, second and mole are SI base units.",
    difficulty: "easy",
    type: "concept",
    tags: ["fundamental units", "derived units", "newton"],
  },
  {
    id: "qphy-p2-020",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensionless Quantities",
    question: "Which physical quantity has a unit but no dimensions?",
    options: ["Solid angle", "Velocity", "Force", "Energy"],
    correctAnswer: "Solid angle",
    explanation:
      "Solid angle is measured in steradian but is dimensionless [M⁰L⁰T⁰]. Plane angle (radian) is another such quantity.",
    difficulty: "hard",
    type: "concept",
    tags: ["dimensionless", "solid angle", "supplementary units"],
  },
  {
    id: "qphy-p2-021",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Significant Figures",
    question: "The number of significant figures in 0.0500 is:",
    options: ["2", "3", "4", "5"],
    correctAnswer: "3",
    explanation:
      "Leading zeros are not significant; the trailing zeros after the decimal are. So 0.0500 has 3 significant figures.",
    difficulty: "medium",
    type: "numerical",
    tags: ["significant figures"],
  },
  {
    id: "qphy-p2-022",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Units of Length",
    question: "1 parsec is approximately equal to:",
    options: ["3.08 × 10¹⁶ m", "9.46 × 10¹⁵ m", "1.5 × 10¹¹ m", "3 × 10⁸ m"],
    correctAnswer: "3.08 × 10¹⁶ m",
    explanation:
      "1 parsec is the distance at which 1 AU subtends an angle of 1 arcsecond, ≈ 3.08 × 10¹⁶ m.",
    difficulty: "medium",
    type: "formula",
    tags: ["parsec", "astronomical units"],
  },
  {
    id: "qphy-p2-023",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Errors",
    question: "If the error in measuring the radius of a sphere is 1%, the error in its volume is:",
    options: ["1%", "2%", "3%", "4%"],
    correctAnswer: "3%",
    explanation:
      "Volume V ∝ r³, so % error in V = 3 × % error in r = 3 × 1% = 3%.",
    difficulty: "hard",
    type: "numerical",
    tags: ["errors", "percentage error", "error propagation"],
  },
  {
    id: "qphy-p2-024",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Errors",
    question:
      "A length is measured as 2.50 m while the true value is 2.45 m. The absolute error is:",
    options: ["0.05 m", "0.5 m", "0.025 m", "0.005 m"],
    correctAnswer: "0.05 m",
    explanation: "Absolute error = |measured − true| = |2.50 − 2.45| = 0.05 m.",
    difficulty: "medium",
    type: "numerical",
    tags: ["errors", "absolute error"],
  },
  {
    id: "qphy-p2-025",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Significant Figures",
    question: "The number of significant figures in 0.007 is:",
    options: ["1", "2", "3", "4"],
    correctAnswer: "1",
    explanation:
      "Leading zeros are not significant. Only the 7 is significant, so 0.007 has 1 significant figure.",
    difficulty: "medium",
    type: "numerical",
    tags: ["significant figures"],
  },
  {
    id: "qphy-p2-026",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimensional formula of coefficient of viscosity is:",
    options: ["[ML⁻¹T⁻¹]", "[ML⁻¹T⁻²]", "[MLT⁻¹]", "[ML²T⁻¹]"],
    correctAnswer: "[ML⁻¹T⁻¹]",
    explanation:
      "From η = F/(A·dv/dx), we get [ML⁻¹T⁻¹].",
    difficulty: "hard",
    type: "formula",
    tags: ["dimensional formula", "viscosity"],
  },
  {
    id: "qphy-p2-027",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimensional formula of surface tension is:",
    options: ["[MT⁻²]", "[ML⁻¹T⁻²]", "[MLT⁻²]", "[MT⁻¹]"],
    correctAnswer: "[MT⁻²]",
    explanation: "Surface tension = force/length = [MLT⁻²]/[L] = [MT⁻²].",
    difficulty: "medium",
    type: "formula",
    tags: ["dimensional formula", "surface tension"],
  },
  {
    id: "qphy-p2-028",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimensional formula of Planck's constant is:",
    options: ["[ML²T⁻¹]", "[MLT⁻¹]", "[ML²T⁻²]", "[ML²T⁻³]"],
    correctAnswer: "[ML²T⁻¹]",
    explanation:
      "From E = hν, h = E/ν = [ML²T⁻²]/[T⁻¹] = [ML²T⁻¹].",
    difficulty: "hard",
    type: "formula",
    tags: ["dimensional formula", "Planck's constant"],
  },
  {
    id: "qphy-p2-029",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Units of Length",
    question: "1 micron is equal to:",
    options: ["10⁻⁶ m", "10⁻⁹ m", "10⁻³ m", "10⁻⁴ m"],
    correctAnswer: "10⁻⁶ m",
    explanation: "1 micron (micrometre, μm) = 10⁻⁶ m.",
    difficulty: "easy",
    type: "formula",
    tags: ["micron", "unit conversion"],
  },
  {
    id: "qphy-p2-030",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Vernier Calipers",
    question:
      "In a vernier calipers, 9 main scale divisions coincide with 10 vernier divisions. If 1 MSD = 1 mm, the least count is:",
    options: ["0.1 mm", "0.01 mm", "0.2 mm", "0.05 mm"],
    correctAnswer: "0.1 mm",
    explanation:
      "Least count = 1 MSD − 1 VSD = 1 mm − (9/10) mm = 0.1 mm.",
    difficulty: "medium",
    type: "numerical",
    tags: ["vernier calipers", "least count"],
  },
  {
    id: "qphy-p2-031",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Screw Gauge",
    question:
      "A screw gauge has a pitch of 1 mm and 100 divisions on the circular scale. Its least count is:",
    options: ["0.1 mm", "0.01 mm", "0.001 mm", "0.05 mm"],
    correctAnswer: "0.01 mm",
    explanation: "Least count = pitch/no. of divisions = 1 mm/100 = 0.01 mm.",
    difficulty: "medium",
    type: "numerical",
    tags: ["screw gauge", "least count"],
  },
  {
    id: "qphy-p2-032",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Significant Figures",
    question: "The number of significant figures in 4.0 × 10⁴ is:",
    options: ["1", "2", "3", "5"],
    correctAnswer: "2",
    explanation:
      "In scientific notation, all digits in the coefficient count. 4.0 has 2 significant figures.",
    difficulty: "medium",
    type: "numerical",
    tags: ["significant figures", "scientific notation"],
  },
  {
    id: "qphy-p2-033",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimensional formula of the gravitational constant G is:",
    options: ["[M⁻¹L³T⁻²]", "[M⁻¹L²T⁻²]", "[ML³T⁻²]", "[M⁻¹L³T⁻¹]"],
    correctAnswer: "[M⁻¹L³T⁻²]",
    explanation:
      "From F = Gm₁m₂/r², G = Fr²/(m₁m₂) = [MLT⁻²][L²]/[M²] = [M⁻¹L³T⁻²].",
    difficulty: "hard",
    type: "formula",
    tags: ["dimensional formula", "gravitational constant"],
  },
  {
    id: "qphy-p2-034",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Supplementary Units",
    question: "The SI unit of solid angle is:",
    options: ["radian", "degree", "steradian", "candela"],
    correctAnswer: "steradian",
    explanation: "Solid angle is measured in steradian (sr), a supplementary SI unit.",
    difficulty: "easy",
    type: "concept",
    tags: ["SI units", "solid angle", "steradian"],
  },
  {
    id: "qphy-p2-035",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Errors",
    question: "Random errors can be reduced by:",
    options: [
      "taking a single observation",
      "taking many observations and averaging",
      "using better instruments only",
      "calibrating the instrument once",
    ],
    correctAnswer: "taking many observations and averaging",
    explanation:
      "Random errors fluctuate; taking many observations and averaging reduces their effect.",
    difficulty: "medium",
    type: "concept",
    tags: ["errors", "random errors"],
  },
  {
    id: "qphy-p2-036",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimensional formula of angular velocity is:",
    options: ["[T⁻¹]", "[T⁻²]", "[LT⁻¹]", "[MLT⁻¹]"],
    correctAnswer: "[T⁻¹]",
    explanation: "Angular velocity = angle/time = [1]/[T] = [T⁻¹] (angle is dimensionless).",
    difficulty: "medium",
    type: "formula",
    tags: ["dimensional formula", "angular velocity"],
  },
  {
    id: "qphy-p2-037",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Errors",
    question:
      "If the error in measuring the radius of a circle is 2%, the error in its area is:",
    options: ["1%", "2%", "4%", "8%"],
    correctAnswer: "4%",
    explanation:
      "Area A = πr², so % error in A = 2 × % error in r = 2 × 2% = 4%.",
    difficulty: "medium",
    type: "numerical",
    tags: ["errors", "percentage error", "error propagation"],
  },
  {
    id: "qphy-p2-038",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimension of impulse is the same as that of:",
    options: ["momentum", "force", "energy", "power"],
    correctAnswer: "momentum",
    explanation:
      "Impulse = force × time = [MLT⁻¹]; momentum = mass × velocity = [MLT⁻¹]. Both are equal.",
    difficulty: "medium",
    type: "concept",
    tags: ["dimensional analysis", "impulse", "momentum"],
  },
  {
    id: "qphy-p2-039",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Derived Units",
    question: "1 watt is equal to:",
    options: ["1 J/s", "1 J·s", "1 N/s", "1 N·m"],
    correctAnswer: "1 J/s",
    explanation: "Power = work/time. 1 watt = 1 joule per second = 1 J/s.",
    difficulty: "easy",
    type: "formula",
    tags: ["derived units", "watt", "power"],
  },
  {
    id: "qphy-p2-040",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Units of Length",
    question: "1 nanometre is equal to:",
    options: ["10⁻⁶ m", "10⁻⁹ m", "10⁻¹² m", "10⁻¹⁰ m"],
    correctAnswer: "10⁻⁹ m",
    explanation: "1 nanometre (nm) = 10⁻⁹ m.",
    difficulty: "easy",
    type: "formula",
    tags: ["nanometre", "unit conversion"],
  },
  {
    id: "qphy-p2-041",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Significant Figures",
    question: "The number of significant figures in 200.0 is:",
    options: ["1", "2", "3", "4"],
    correctAnswer: "4",
    explanation:
      "The decimal point makes the trailing zero significant. So 200.0 has 4 significant figures.",
    difficulty: "medium",
    type: "numerical",
    tags: ["significant figures"],
  },
  {
    id: "qphy-p2-042",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimensional formula of density is:",
    options: ["[ML⁻³]", "[M⁻³L]", "[ML³]", "[ML⁻²]"],
    correctAnswer: "[ML⁻³]",
    explanation: "Density = mass/volume = [M]/[L³] = [ML⁻³].",
    difficulty: "easy",
    type: "formula",
    tags: ["dimensional formula", "density"],
  },
  {
    id: "qphy-p2-043",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Errors",
    question: "If Z = A + B, then the absolute error in Z is:",
    options: [
      "ΔZ = ΔA + ΔB",
      "ΔZ = ΔA − ΔB",
      "ΔZ/Z = ΔA/A + ΔB/B",
      "ΔZ = ΔA × ΔB",
    ],
    correctAnswer: "ΔZ = ΔA + ΔB",
    explanation:
      "For addition/subtraction, absolute errors add up: ΔZ = ΔA + ΔB (worst case).",
    difficulty: "medium",
    type: "formula",
    tags: ["errors", "error propagation", "addition"],
  },
  {
    id: "qphy-p2-044",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Errors",
    question: "If Z = A × B, then the relative error in Z is:",
    options: [
      "ΔZ/Z = ΔA/A + ΔB/B",
      "ΔZ = ΔA + ΔB",
      "ΔZ/Z = ΔA/A − ΔB/B",
      "ΔZ = ΔA × ΔB",
    ],
    correctAnswer: "ΔZ/Z = ΔA/A + ΔB/B",
    explanation:
      "For multiplication/division, relative (percentage) errors add up.",
    difficulty: "medium",
    type: "formula",
    tags: ["errors", "error propagation", "multiplication"],
  },
  {
    id: "qphy-p2-045",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimensional formula of kinetic energy is:",
    options: ["[ML²T⁻²]", "[MLT⁻²]", "[ML²T⁻¹]", "[ML⁻²T⁻²]"],
    correctAnswer: "[ML²T⁻²]",
    explanation:
      "Kinetic energy = ½mv² = [M][LT⁻¹]² = [ML²T⁻²], same as all forms of energy.",
    difficulty: "easy",
    type: "formula",
    tags: ["dimensional formula", "kinetic energy"],
  },
  {
    id: "qphy-p2-046",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Constants",
    question: "The speed of light in vacuum is approximately:",
    options: ["3 × 10⁸ m/s", "3 × 10¹⁰ m/s", "3 × 10⁶ m/s", "3 × 10⁵ m/s"],
    correctAnswer: "3 × 10⁸ m/s",
    explanation: "The speed of light in vacuum c ≈ 2.998 × 10⁸ m/s ≈ 3 × 10⁸ m/s.",
    difficulty: "easy",
    type: "formula",
    tags: ["constants", "speed of light"],
  },
  {
    id: "qphy-p2-047",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Significant Figures",
    question: "The number of significant figures in 0.00340 is:",
    options: ["2", "3", "4", "5"],
    correctAnswer: "3",
    explanation:
      "Leading zeros are not significant; trailing zeros after decimal are. So 0.00340 has 3 significant figures.",
    difficulty: "medium",
    type: "numerical",
    tags: ["significant figures"],
  },
  {
    id: "qphy-p2-048",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Astronomical Units",
    question: "1 astronomical unit (AU) is approximately equal to:",
    options: [
      "1.5 × 10¹¹ m",
      "9.46 × 10¹⁵ m",
      "3.08 × 10¹⁶ m",
      "3 × 10⁸ m",
    ],
    correctAnswer: "1.5 × 10¹¹ m",
    explanation:
      "1 AU is the mean distance between the Earth and the Sun, ≈ 1.5 × 10¹¹ m.",
    difficulty: "medium",
    type: "formula",
    tags: ["astronomical unit", "AU"],
  },
  {
    id: "qphy-p2-049",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "Which of the following has the same dimensions as pressure?",
    options: [
      "Energy per unit volume",
      "Force per unit mass",
      "Momentum per unit volume",
      "Work per unit time",
    ],
    correctAnswer: "Energy per unit volume",
    explanation:
      "Pressure = [ML⁻¹T⁻²]. Energy/volume = [ML²T⁻²]/[L³] = [ML⁻¹T⁻²]. Both match.",
    difficulty: "hard",
    type: "concept",
    tags: ["dimensional analysis", "pressure", "energy density"],
  },
  {
    id: "qphy-p2-050",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimensional formula of frequency is:",
    options: ["[T⁻¹]", "[T⁻²]", "[T]", "[MT⁻¹]"],
    correctAnswer: "[T⁻¹]",
    explanation: "Frequency = number of oscillations/time = 1/[T] = [T⁻¹].",
    difficulty: "easy",
    type: "formula",
    tags: ["dimensional formula", "frequency"],
  },
  {
    id: "qphy-p2-051",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Fundamental vs Derived Units",
    question: "Which of the following is a derived unit?",
    options: ["newton", "kilogram", "second", "mole"],
    correctAnswer: "newton",
    explanation:
      "Newton (N) is a derived unit of force (kg·m/s²); the others are SI base units.",
    difficulty: "easy",
    type: "concept",
    tags: ["derived units", "newton"],
  },
  {
    id: "qphy-p2-052",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Unit Conversion",
    question: "1 kilometre is equal to:",
    options: ["100 m", "1000 m", "10000 m", "100000 m"],
    correctAnswer: "1000 m",
    explanation: "1 km = 1000 m.",
    difficulty: "easy",
    type: "formula",
    tags: ["unit conversion", "kilometre"],
  },
  {
    id: "qphy-p2-053",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimensional formula of momentum is:",
    options: ["[MLT⁻¹]", "[MLT⁻²]", "[ML²T⁻¹]", "[M⁻¹LT⁻¹]"],
    correctAnswer: "[MLT⁻¹]",
    explanation: "Momentum = mass × velocity = [M][LT⁻¹] = [MLT⁻¹].",
    difficulty: "medium",
    type: "formula",
    tags: ["dimensional formula", "momentum"],
  },
  {
    id: "qphy-p2-054",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Significant Figures",
    question: "The number of significant figures in 0.050 is:",
    options: ["1", "2", "3", "4"],
    correctAnswer: "2",
    explanation:
      "Leading zeros are not significant. The 5 and trailing 0 (after decimal) count, giving 2 significant figures.",
    difficulty: "medium",
    type: "numerical",
    tags: ["significant figures"],
  },
  {
    id: "qphy-p2-055",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "SI Base Units",
    question: "The unit of temperature in the SI system is:",
    options: ["°C", "°F", "kelvin", "calorie"],
    correctAnswer: "kelvin",
    explanation: "Kelvin (K) is the SI base unit of temperature.",
    difficulty: "easy",
    type: "concept",
    tags: ["SI units", "temperature", "kelvin"],
  },
  {
    id: "qphy-p2-056",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Unit Conversion",
    question: "1 kilogram is equal to:",
    options: ["100 g", "1000 g", "10000 g", "100000 g"],
    correctAnswer: "1000 g",
    explanation: "1 kg = 1000 g.",
    difficulty: "easy",
    type: "formula",
    tags: ["unit conversion", "kilogram"],
  },
  {
    id: "qphy-p2-057",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Fundamental Quantities",
    question: "Which of the following is a fundamental quantity?",
    options: ["Time", "Force", "Energy", "Power"],
    correctAnswer: "Time",
    explanation: "Time (SI unit: second) is a fundamental quantity; the others are derived.",
    difficulty: "easy",
    type: "concept",
    tags: ["fundamental quantities"],
  },
  {
    id: "qphy-p2-058",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Systems of Units",
    question: "Which of the following units belongs to the FPS system?",
    options: ["foot", "metre", "centimetre", "kilometre"],
    correctAnswer: "foot",
    explanation:
      "The FPS system uses foot, pound, and second as base units.",
    difficulty: "easy",
    type: "concept",
    tags: ["FPS system", "systems of units"],
  },
  {
    id: "qphy-p2-059",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Dimensional Analysis",
    question: "The dimensional formula of angular momentum is:",
    options: ["[ML²T⁻¹]", "[MLT⁻¹]", "[ML²T⁻²]", "[ML⁻²T⁻¹]"],
    correctAnswer: "[ML²T⁻¹]",
    explanation:
      "Angular momentum L = mvr = [M][LT⁻¹][L] = [ML²T⁻¹], same as Planck's constant.",
    difficulty: "hard",
    type: "formula",
    tags: ["dimensional formula", "angular momentum"],
  },
  {
    id: "qphy-p2-060",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p2",
    chapter: "Units and Measurements",
    topic: "Errors",
    question: "If a = 5.0 ± 0.1 and b = 4.0 ± 0.2, then a + b with error is:",
    options: ["9.0 ± 0.3", "9.0 ± 0.2", "9.0 ± 0.1", "20 ± 0.3"],
    correctAnswer: "9.0 ± 0.3",
    explanation:
      "a + b = 9.0 and for addition, errors add: 0.1 + 0.2 = 0.3. So result is 9.0 ± 0.3.",
    difficulty: "hard",
    type: "numerical",
    tags: ["errors", "error propagation", "addition"],
  },

  // ==================== MOTION IN A STRAIGHT LINE (p3) — 60 questions ====================
  {
    id: "qphy-p3-001",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Displacement",
    question: "The SI unit of displacement is:",
    options: ["metre", "metre/second", "second", "joule"],
    correctAnswer: "metre",
    explanation: "Displacement is the change in position; its SI unit is the metre (m).",
    difficulty: "easy",
    type: "concept",
    tags: ["displacement", "SI units"],
  },
  {
    id: "qphy-p3-002",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Distance vs Displacement",
    question: "Distance is a ___ quantity.",
    options: ["vector", "scalar", "tensor", "dimensionless"],
    correctAnswer: "scalar",
    explanation: "Distance has magnitude only (no direction), so it is a scalar quantity.",
    difficulty: "easy",
    type: "concept",
    tags: ["distance", "scalar"],
  },
  {
    id: "qphy-p3-003",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Distance vs Displacement",
    question: "Displacement is a ___ quantity.",
    options: ["scalar", "vector", "tensor", "constant"],
    correctAnswer: "vector",
    explanation: "Displacement has both magnitude and direction, so it is a vector quantity.",
    difficulty: "easy",
    type: "concept",
    tags: ["displacement", "vector"],
  },
  {
    id: "qphy-p3-004",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Distance vs Displacement",
    question:
      "A body moves in a circle of radius r and returns to its starting point. Its displacement is:",
    options: ["2πr", "πr", "0", "r"],
    correctAnswer: "0",
    explanation:
      "Since initial and final positions are the same, displacement (which depends on endpoints only) is zero.",
    difficulty: "easy",
    type: "concept",
    tags: ["displacement", "circular motion"],
  },
  {
    id: "qphy-p3-005",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Speed",
    question: "Speed is defined as:",
    options: [
      "displacement/time",
      "distance/time",
      "velocity × time",
      "distance × time",
    ],
    correctAnswer: "distance/time",
    explanation: "Speed = total distance travelled / time taken. It is a scalar quantity.",
    difficulty: "easy",
    type: "formula",
    tags: ["speed", "definition"],
  },
  {
    id: "qphy-p3-006",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Velocity",
    question: "Velocity is defined as:",
    options: [
      "distance/time",
      "displacement/time",
      "speed × time",
      "acceleration × time",
    ],
    correctAnswer: "displacement/time",
    explanation: "Velocity = displacement/time. It is a vector quantity with direction.",
    difficulty: "easy",
    type: "formula",
    tags: ["velocity", "definition"],
  },
  {
    id: "qphy-p3-007",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Acceleration",
    question: "The SI unit of acceleration is:",
    options: ["m/s", "m/s²", "m²/s", "m/s³"],
    correctAnswer: "m/s²",
    explanation: "Acceleration = change in velocity / time = (m/s)/s = m/s².",
    difficulty: "easy",
    type: "formula",
    tags: ["acceleration", "SI units"],
  },
  {
    id: "qphy-p3-008",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Equations of Motion",
    question: "The equation v = u + at is valid when:",
    options: [
      "acceleration is uniform",
      "velocity is uniform",
      "motion is circular",
      "displacement is zero",
    ],
    correctAnswer: "acceleration is uniform",
    explanation:
      "The equations of motion (v = u + at, etc.) are valid only for uniformly accelerated motion.",
    difficulty: "medium",
    type: "formula",
    tags: ["equations of motion", "uniform acceleration"],
  },
  {
    id: "qphy-p3-009",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Free Fall",
    question:
      "A body is dropped from rest. Its velocity after 2 s (taking g = 10 m/s²) is:",
    options: ["10 m/s", "20 m/s", "5 m/s", "40 m/s"],
    correctAnswer: "20 m/s",
    explanation: "v = u + at = 0 + 10 × 2 = 20 m/s.",
    difficulty: "easy",
    type: "numerical",
    tags: ["free fall", "equations of motion"],
  },
  {
    id: "qphy-p3-010",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Graphs",
    question: "The slope of a position-time graph gives:",
    options: ["acceleration", "velocity", "displacement", "force"],
    correctAnswer: "velocity",
    explanation: "Velocity = dx/dt, so the slope of x-t graph gives velocity.",
    difficulty: "medium",
    type: "concept",
    tags: ["graphs", "position-time graph", "velocity"],
  },
  {
    id: "qphy-p3-011",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Graphs",
    question: "The slope of a velocity-time graph gives:",
    options: ["displacement", "acceleration", "velocity", "distance"],
    correctAnswer: "acceleration",
    explanation: "Acceleration = dv/dt, so the slope of v-t graph gives acceleration.",
    difficulty: "medium",
    type: "concept",
    tags: ["graphs", "velocity-time graph", "acceleration"],
  },
  {
    id: "qphy-p3-012",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Graphs",
    question: "The area under a velocity-time graph gives:",
    options: ["acceleration", "displacement", "velocity", "force"],
    correctAnswer: "displacement",
    explanation:
      "Since v = dx/dt, the integral ∫v dt = displacement; hence area under v-t graph gives displacement.",
    difficulty: "medium",
    type: "concept",
    tags: ["graphs", "velocity-time graph", "displacement"],
  },
  {
    id: "qphy-p3-013",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Graphs",
    question: "The area under an acceleration-time graph gives:",
    options: ["velocity", "displacement", "change in velocity", "distance"],
    correctAnswer: "change in velocity",
    explanation:
      "Since a = dv/dt, ∫a dt = Δv. Area under a-t graph gives the change in velocity.",
    difficulty: "medium",
    type: "concept",
    tags: ["graphs", "acceleration-time graph"],
  },
  {
    id: "qphy-p3-014",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Free Fall",
    question: "The value of acceleration due to gravity (g) is approximately:",
    options: ["8.9 m/s²", "9.8 m/s²", "10.8 m/s²", "98 m/s²"],
    correctAnswer: "9.8 m/s²",
    explanation:
      "The standard value of acceleration due to gravity near Earth's surface is about 9.8 m/s².",
    difficulty: "easy",
    type: "formula",
    tags: ["free fall", "acceleration due to gravity"],
  },
  {
    id: "qphy-p3-015",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Equations of Motion",
    question:
      "A car starts from rest and accelerates at 2 m/s². Its velocity after 5 s is:",
    options: ["5 m/s", "10 m/s", "20 m/s", "7 m/s"],
    correctAnswer: "10 m/s",
    explanation: "v = u + at = 0 + 2 × 5 = 10 m/s.",
    difficulty: "easy",
    type: "numerical",
    tags: ["equations of motion", "acceleration"],
  },
  {
    id: "qphy-p3-016",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Uniform Motion",
    question: "For a body in uniform motion, the acceleration is:",
    options: ["zero", "constant non-zero", "increasing", "decreasing"],
    correctAnswer: "zero",
    explanation:
      "Uniform motion means constant velocity, so acceleration is zero.",
    difficulty: "easy",
    type: "concept",
    tags: ["uniform motion", "acceleration"],
  },
  {
    id: "qphy-p3-017",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Graphs",
    question:
      "For uniformly accelerated motion, the velocity-time graph is:",
    options: [
      "a curve",
      "a straight line with a slope",
      "a horizontal line",
      "a vertical line",
    ],
    correctAnswer: "a straight line with a slope",
    explanation:
      "Since v = u + at is linear in t, the v-t graph is a straight line with slope = a.",
    difficulty: "easy",
    type: "concept",
    tags: ["graphs", "velocity-time graph", "uniform acceleration"],
  },
  {
    id: "qphy-p3-018",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Free Fall",
    question:
      "A ball is thrown upward with velocity 19.6 m/s. The maximum height reached (g = 9.8 m/s²) is:",
    options: ["9.8 m", "19.6 m", "39.2 m", "4.9 m"],
    correctAnswer: "19.6 m",
    explanation:
      "At max height, v = 0. Using v² = u² − 2gh: 0 = (19.6)² − 2(9.8)h, so h = 19.6 m.",
    difficulty: "medium",
    type: "numerical",
    tags: ["free fall", "equations of motion", "vertical motion"],
  },
  {
    id: "qphy-p3-019",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Free Fall",
    question:
      "The time taken to reach maximum height when u = 19.6 m/s and g = 9.8 m/s² is:",
    options: ["1 s", "2 s", "3 s", "4 s"],
    correctAnswer: "2 s",
    explanation: "At top, v = 0. t = u/g = 19.6/9.8 = 2 s.",
    difficulty: "medium",
    type: "numerical",
    tags: ["free fall", "time of ascent"],
  },
  {
    id: "qphy-p3-020",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Equations of Motion",
    question:
      "A car moving with 20 m/s decelerates at 4 m/s². The time taken to stop is:",
    options: ["4 s", "5 s", "8 s", "10 s"],
    correctAnswer: "5 s",
    explanation: "v = u + at; 0 = 20 − 4t; t = 5 s.",
    difficulty: "medium",
    type: "numerical",
    tags: ["equations of motion", "deceleration"],
  },
  {
    id: "qphy-p3-021",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Equations of Motion",
    question:
      "A body starts from rest and moves with acceleration 5 m/s². The distance covered in 4 s is:",
    options: ["20 m", "40 m", "80 m", "10 m"],
    correctAnswer: "40 m",
    explanation: "s = ut + ½at² = 0 + ½ × 5 × 16 = 40 m.",
    difficulty: "easy",
    type: "numerical",
    tags: ["equations of motion", "acceleration"],
  },
  {
    id: "qphy-p3-022",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Graphs",
    question: "The velocity-time graph of a body at rest is:",
    options: [
      "a straight line with positive slope",
      "a horizontal line on the time axis",
      "a parabola",
      "a vertical line",
    ],
    correctAnswer: "a horizontal line on the time axis",
    explanation:
      "If the body is at rest, velocity = 0 at all times — a horizontal line along the time axis (v = 0).",
    difficulty: "easy",
    type: "concept",
    tags: ["graphs", "velocity-time graph", "rest"],
  },
  {
    id: "qphy-p3-023",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Vertical Motion",
    question:
      "A body projected vertically upward returns to the ground. The total displacement is:",
    options: [
      "equal to maximum height",
      "twice the maximum height",
      "zero",
      "equal to range",
    ],
    correctAnswer: "zero",
    explanation:
      "Initial and final positions are the same, so the total displacement is zero.",
    difficulty: "medium",
    type: "concept",
    tags: ["displacement", "vertical motion"],
  },
  {
    id: "qphy-p3-024",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Uniform Motion",
    question:
      "If a body covers equal distances in equal intervals of time, it has:",
    options: [
      "uniform velocity",
      "uniform acceleration",
      "non-uniform velocity",
      "zero displacement",
    ],
    correctAnswer: "uniform velocity",
    explanation:
      "Equal distances in equal time intervals imply constant speed; in a straight line, that means uniform velocity.",
    difficulty: "easy",
    type: "concept",
    tags: ["uniform motion", "velocity"],
  },
  {
    id: "qphy-p3-025",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Speed",
    question: "A train 100 m long crosses a pole in 5 s. Its speed is:",
    options: ["10 m/s", "20 m/s", "25 m/s", "50 m/s"],
    correctAnswer: "20 m/s",
    explanation: "Speed = distance/time = 100/5 = 20 m/s.",
    difficulty: "medium",
    type: "numerical",
    tags: ["speed", "numerical"],
  },
  {
    id: "qphy-p3-026",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Equations of Motion",
    question:
      "A body moving with velocity 10 m/s accelerates at 3 m/s². Its velocity after 4 s is:",
    options: ["12 m/s", "22 m/s", "40 m/s", "14 m/s"],
    correctAnswer: "22 m/s",
    explanation: "v = u + at = 10 + 3 × 4 = 22 m/s.",
    difficulty: "easy",
    type: "numerical",
    tags: ["equations of motion", "acceleration"],
  },
  {
    id: "qphy-p3-027",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Speed",
    question: "A car moves at 15 m/s. The distance covered in 1 minute is:",
    options: ["15 m", "90 m", "900 m", "1500 m"],
    correctAnswer: "900 m",
    explanation: "Distance = speed × time = 15 × 60 = 900 m.",
    difficulty: "easy",
    type: "numerical",
    tags: ["speed", "distance"],
  },
  {
    id: "qphy-p3-028",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Acceleration",
    question: "The acceleration of a body moving with constant velocity is:",
    options: ["zero", "positive", "negative", "infinite"],
    correctAnswer: "zero",
    explanation:
      "Constant velocity means no change in velocity, so acceleration is zero.",
    difficulty: "easy",
    type: "concept",
    tags: ["acceleration", "constant velocity"],
  },
  {
    id: "qphy-p3-029",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Free Fall",
    question:
      "A stone is dropped from rest. The distance covered in the 3rd second (g = 10 m/s²) is:",
    options: ["25 m", "30 m", "45 m", "15 m"],
    correctAnswer: "25 m",
    explanation:
      "Distance in nth second: sₙ = u + (a/2)(2n − 1) = 0 + 5 × (5) = 25 m.",
    difficulty: "hard",
    type: "numerical",
    tags: ["free fall", "distance in nth second"],
  },
  {
    id: "qphy-p3-030",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Vertical Motion",
    question:
      "A ball is thrown vertically upward. At the maximum height, its acceleration is:",
    options: ["zero", "g downward", "g upward", "2g"],
    correctAnswer: "g downward",
    explanation:
      "Throughout free fall (including at the top), gravity acts downward, so acceleration is g downward.",
    difficulty: "medium",
    type: "concept",
    tags: ["vertical motion", "acceleration due to gravity"],
  },
  {
    id: "qphy-p3-031",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Uniform Motion",
    question: "A body moves with uniform velocity. Its acceleration is:",
    options: ["uniform non-zero", "zero", "increasing", "decreasing"],
    correctAnswer: "zero",
    explanation:
      "Uniform velocity means constant velocity, hence acceleration is zero.",
    difficulty: "easy",
    type: "concept",
    tags: ["uniform motion", "acceleration"],
  },
  {
    id: "qphy-p3-032",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Graphs",
    question: "The distance-time graph of a body at rest is:",
    options: [
      "a straight line with a slope",
      "a horizontal line parallel to the time axis",
      "a curve",
      "a vertical line",
    ],
    correctAnswer: "a horizontal line parallel to the time axis",
    explanation:
      "If the body is at rest, distance does not change with time — a horizontal line parallel to the time axis.",
    difficulty: "easy",
    type: "concept",
    tags: ["graphs", "distance-time graph", "rest"],
  },
  {
    id: "qphy-p3-033",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Vertical Motion",
    question:
      "A ball is thrown vertically upward with 30 m/s. Its time of flight (g = 10 m/s²) is:",
    options: ["3 s", "6 s", "9 s", "12 s"],
    correctAnswer: "6 s",
    explanation:
      "Time of flight = 2u/g = 2 × 30/10 = 6 s (symmetric up and down).",
    difficulty: "medium",
    type: "numerical",
    tags: ["vertical motion", "time of flight"],
  },
  {
    id: "qphy-p3-034",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Acceleration",
    question:
      "A car accelerates uniformly from 5 m/s to 25 m/s in 5 s. Its acceleration is:",
    options: ["2 m/s²", "4 m/s²", "5 m/s²", "20 m/s²"],
    correctAnswer: "4 m/s²",
    explanation: "a = (v − u)/t = (25 − 5)/5 = 4 m/s².",
    difficulty: "easy",
    type: "numerical",
    tags: ["acceleration", "equations of motion"],
  },
  {
    id: "qphy-p3-035",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Relative Velocity",
    question:
      "Two trains move towards each other at 30 m/s and 40 m/s. Their relative velocity is:",
    options: ["10 m/s", "70 m/s", "50 m/s", "35 m/s"],
    correctAnswer: "70 m/s",
    explanation:
      "When moving in opposite directions, relative velocity = 30 + 40 = 70 m/s.",
    difficulty: "medium",
    type: "numerical",
    tags: ["relative velocity"],
  },
  {
    id: "qphy-p3-036",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Relative Velocity",
    question:
      "A swimmer swims at 5 m/s in still water. If the river flows at 3 m/s, his velocity relative to the ground (downstream) is:",
    options: ["2 m/s", "5 m/s", "8 m/s", "15 m/s"],
    correctAnswer: "8 m/s",
    explanation:
      "Downstream, velocities add: 5 + 3 = 8 m/s.",
    difficulty: "medium",
    type: "numerical",
    tags: ["relative velocity", "river-boat"],
  },
  {
    id: "qphy-p3-037",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Graphs",
    question: "The slope of a distance-time graph gives:",
    options: ["velocity", "speed", "acceleration", "displacement"],
    correctAnswer: "speed",
    explanation:
      "Distance/time = speed. Since distance is scalar, the slope of a distance-time graph gives speed.",
    difficulty: "medium",
    type: "concept",
    tags: ["graphs", "distance-time graph", "speed"],
  },
  {
    id: "qphy-p3-038",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Equations of Motion",
    question:
      "A body starts from rest and accelerates at 10 m/s². The distance covered in 3 s is:",
    options: ["30 m", "45 m", "90 m", "15 m"],
    correctAnswer: "45 m",
    explanation: "s = ut + ½at² = 0 + ½ × 10 × 9 = 45 m.",
    difficulty: "easy",
    type: "numerical",
    tags: ["equations of motion", "acceleration"],
  },
  {
    id: "qphy-p3-039",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Equations of Motion",
    question:
      "Using v² = u² + 2as, if u = 0, a = 2 m/s², s = 25 m, then v is:",
    options: ["5 m/s", "10 m/s", "50 m/s", "100 m/s"],
    correctAnswer: "10 m/s",
    explanation: "v² = 0 + 2 × 2 × 25 = 100, so v = 10 m/s.",
    difficulty: "medium",
    type: "numerical",
    tags: ["equations of motion"],
  },
  {
    id: "qphy-p3-040",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Equations of Motion",
    question:
      "A body moving at 20 m/s decelerates at 5 m/s². The distance before it stops is:",
    options: ["20 m", "40 m", "80 m", "100 m"],
    correctAnswer: "40 m",
    explanation:
      "v² = u² + 2as; 0 = 400 − 2 × 5 × s; s = 40 m.",
    difficulty: "medium",
    type: "numerical",
    tags: ["equations of motion", "deceleration"],
  },
  {
    id: "qphy-p3-041",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Acceleration",
    question: "Negative acceleration means:",
    options: [
      "velocity is increasing",
      "velocity is decreasing",
      "body is at rest",
      "body is moving upward",
    ],
    correctAnswer: "velocity is decreasing",
    explanation:
      "Negative acceleration (retardation) means the velocity of the body is decreasing with time.",
    difficulty: "easy",
    type: "concept",
    tags: ["acceleration", "deceleration"],
  },
  {
    id: "qphy-p3-042",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Free Fall",
    question:
      "A body falls freely from a height h. The time to reach the ground (g = 10 m/s²) when h = 20 m is:",
    options: ["1 s", "2 s", "4 s", "5 s"],
    correctAnswer: "2 s",
    explanation: "h = ½gt²; 20 = ½ × 10 × t²; t² = 4; t = 2 s.",
    difficulty: "medium",
    type: "numerical",
    tags: ["free fall", "equations of motion"],
  },
  {
    id: "qphy-p3-043",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Average Velocity",
    question:
      "A body covers 10 m in 2 s and 30 m in the next 2 s. The average velocity over 4 s is:",
    options: ["5 m/s", "7.5 m/s", "10 m/s", "15 m/s"],
    correctAnswer: "10 m/s",
    explanation: "Total displacement = 40 m, total time = 4 s. Avg velocity = 40/4 = 10 m/s.",
    difficulty: "medium",
    type: "numerical",
    tags: ["average velocity"],
  },
  {
    id: "qphy-p3-044",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Vertical Motion",
    question:
      "A ball is thrown upward. At the highest point, its velocity is:",
    options: ["maximum", "zero", "equal to initial", "double the initial"],
    correctAnswer: "zero",
    explanation:
      "At the highest point of vertical motion, velocity momentarily becomes zero before reversing direction.",
    difficulty: "easy",
    type: "concept",
    tags: ["vertical motion", "velocity"],
  },
  {
    id: "qphy-p3-045",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Speed vs Velocity",
    question:
      "The motion of a body with constant speed but varying velocity is:",
    options: [
      "not possible",
      "possible (e.g., circular motion)",
      "uniform motion",
      "free fall",
    ],
    correctAnswer: "possible (e.g., circular motion)",
    explanation:
      "In uniform circular motion, speed is constant but velocity (direction) keeps changing.",
    difficulty: "medium",
    type: "concept",
    tags: ["speed vs velocity", "circular motion"],
  },
  {
    id: "qphy-p3-046",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Average Speed",
    question:
      "A car covers 60 km in the first hour and 80 km in the next hour. Its average speed is:",
    options: ["60 km/h", "70 km/h", "80 km/h", "140 km/h"],
    correctAnswer: "70 km/h",
    explanation: "Average speed = total distance/total time = (60 + 80)/2 = 70 km/h.",
    difficulty: "easy",
    type: "numerical",
    tags: ["average speed"],
  },
  {
    id: "qphy-p3-047",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Instantaneous Quantities",
    question:
      "A body moves with v = 4t. At t = 2 s, its acceleration is:",
    options: ["2 m/s²", "4 m/s²", "8 m/s²", "16 m/s²"],
    correctAnswer: "4 m/s²",
    explanation: "a = dv/dt = d(4t)/dt = 4 m/s², constant for all t.",
    difficulty: "medium",
    type: "numerical",
    tags: ["instantaneous acceleration", "calculus"],
  },
  {
    id: "qphy-p3-048",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Speed",
    question:
      "A train 150 m long crosses a platform 250 m long in 20 s. The speed of the train is:",
    options: ["10 m/s", "20 m/s", "15 m/s", "25 m/s"],
    correctAnswer: "20 m/s",
    explanation:
      "Total distance = 150 + 250 = 400 m. Speed = 400/20 = 20 m/s.",
    difficulty: "medium",
    type: "numerical",
    tags: ["speed", "train problem"],
  },
  {
    id: "qphy-p3-049",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Vertical Motion",
    question:
      "A body projected upward takes 4 s to reach maximum height. Its initial velocity (g = 10 m/s²) is:",
    options: ["20 m/s", "40 m/s", "10 m/s", "5 m/s"],
    correctAnswer: "40 m/s",
    explanation: "At top, v = 0; t = u/g; u = gt = 10 × 4 = 40 m/s.",
    difficulty: "medium",
    type: "numerical",
    tags: ["vertical motion", "equations of motion"],
  },
  {
    id: "qphy-p3-050",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Average vs Instantaneous",
    question:
      "The instantaneous velocity equals the average velocity when:",
    options: [
      "body is at rest",
      "motion is uniform",
      "acceleration is non-zero",
      "the body is in free fall",
    ],
    correctAnswer: "motion is uniform",
    explanation:
      "In uniform motion (constant velocity), every instantaneous value equals the average.",
    difficulty: "hard",
    type: "concept",
    tags: ["average velocity", "instantaneous velocity", "uniform motion"],
  },
  {
    id: "qphy-p3-051",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Distance in nth Second",
    question:
      "A body moving with 10 m/s accelerates at 2 m/s². The distance covered in the 5th second is:",
    options: ["19 m", "20 m", "18 m", "25 m"],
    correctAnswer: "19 m",
    explanation:
      "sₙ = u + (a/2)(2n − 1) = 10 + 1 × 9 = 19 m.",
    difficulty: "hard",
    type: "numerical",
    tags: ["distance in nth second", "equations of motion"],
  },
  {
    id: "qphy-p3-052",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Relative Velocity",
    question:
      "Two cars move in the same direction at 50 km/h and 30 km/h. The relative velocity of the first w.r.t. the second is:",
    options: ["80 km/h", "20 km/h", "50 km/h", "30 km/h"],
    correctAnswer: "20 km/h",
    explanation:
      "Same direction: relative velocity = 50 − 30 = 20 km/h.",
    difficulty: "medium",
    type: "numerical",
    tags: ["relative velocity"],
  },
  {
    id: "qphy-p3-053",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Vertical Motion",
    question:
      "A body thrown vertically up with 40 m/s. Its velocity at half the maximum height (g = 10 m/s²) is:",
    options: ["20 m/s", "20√2 m/s", "10 m/s", "40 m/s"],
    correctAnswer: "20√2 m/s",
    explanation:
      "Max height H = u²/(2g) = 1600/20 = 80 m. At h = 40 m: v² = 1600 − 2(10)(40) = 800; v = 20√2 m/s.",
    difficulty: "hard",
    type: "numerical",
    tags: ["vertical motion", "equations of motion"],
  },
  {
    id: "qphy-p3-054",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Free Fall",
    question:
      "A body falls from rest. The ratio of distances covered in the 1st, 2nd, and 3rd seconds is:",
    options: ["1 : 3 : 5", "1 : 2 : 3", "1 : 4 : 9", "1 : 8 : 27"],
    correctAnswer: "1 : 3 : 5",
    explanation:
      "Distances from rest in successive seconds are in the ratio 1 : 3 : 5 : 7 ... (odd numbers).",
    difficulty: "medium",
    type: "formula",
    tags: ["free fall", "distance ratio"],
  },
  {
    id: "qphy-p3-055",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Unit Conversion",
    question:
      "A car accelerates from 0 to 60 km/h in 10 s. Its acceleration in m/s² is:",
    options: ["1.67 m/s²", "6 m/s²", "60 m/s²", "600 m/s²"],
    correctAnswer: "1.67 m/s²",
    explanation:
      "60 km/h = 60 × 5/18 ≈ 16.67 m/s. a = 16.67/10 ≈ 1.67 m/s².",
    difficulty: "medium",
    type: "numerical",
    tags: ["unit conversion", "acceleration"],
  },
  {
    id: "qphy-p3-056",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Graphs",
    question: "The area under a speed-time graph gives:",
    options: ["velocity", "distance", "acceleration", "displacement"],
    correctAnswer: "distance",
    explanation:
      "Since speed = distance/time, the area under a speed-time graph gives the total distance travelled.",
    difficulty: "medium",
    type: "concept",
    tags: ["graphs", "speed-time graph", "distance"],
  },
  {
    id: "qphy-p3-057",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Free Fall",
    question:
      "A ball is dropped from a height of 45 m (g = 10 m/s²). The time to reach the ground is:",
    options: ["2 s", "3 s", "4.5 s", "9 s"],
    correctAnswer: "3 s",
    explanation: "h = ½gt²; 45 = ½ × 10 × t²; t² = 9; t = 3 s.",
    difficulty: "medium",
    type: "numerical",
    tags: ["free fall", "equations of motion"],
  },
  {
    id: "qphy-p3-058",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Instantaneous Quantities",
    question:
      "A particle moves along the x-axis with x = 5t². Its velocity at t = 3 s is:",
    options: ["15 m/s", "30 m/s", "45 m/s", "5 m/s"],
    correctAnswer: "30 m/s",
    explanation: "v = dx/dt = 10t; at t = 3 s, v = 30 m/s.",
    difficulty: "medium",
    type: "numerical",
    tags: ["instantaneous velocity", "calculus"],
  },
  {
    id: "qphy-p3-059",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Vertical Motion",
    question:
      "When a body is thrown upward, its acceleration during the ascent is:",
    options: ["zero", "g downward", "g upward", "decreasing"],
    correctAnswer: "g downward",
    explanation:
      "Gravity always acts downward. During ascent (and descent), the acceleration is g downward.",
    difficulty: "medium",
    type: "concept",
    tags: ["vertical motion", "acceleration due to gravity"],
  },
  {
    id: "qphy-p3-060",
    subject: "physics",
    subjectName: "Physics",
    chapterId: "p3",
    chapter: "Motion in a Straight Line",
    topic: "Deceleration",
    question:
      "A car moving at 36 km/h stops in 5 s after applying the brakes. Its deceleration is:",
    options: ["2 m/s²", "7.2 m/s²", "36 m/s²", "5 m/s²"],
    correctAnswer: "2 m/s²",
    explanation:
      "36 km/h = 10 m/s. a = (0 − 10)/5 = −2 m/s², so deceleration = 2 m/s².",
    difficulty: "medium",
    type: "numerical",
    tags: ["deceleration", "unit conversion"],
  },
];
