import type { QuizMCQ } from "./quizzes-physics";

export const CS_QUIZZES: QuizMCQ[] = [
  // ==================== NUMBER SYSTEM AND CONVERSION (cs2) — 30 questions ====================
  {
    id: "qcs-cs2-001",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Number Bases",
    question: "The binary number system uses which base?",
    options: ["2", "8", "10", "16"],
    correctAnswer: "2",
    explanation:
      "The binary system uses base 2 with digits 0 and 1 only.",
    difficulty: "easy",
    type: "concept",
    tags: ["binary", "number systems"],
  },
  {
    id: "qcs-cs2-002",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Number Bases",
    question: "The octal number system uses which base?",
    options: ["8", "2", "10", "16"],
    correctAnswer: "8",
    explanation:
      "The octal system uses base 8 with digits 0 through 7.",
    difficulty: "easy",
    type: "concept",
    tags: ["octal", "number systems"],
  },
  {
    id: "qcs-cs2-003",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Number Bases",
    question: "The decimal number system uses which base?",
    options: ["10", "2", "8", "16"],
    correctAnswer: "10",
    explanation:
      "The decimal system uses base 10 with digits 0 through 9.",
    difficulty: "easy",
    type: "concept",
    tags: ["decimal", "number systems"],
  },
  {
    id: "qcs-cs2-004",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Number Bases",
    question: "The hexadecimal number system uses which base?",
    options: ["16", "10", "8", "2"],
    correctAnswer: "16",
    explanation:
      "The hexadecimal system uses base 16 with digits 0–9 and A–F.",
    difficulty: "easy",
    type: "concept",
    tags: ["hexadecimal", "number systems"],
  },
  {
    id: "qcs-cs2-005",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Decimal to Binary",
    question: "The binary equivalent of decimal 5 is:",
    options: ["101", "110", "100", "011"],
    correctAnswer: "101",
    explanation:
      "5 = 4 + 1 = 1×2² + 0×2¹ + 1×2⁰, so binary is 101.",
    difficulty: "easy",
    type: "numerical",
    tags: ["decimal to binary", "conversion"],
  },
  {
    id: "qcs-cs2-006",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Binary to Decimal",
    question: "The decimal equivalent of binary 1010 is:",
    options: ["10", "8", "12", "11"],
    correctAnswer: "10",
    explanation:
      "1010 = 1×8 + 0×4 + 1×2 + 0×1 = 8 + 2 = 10.",
    difficulty: "easy",
    type: "numerical",
    tags: ["binary to decimal", "conversion"],
  },
  {
    id: "qcs-cs2-007",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Binary to Decimal",
    question: "The decimal equivalent of binary 1111 is:",
    options: ["15", "14", "16", "13"],
    correctAnswer: "15",
    explanation:
      "1111 = 8 + 4 + 2 + 1 = 15.",
    difficulty: "easy",
    type: "numerical",
    tags: ["binary to decimal", "conversion"],
  },
  {
    id: "qcs-cs2-008",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Binary to Decimal",
    question: "The decimal equivalent of binary 10000 is:",
    options: ["16", "8", "15", "32"],
    correctAnswer: "16",
    explanation:
      "10000 = 1×2⁴ = 16.",
    difficulty: "easy",
    type: "numerical",
    tags: ["binary to decimal", "conversion"],
  },
  {
    id: "qcs-cs2-009",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Hexadecimal",
    question: "The digits used in the hexadecimal system range from:",
    options: [
      "0–9 and A–F",
      "0–9 only",
      "1–9",
      "0–7",
    ],
    correctAnswer: "0–9 and A–F",
    explanation:
      "Hexadecimal uses 16 symbols: 0, 1, ..., 9, A, B, C, D, E, F (where A=10, ..., F=15).",
    difficulty: "easy",
    type: "concept",
    tags: ["hexadecimal", "digits"],
  },
  {
    id: "qcs-cs2-010",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Octal to Binary",
    question: "The binary equivalent of octal 7 is:",
    options: ["111", "100", "110", "101"],
    correctAnswer: "111",
    explanation:
      "Each octal digit maps to 3 bits. 7 = 111 in binary.",
    difficulty: "easy",
    type: "numerical",
    tags: ["octal to binary", "conversion"],
  },
  {
    id: "qcs-cs2-011",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Hex to Decimal",
    question: "The decimal equivalent of hexadecimal A is:",
    options: ["10", "11", "12", "1"],
    correctAnswer: "10",
    explanation:
      "In hexadecimal, A represents the decimal value 10.",
    difficulty: "easy",
    type: "numerical",
    tags: ["hex to decimal", "conversion"],
  },
  {
    id: "qcs-cs2-012",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Hex to Decimal",
    question: "The decimal equivalent of hexadecimal F is:",
    options: ["15", "16", "14", "0"],
    correctAnswer: "15",
    explanation:
      "In hexadecimal, F represents the decimal value 15.",
    difficulty: "easy",
    type: "numerical",
    tags: ["hex to decimal", "conversion"],
  },
  {
    id: "qcs-cs2-013",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Decimal to Binary",
    question: "The binary equivalent of decimal 8 is:",
    options: ["1000", "1001", "111", "1010"],
    correctAnswer: "1000",
    explanation:
      "8 = 1×2³, so binary is 1000.",
    difficulty: "easy",
    type: "numerical",
    tags: ["decimal to binary", "conversion"],
  },
  {
    id: "qcs-cs2-014",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Octal to Decimal",
    question: "The decimal equivalent of octal 10 is:",
    options: ["8", "10", "2", "16"],
    correctAnswer: "8",
    explanation:
      "Octal 10 = 1×8¹ + 0×8⁰ = 8 in decimal.",
    difficulty: "easy",
    type: "numerical",
    tags: ["octal to decimal", "conversion"],
  },
  {
    id: "qcs-cs2-015",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Hex to Decimal",
    question: "The decimal equivalent of hexadecimal 10 is:",
    options: ["16", "10", "8", "32"],
    correctAnswer: "16",
    explanation:
      "Hex 10 = 1×16¹ + 0×16⁰ = 16 in decimal.",
    difficulty: "easy",
    type: "numerical",
    tags: ["hex to decimal", "conversion"],
  },
  {
    id: "qcs-cs2-016",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Decimal to Binary",
    question: "The binary equivalent of decimal 16 is:",
    options: ["10000", "1111", "10001", "100000"],
    correctAnswer: "10000",
    explanation:
      "16 = 1×2⁴, so binary is 10000.",
    difficulty: "easy",
    type: "numerical",
    tags: ["decimal to binary", "conversion"],
  },
  {
    id: "qcs-cs2-017",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Bits and Bytes",
    question: "The number of bits in a nibble is:",
    options: ["4", "8", "2", "16"],
    correctAnswer: "4",
    explanation:
      "A nibble is a group of 4 bits (half a byte).",
    difficulty: "easy",
    type: "concept",
    tags: ["nibble", "bits", "bytes"],
  },
  {
    id: "qcs-cs2-018",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Bits and Bytes",
    question: "The number of bits in a byte is:",
    options: ["8", "4", "16", "2"],
    correctAnswer: "8",
    explanation:
      "One byte consists of 8 bits.",
    difficulty: "easy",
    type: "concept",
    tags: ["byte", "bits"],
  },
  {
    id: "qcs-cs2-019",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Binary to Octal",
    question: "The octal equivalent of binary 111000 is:",
    options: ["70", "07", "71", "17"],
    correctAnswer: "70",
    explanation:
      "Group bits in threes from right: 111 = 7, 000 = 0, so octal is 70.",
    difficulty: "medium",
    type: "numerical",
    tags: ["binary to octal", "conversion"],
  },
  {
    id: "qcs-cs2-020",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Binary to Hex",
    question: "The hexadecimal equivalent of binary 11110000 is:",
    options: ["F0", "0F", "FF", "70"],
    correctAnswer: "F0",
    explanation:
      "Group bits in fours: 1111 = F, 0000 = 0, so hex is F0.",
    difficulty: "medium",
    type: "numerical",
    tags: ["binary to hex", "conversion"],
  },
  {
    id: "qcs-cs2-021",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Binary to Decimal",
    question: "The decimal equivalent of binary 11001 is:",
    options: ["25", "24", "26", "28"],
    correctAnswer: "25",
    explanation:
      "11001 = 16 + 8 + 0 + 0 + 1 = 25.",
    difficulty: "medium",
    type: "numerical",
    tags: ["binary to decimal", "conversion"],
  },
  {
    id: "qcs-cs2-022",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Decimal to Octal",
    question: "The octal equivalent of decimal 8 is:",
    options: ["10", "8", "11", "7"],
    correctAnswer: "10",
    explanation:
      "8 = 1×8¹ + 0×8⁰, so octal is 10.",
    difficulty: "medium",
    type: "numerical",
    tags: ["decimal to octal", "conversion"],
  },
  {
    id: "qcs-cs2-023",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Decimal to Hex",
    question: "The hexadecimal equivalent of decimal 255 is:",
    options: ["FF", "100", "FE", "F0"],
    correctAnswer: "FF",
    explanation:
      "255 = 15×16 + 15 = FF in hexadecimal.",
    difficulty: "medium",
    type: "numerical",
    tags: ["decimal to hex", "conversion"],
  },
  {
    id: "qcs-cs2-024",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Decimal to Binary",
    question: "The binary equivalent of decimal 2 is:",
    options: ["10", "01", "11", "100"],
    correctAnswer: "10",
    explanation:
      "2 = 1×2¹ + 0×2⁰, so binary is 10.",
    difficulty: "easy",
    type: "numerical",
    tags: ["decimal to binary", "conversion"],
  },
  {
    id: "qcs-cs2-025",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Decimal to Binary",
    question: "The binary equivalent of decimal 0 is:",
    options: ["0", "1", "00", "10"],
    correctAnswer: "0",
    explanation:
      "Decimal 0 is 0 in binary (and in all bases).",
    difficulty: "easy",
    type: "numerical",
    tags: ["decimal to binary", "conversion"],
  },
  {
    id: "qcs-cs2-026",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Decimal to Binary",
    question: "The binary equivalent of decimal 10 is:",
    options: ["1010", "1100", "1001", "1110"],
    correctAnswer: "1010",
    explanation:
      "10 = 8 + 2 = 1010 in binary.",
    difficulty: "easy",
    type: "numerical",
    tags: ["decimal to binary", "conversion"],
  },
  {
    id: "qcs-cs2-027",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Binary to Decimal",
    question: "The decimal equivalent of binary 100 is:",
    options: ["4", "3", "5", "2"],
    correctAnswer: "4",
    explanation:
      "100 = 1×2² = 4 in decimal.",
    difficulty: "easy",
    type: "numerical",
    tags: ["binary to decimal", "conversion"],
  },
  {
    id: "qcs-cs2-028",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Decimal to Binary",
    question: "The binary equivalent of decimal 15 is:",
    options: ["1111", "1000", "1010", "1100"],
    correctAnswer: "1111",
    explanation:
      "15 = 8 + 4 + 2 + 1 = 1111 in binary.",
    difficulty: "easy",
    type: "numerical",
    tags: ["decimal to binary", "conversion"],
  },
  {
    id: "qcs-cs2-029",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Hex to Decimal",
    question: "The decimal equivalent of hexadecimal 1A is:",
    options: ["26", "16", "10", "32"],
    correctAnswer: "26",
    explanation:
      "1A = 1×16 + 10 = 26 in decimal (A = 10).",
    difficulty: "medium",
    type: "numerical",
    tags: ["hex to decimal", "conversion"],
  },
  {
    id: "qcs-cs2-030",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs2",
    chapter: "Number System and Conversion",
    topic: "Decimal to Hex",
    question: "The hexadecimal equivalent of decimal 16 is:",
    options: ["10", "16", "F", "1A"],
    correctAnswer: "10",
    explanation:
      "16 = 1×16¹ + 0×16⁰, so hexadecimal is 10.",
    difficulty: "medium",
    type: "numerical",
    tags: ["decimal to hex", "conversion"],
  },

  // ==================== INTRODUCING PYTHON (cs5) — 40 questions ====================
  {
    id: "qcs-cs5-001",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "History of Python",
    question: "Python was created by:",
    options: [
      "Guido van Rossum",
      "Dennis Ritchie",
      "James Gosling",
      "Bjarne Stroustrup",
    ],
    correctAnswer: "Guido van Rossum",
    explanation:
      "Python was created by Guido van Rossum and released in 1991.",
    difficulty: "easy",
    type: "concept",
    tags: ["python history"],
  },
  {
    id: "qcs-cs5-002",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Python Characteristics",
    question: "Python is a ___ language.",
    options: ["interpreted", "compiled only", "assembly", "machine"],
    correctAnswer: "interpreted",
    explanation:
      "Python is an interpreted language; its source code is executed line by line by an interpreter.",
    difficulty: "easy",
    type: "concept",
    tags: ["interpreted", "python characteristics"],
  },
  {
    id: "qcs-cs5-003",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Tokens",
    question: "The smallest individual unit in a Python program is a:",
    options: ["token", "keyword", "identifier", "literal"],
    correctAnswer: "token",
    explanation:
      "A token is the smallest individual element of a Python program (keywords, identifiers, literals, operators, punctuators).",
    difficulty: "easy",
    type: "concept",
    tags: ["tokens"],
  },
  {
    id: "qcs-cs5-004",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Keywords",
    question: "Which of the following is a keyword in Python?",
    options: ["for", "variable", "main", "compute"],
    correctAnswer: "for",
    explanation:
      "'for' is a reserved keyword in Python used for loops. The others are not keywords.",
    difficulty: "easy",
    type: "concept",
    tags: ["keywords"],
  },
  {
    id: "qcs-cs5-005",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Identifiers",
    question: "Which of the following is a valid Python identifier?",
    options: ["my_var", "2name", "my-var", "class"],
    correctAnswer: "my_var",
    explanation:
      "Identifiers can contain letters, digits, and underscores, but cannot start with a digit, contain a hyphen, or be a keyword like 'class'.",
    difficulty: "easy",
    type: "concept",
    tags: ["identifiers", "naming rules"],
  },
  {
    id: "qcs-cs5-006",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Identifiers",
    question: "Which of the following is NOT a valid Python identifier?",
    options: ["2num", "num_2", "_num", "num2"],
    correctAnswer: "2num",
    explanation:
      "An identifier cannot begin with a digit. 2num is invalid.",
    difficulty: "easy",
    type: "concept",
    tags: ["identifiers", "naming rules"],
  },
  {
    id: "qcs-cs5-007",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Comments",
    question: "A comment in Python starts with the symbol:",
    options: ["#", "//", "/*", "--"],
    correctAnswer: "#",
    explanation:
      "In Python, single-line comments begin with the # symbol.",
    difficulty: "easy",
    type: "concept",
    tags: ["comments"],
  },
  {
    id: "qcs-cs5-008",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Case Sensitivity",
    question: "Python is case-sensitive. True or False?",
    options: ["True", "False", "Sometimes", "Only for keywords"],
    correctAnswer: "True",
    explanation:
      "Python is case-sensitive — 'Name' and 'name' are different identifiers.",
    difficulty: "easy",
    type: "true-false",
    tags: ["case sensitivity"],
  },
  {
    id: "qcs-cs5-009",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Data Types",
    question: 'What is the output of: print(type(5))?',
    options: [
      "<class 'int'>",
      "<class 'float'>",
      "<class 'str'>",
      "int",
    ],
    correctAnswer: "<class 'int'>",
    explanation:
      "5 is an integer, so type(5) returns <class 'int'>.",
    difficulty: "easy",
    type: "output",
    tags: ["data types", "type()", "int"],
  },
  {
    id: "qcs-cs5-010",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Operators",
    question: "What is the output of: print(2 ** 3)?",
    options: ["8", "6", "9", "5"],
    correctAnswer: "8",
    explanation:
      "** is the exponentiation operator. 2 ** 3 = 2³ = 8.",
    difficulty: "easy",
    type: "output",
    tags: ["operators", "exponentiation"],
  },
  {
    id: "qcs-cs5-011",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Operators",
    question: "What is the output of: print(7 // 2)?",
    options: ["3", "3.5", "4", "2"],
    correctAnswer: "3",
    explanation:
      "// is floor division: 7 // 2 = 3 (the integer part of 3.5).",
    difficulty: "easy",
    type: "output",
    tags: ["operators", "floor division"],
  },
  {
    id: "qcs-cs5-012",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Operators",
    question: "What is the output of: print(7 % 2)?",
    options: ["1", "3", "0", "2"],
    correctAnswer: "1",
    explanation:
      "% is the modulus operator: 7 % 2 = 1 (the remainder of 7÷2).",
    difficulty: "easy",
    type: "output",
    tags: ["operators", "modulus"],
  },
  {
    id: "qcs-cs5-013",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Operator Precedence",
    question: "What is the output of: print(2 + 3 * 4)?",
    options: ["14", "20", "24", "11"],
    correctAnswer: "14",
    explanation:
      "Multiplication has higher precedence than addition: 3 × 4 = 12, then 2 + 12 = 14.",
    difficulty: "easy",
    type: "output",
    tags: ["operator precedence"],
  },
  {
    id: "qcs-cs5-014",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Mutable vs Immutable",
    question: "Which of the following is a mutable data type in Python?",
    options: ["list", "tuple", "string", "int"],
    correctAnswer: "list",
    explanation:
      "Lists are mutable (their contents can be changed). Tuples, strings, and ints are immutable.",
    difficulty: "medium",
    type: "concept",
    tags: ["mutable", "data types"],
  },
  {
    id: "qcs-cs5-015",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Mutable vs Immutable",
    question: "Which of the following is an immutable data type in Python?",
    options: ["tuple", "list", "dict", "set"],
    correctAnswer: "tuple",
    explanation:
      "Tuples are immutable — once created, their elements cannot be changed.",
    difficulty: "medium",
    type: "concept",
    tags: ["immutable", "data types"],
  },
  {
    id: "qcs-cs5-016",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "String Operations",
    question: 'What is the output of: print("Hello" + "World")?',
    options: ["HelloWorld", "Hello World", "Hello+World", "Error"],
    correctAnswer: "HelloWorld",
    explanation:
      "The + operator concatenates two strings, giving 'HelloWorld' (no space).",
    difficulty: "easy",
    type: "output",
    tags: ["strings", "concatenation"],
  },
  {
    id: "qcs-cs5-017",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "String Operations",
    question: 'What is the output of: print(3 * "ab")?',
    options: ["ababab", "ab3", "ab ab ab", "Error"],
    correctAnswer: "ababab",
    explanation:
      "Multiplying a string by an integer n repeats it n times: 3 × 'ab' = 'ababab'.",
    difficulty: "easy",
    type: "output",
    tags: ["strings", "repetition"],
  },
  {
    id: "qcs-cs5-018",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Input Function",
    question: "Which function is used to take input from the user in Python?",
    options: ["input()", "read()", "get()", "scan()"],
    correctAnswer: "input()",
    explanation:
      "The input() function reads a line of input from the user as a string.",
    difficulty: "easy",
    type: "concept",
    tags: ["input", "functions"],
  },
  {
    id: "qcs-cs5-019",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Input Function",
    question: "The input() function returns data of which type?",
    options: ["str", "int", "float", "any"],
    correctAnswer: "str",
    explanation:
      "input() always returns a string, even if the user enters a number. Type conversion (e.g., int()) is needed otherwise.",
    difficulty: "medium",
    type: "concept",
    tags: ["input", "data types"],
  },
  {
    id: "qcs-cs5-020",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Type Conversion",
    question: 'Which converts the string "5" to an integer?',
    options: ['int("5")', 'str("5")', 'float("5")', 'convert("5")'],
    correctAnswer: 'int("5")',
    explanation:
      "int('5') converts the string '5' to the integer 5.",
    difficulty: "easy",
    type: "concept",
    tags: ["type conversion", "int"],
  },
  {
    id: "qcs-cs5-021",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Strings",
    question: "Which can be used as a multi-line string in Python?",
    options: [
      "triple quotes ''' or \"\"\"",
      "#",
      "//",
      "$ $",
    ],
    correctAnswer: "triple quotes ''' or \"\"\"",
    explanation:
      "Triple-quoted strings (''' or \"\"\") can span multiple lines in Python.",
    difficulty: "medium",
    type: "concept",
    tags: ["strings", "multi-line"],
  },
  {
    id: "qcs-cs5-022",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Operators",
    question: "What does the // operator do in Python?",
    options: [
      "floor division",
      "exponentiation",
      "modulus",
      "multiplication",
    ],
    correctAnswer: "floor division",
    explanation:
      "// performs floor (integer) division, returning the quotient rounded down to the nearest integer.",
    difficulty: "easy",
    type: "concept",
    tags: ["operators", "floor division"],
  },
  {
    id: "qcs-cs5-023",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Operators",
    question: "What does the ** operator do in Python?",
    options: [
      "exponentiation",
      "multiplication",
      "modulus",
      "floor division",
    ],
    correctAnswer: "exponentiation",
    explanation:
      "** is the exponentiation operator: a ** b = a raised to the power b.",
    difficulty: "easy",
    type: "concept",
    tags: ["operators", "exponentiation"],
  },
  {
    id: "qcs-cs5-024",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Operators",
    question: "What is the output of: print(10 / 2)?",
    options: ["5.0", "5", "2", "5.5"],
    correctAnswer: "5.0",
    explanation:
      "In Python 3, / always returns a float, so 10 / 2 = 5.0.",
    difficulty: "medium",
    type: "output",
    tags: ["operators", "division"],
  },
  {
    id: "qcs-cs5-025",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Functions",
    question: "Which keyword is used to define a function in Python?",
    options: ["def", "function", "func", "define"],
    correctAnswer: "def",
    explanation:
      "Functions are defined using the 'def' keyword, followed by the function name and parentheses.",
    difficulty: "easy",
    type: "concept",
    tags: ["functions", "def"],
  },
  {
    id: "qcs-cs5-026",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Python Files",
    question: "What is the file extension of a Python file?",
    options: [".py", ".python", ".p", ".pyt"],
    correctAnswer: ".py",
    explanation:
      "Python source files have the .py extension.",
    difficulty: "easy",
    type: "concept",
    tags: ["file extension", "python files"],
  },
  {
    id: "qcs-cs5-027",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Data Types",
    question: "What is the output of: print(type(3.14))?",
    options: [
      "<class 'float'>",
      "<class 'int'>",
      "<class 'str'>",
      "float",
    ],
    correctAnswer: "<class 'float'>",
    explanation:
      "3.14 is a floating-point number, so type(3.14) returns <class 'float'>.",
    difficulty: "easy",
    type: "output",
    tags: ["data types", "type()", "float"],
  },
  {
    id: "qcs-cs5-028",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Relational Operators",
    question: "Which of the following is a relational operator?",
    options: ["==", "=", "+", "//"],
    correctAnswer: "==",
    explanation:
      "== is the equality (relational) operator. = is assignment, + is addition, // is floor division.",
    difficulty: "easy",
    type: "concept",
    tags: ["operators", "relational"],
  },
  {
    id: "qcs-cs5-029",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Logical Operators",
    question: "Which of the following is a logical operator in Python?",
    options: ["and", "==", "+", "="],
    correctAnswer: "and",
    explanation:
      "'and', 'or', 'not' are the logical operators in Python.",
    difficulty: "easy",
    type: "concept",
    tags: ["operators", "logical"],
  },
  {
    id: "qcs-cs5-030",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Boolean Values",
    question: "What is the output of: print(2 == 2)?",
    options: ["True", "true", "1", "Yes"],
    correctAnswer: "True",
    explanation:
      "2 == 2 evaluates to the boolean value True (capital T).",
    difficulty: "easy",
    type: "output",
    tags: ["boolean", "relational"],
  },
  {
    id: "qcs-cs5-031",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Logical Operators",
    question: "What is the result of: True and False?",
    options: ["False", "True", "None", "Error"],
    correctAnswer: "False",
    explanation:
      "The 'and' operator returns True only if both operands are True; here one is False, so result is False.",
    difficulty: "easy",
    type: "output",
    tags: ["logical operators", "boolean"],
  },
  {
    id: "qcs-cs5-032",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Logical Operators",
    question: "What is the output of: print(not True)?",
    options: ["False", "True", "0", "Error"],
    correctAnswer: "False",
    explanation:
      "The 'not' operator negates the boolean: not True = False.",
    difficulty: "easy",
    type: "output",
    tags: ["logical operators", "not"],
  },
  {
    id: "qcs-cs5-033",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Identifiers",
    question: "Which character cannot be used in a Python identifier?",
    options: ["@", "_", "a", "9"],
    correctAnswer: "@",
    explanation:
      "Identifiers can only contain letters (a–z, A–Z), digits (0–9), and underscores (_). '@' and other special characters are not allowed.",
    difficulty: "medium",
    type: "concept",
    tags: ["identifiers", "naming rules"],
  },
  {
    id: "qcs-cs5-034",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Keywords",
    question: "Keywords in Python are:",
    options: [
      "reserved words with special meaning",
      "variable names",
      "function names",
      "comments",
    ],
    correctAnswer: "reserved words with special meaning",
    explanation:
      "Keywords are reserved words with predefined meanings (e.g., if, for, while, def) and cannot be used as identifiers.",
    difficulty: "easy",
    type: "concept",
    tags: ["keywords"],
  },
  {
    id: "qcs-cs5-035",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Print Function",
    question: 'What is the output of: print("Hello", "World")?',
    options: ["Hello World", "HelloWorld", "Hello,World", "Error"],
    correctAnswer: "Hello World",
    explanation:
      "print() separates multiple arguments with a space by default, giving 'Hello World'.",
    difficulty: "easy",
    type: "output",
    tags: ["print", "default separator"],
  },
  {
    id: "qcs-cs5-036",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Output",
    question: "Which function is used to display output in Python?",
    options: ["print()", "display()", "show()", "output()"],
    correctAnswer: "print()",
    explanation:
      "print() is the built-in function used to display output to the console.",
    difficulty: "easy",
    type: "concept",
    tags: ["print", "output"],
  },
  {
    id: "qcs-cs5-037",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Built-in Functions",
    question: "Which of these is a built-in function in Python?",
    options: ["len()", "length()", "size()", "count()"],
    correctAnswer: "len()",
    explanation:
      "len() is a built-in Python function that returns the length (number of items) of an object.",
    difficulty: "easy",
    type: "concept",
    tags: ["built-in functions", "len"],
  },
  {
    id: "qcs-cs5-038",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Built-in Functions",
    question: 'What is the output of: print(len("hello"))?',
    options: ["5", "4", "6", "Error"],
    correctAnswer: "5",
    explanation:
      '"hello" has 5 characters, so len("hello") = 5.',
    difficulty: "easy",
    type: "output",
    tags: ["built-in functions", "len", "strings"],
  },
  {
    id: "qcs-cs5-039",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Indentation",
    question: "Python uses ___ to indicate blocks of code.",
    options: [
      "indentation",
      "braces",
      "semicolons",
      "brackets",
    ],
    correctAnswer: "indentation",
    explanation:
      "Python uses indentation (whitespace) to define code blocks instead of braces or keywords like 'begin/end'.",
    difficulty: "easy",
    type: "concept",
    tags: ["indentation", "code blocks"],
  },
  {
    id: "qcs-cs5-040",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs5",
    chapter: "Introducing Python",
    topic: "Boolean Values",
    question: "Which of the following is a boolean value in Python?",
    options: ["True", "true", "TRUE", "Yes"],
    correctAnswer: "True",
    explanation:
      "Python uses 'True' and 'False' (capitalised) as boolean values. Lowercase 'true' is not valid.",
    difficulty: "easy",
    type: "concept",
    tags: ["boolean", "values"],
  },

  // ==================== FLOW OF CONTROL (cs6) — 30 questions ====================
  {
    id: "qcs-cs6-001",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "Conditional Statements",
    question: "Which statement is used for decision making in Python?",
    options: ["if", "for", "while", "def"],
    correctAnswer: "if",
    explanation:
      "The 'if' statement is used to make decisions and execute code conditionally.",
    difficulty: "easy",
    type: "concept",
    tags: ["conditional", "if"],
  },
  {
    id: "qcs-cs6-002",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "Conditional Statements",
    question: "Which keyword is used for an alternative branch in an if statement?",
    options: ["elif", "else if", "elseif", "elsif"],
    correctAnswer: "elif",
    explanation:
      "Python uses 'elif' (short for 'else if') for additional conditions after 'if'.",
    difficulty: "easy",
    type: "concept",
    tags: ["conditional", "elif"],
  },
  {
    id: "qcs-cs6-003",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "Conditional Statements",
    question:
      'What is the output?\nx = 5\nif x > 3:\n    print("A")',
    options: ["A", "B", "nothing", "error"],
    correctAnswer: "A",
    explanation:
      "Since x = 5 > 3 is True, the if block runs and prints 'A'.",
    difficulty: "easy",
    type: "output",
    tags: ["if statement", "output prediction"],
  },
  {
    id: "qcs-cs6-004",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "range() Function",
    question: "What does range(5) generate?",
    options: [
      "0, 1, 2, 3, 4",
      "1, 2, 3, 4, 5",
      "0, 1, 2, 3, 4, 5",
      "1, 2, 3, 4",
    ],
    correctAnswer: "0, 1, 2, 3, 4",
    explanation:
      "range(5) generates integers from 0 to 4 (i.e., 5 values starting from 0).",
    difficulty: "easy",
    type: "concept",
    tags: ["range", "for loops"],
  },
  {
    id: "qcs-cs6-005",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "range() Function",
    question: "What does range(1, 5) generate?",
    options: [
      "1, 2, 3, 4",
      "0, 1, 2, 3, 4",
      "1, 2, 3, 4, 5",
      "5",
    ],
    correctAnswer: "1, 2, 3, 4",
    explanation:
      "range(1, 5) generates integers from 1 up to (but not including) 5.",
    difficulty: "easy",
    type: "concept",
    tags: ["range", "for loops"],
  },
  {
    id: "qcs-cs6-006",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "range() Function",
    question: "What does range(0, 10, 2) generate?",
    options: [
      "0, 2, 4, 6, 8",
      "0, 1, 2, 3, 4, 5, 6, 7, 8, 9",
      "2, 4, 6, 8, 10",
      "0, 2, 4, 6, 8, 10",
    ],
    correctAnswer: "0, 2, 4, 6, 8",
    explanation:
      "range(0, 10, 2) starts at 0, ends before 10, stepping by 2: 0, 2, 4, 6, 8.",
    difficulty: "medium",
    type: "concept",
    tags: ["range", "step"],
  },
  {
    id: "qcs-cs6-007",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "Loops",
    question: "Which loop runs as long as a condition is true?",
    options: ["while", "for", "if", "def"],
    correctAnswer: "while",
    explanation:
      "A while loop repeatedly executes its body as long as the condition remains True.",
    difficulty: "easy",
    type: "concept",
    tags: ["while loop"],
  },
  {
    id: "qcs-cs6-008",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "Loop Control",
    question: "Which statement exits a loop immediately?",
    options: ["break", "continue", "pass", "exit"],
    correctAnswer: "break",
    explanation:
      "The 'break' statement terminates the nearest enclosing loop immediately.",
    difficulty: "easy",
    type: "concept",
    tags: ["break", "loop control"],
  },
  {
    id: "qcs-cs6-009",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "Loop Control",
    question:
      "Which statement skips the rest of the loop body and continues with the next iteration?",
    options: ["continue", "break", "pass", "skip"],
    correctAnswer: "continue",
    explanation:
      "The 'continue' statement skips the remaining statements in the current iteration and moves to the next.",
    difficulty: "easy",
    type: "concept",
    tags: ["continue", "loop control"],
  },
  {
    id: "qcs-cs6-010",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "For Loops",
    question: "What is the output of: for i in range(3): print(i)",
    options: ["0 1 2", "1 2 3", "0 1 2 3", "3"],
    correctAnswer: "0 1 2",
    explanation:
      "range(3) produces 0, 1, 2, so the loop prints 0, 1, 2 each on a new line.",
    difficulty: "easy",
    type: "output",
    tags: ["for loop", "range", "output prediction"],
  },
  {
    id: "qcs-cs6-011",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "For Loops",
    question: "What is the output of: for i in range(1, 4): print(i)",
    options: ["1 2 3", "0 1 2 3", "1 2 3 4", "0 1 2"],
    correctAnswer: "1 2 3",
    explanation:
      "range(1, 4) produces 1, 2, 3, so the loop prints 1, 2, 3 each on a new line.",
    difficulty: "easy",
    type: "output",
    tags: ["for loop", "range", "output prediction"],
  },
  {
    id: "qcs-cs6-012",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "Loops",
    question: "Which loop is typically used to run a definite number of times?",
    options: ["for", "while", "both are equal", "neither"],
    correctAnswer: "for",
    explanation:
      "The 'for' loop is used when the number of iterations is known in advance (definite iteration).",
    difficulty: "easy",
    type: "concept",
    tags: ["for loop", "definite iteration"],
  },
  {
    id: "qcs-cs6-013",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "While Loops",
    question:
      "What is the output?\ni = 0\nwhile i < 3:\n    print(i)\n    i += 1",
    options: ["0 1 2", "1 2 3", "0 1 2 3", "infinite"],
    correctAnswer: "0 1 2",
    explanation:
      "i starts at 0; the loop prints i then increments it, stopping when i = 3. So output is 0, 1, 2.",
    difficulty: "easy",
    type: "output",
    tags: ["while loop", "output prediction"],
  },
  {
    id: "qcs-cs6-014",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "break Statement",
    question:
      "What is the output?\nfor i in range(5):\n    if i == 3:\n        break\n    print(i)",
    options: ["0 1 2", "0 1 2 3", "0 1 2 3 4", "3"],
    correctAnswer: "0 1 2",
    explanation:
      "The loop prints i = 0, 1, 2; when i becomes 3, break exits the loop before printing.",
    difficulty: "medium",
    type: "output",
    tags: ["break", "for loop", "output prediction"],
  },
  {
    id: "qcs-cs6-015",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "continue Statement",
    question:
      "What is the output?\nfor i in range(5):\n    if i == 2:\n        continue\n    print(i)",
    options: ["0 1 3 4", "0 1 2 3 4", "2", "0 1 2"],
    correctAnswer: "0 1 3 4",
    explanation:
      "When i = 2, 'continue' skips printing 2 and moves to the next iteration, so output is 0, 1, 3, 4.",
    difficulty: "medium",
    type: "output",
    tags: ["continue", "for loop", "output prediction"],
  },
  {
    id: "qcs-cs6-016",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "Conditional Statements",
    question: "Which parts of an if-elif-else chain are optional?",
    options: [
      "elif and else",
      "if",
      "all parts",
      "none",
    ],
    correctAnswer: "elif and else",
    explanation:
      "Only 'if' is required. 'elif' (zero or more) and 'else' (zero or one) are optional.",
    difficulty: "medium",
    type: "concept",
    tags: ["if-elif-else"],
  },
  {
    id: "qcs-cs6-017",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "pass Statement",
    question: "The pass statement in Python:",
    options: [
      "does nothing (acts as a placeholder)",
      "breaks the loop",
      "returns a value",
      "prints a message",
    ],
    correctAnswer: "does nothing (acts as a placeholder)",
    explanation:
      "'pass' is a null operation — it does nothing and is used as a placeholder where syntax requires a statement.",
    difficulty: "medium",
    type: "concept",
    tags: ["pass", "loop control"],
  },
  {
    id: "qcs-cs6-018",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "if-else",
    question:
      'What is the output?\nx = 10\nif x > 5:\n    print("A")\nelse:\n    print("B")',
    options: ["A", "B", "AB", "error"],
    correctAnswer: "A",
    explanation:
      "Since x = 10 > 5 is True, the if branch runs and prints 'A'.",
    difficulty: "easy",
    type: "output",
    tags: ["if-else", "output prediction"],
  },
  {
    id: "qcs-cs6-019",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "range() Function",
    question: "What does range(10, 0, -2) generate?",
    options: [
      "10, 8, 6, 4, 2",
      "10, 8, 6, 4, 2, 0",
      "0, 2, 4, 6, 8, 10",
      "10, 8, 6, 4, 2, -1",
    ],
    correctAnswer: "10, 8, 6, 4, 2",
    explanation:
      "range(10, 0, -2) starts at 10, steps down by 2, stopping before 0: 10, 8, 6, 4, 2.",
    difficulty: "medium",
    type: "concept",
    tags: ["range", "negative step"],
  },
  {
    id: "qcs-cs6-020",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "Nested if",
    question: "A 'nested if' refers to:",
    options: [
      "an if statement inside another if",
      "an if inside a for",
      "a for inside an if",
      "two separate if statements",
    ],
    correctAnswer: "an if statement inside another if",
    explanation:
      "A nested if is an if statement placed inside the block of another if (or else) statement.",
    difficulty: "medium",
    type: "concept",
    tags: ["nested if"],
  },
  {
    id: "qcs-cs6-021",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "if-elif",
    question:
      'What is the output?\nx = 5\nif x == 5:\n    print("Five")\nelif x == 6:\n    print("Six")',
    options: ["Five", "Six", "FiveSix", "error"],
    correctAnswer: "Five",
    explanation:
      "x = 5 matches the first condition, so 'Five' is printed; the elif is not checked.",
    difficulty: "easy",
    type: "output",
    tags: ["if-elif", "output prediction"],
  },
  {
    id: "qcs-cs6-022",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "Infinite Loops",
    question: "An infinite loop occurs when:",
    options: [
      "the loop condition never becomes false",
      "the condition is initially false",
      "there is no loop",
      "the range is empty",
    ],
    correctAnswer: "the loop condition never becomes false",
    explanation:
      "If the loop condition never evaluates to False, the loop runs forever — an infinite loop.",
    difficulty: "medium",
    type: "concept",
    tags: ["infinite loops", "while loop"],
  },
  {
    id: "qcs-cs6-023",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "While Loops",
    question:
      "What is the output?\nx = 0\nwhile x < 5:\n    x += 1\nprint(x)",
    options: ["5", "0", "4", "6"],
    correctAnswer: "5",
    explanation:
      "x increases from 0 to 5; when x = 5, the condition x < 5 becomes False, so the loop stops and prints 5.",
    difficulty: "medium",
    type: "output",
    tags: ["while loop", "output prediction"],
  },
  {
    id: "qcs-cs6-024",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "Indentation",
    question: "In Python, indentation indicates:",
    options: [
      "a block of code",
      "end of a statement",
      "a comment",
      "a variable declaration",
    ],
    correctAnswer: "a block of code",
    explanation:
      "Indentation (consistent whitespace) groups statements into blocks in Python.",
    difficulty: "easy",
    type: "concept",
    tags: ["indentation", "code blocks"],
  },
  {
    id: "qcs-cs6-025",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "For Loops",
    question: "Which loop is best for iterating over a sequence (like a list or string)?",
    options: ["for", "while", "if", "def"],
    correctAnswer: "for",
    explanation:
      "The 'for' loop is designed to iterate directly over items of a sequence.",
    difficulty: "easy",
    type: "concept",
    tags: ["for loop", "iteration"],
  },
  {
    id: "qcs-cs6-026",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "Nested Loops",
    question:
      "How many lines are printed by:\nfor i in range(2):\n    for j in range(2):\n        print(i, j)",
    options: ["4", "2", "3", "1"],
    correctAnswer: "4",
    explanation:
      "Outer loop runs 2 times, inner loop runs 2 times each → 2 × 2 = 4 lines printed.",
    difficulty: "medium",
    type: "numerical",
    tags: ["nested loops", "counting"],
  },
  {
    id: "qcs-cs6-027",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "for-else",
    question: "The else clause of a for loop executes when:",
    options: [
      "the loop completes without a break",
      "the loop hits a break",
      "never",
      "always",
    ],
    correctAnswer: "the loop completes without a break",
    explanation:
      "A for-else's else block runs only if the loop finishes normally (i.e., without hitting a break).",
    difficulty: "hard",
    type: "concept",
    tags: ["for-else", "else clause"],
  },
  {
    id: "qcs-cs6-028",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "pass Statement",
    question:
      'What is the output?\nfor i in range(3):\n    pass\nprint("Done")',
    options: ["Done", "0 1 2", "error", "nothing"],
    correctAnswer: "Done",
    explanation:
      "'pass' does nothing, so the loop runs without effect and then 'Done' is printed.",
    difficulty: "medium",
    type: "output",
    tags: ["pass", "for loop", "output prediction"],
  },
  {
    id: "qcs-cs6-029",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "While Loops",
    question: "The condition in a while loop is checked:",
    options: [
      "before each iteration",
      "after each iteration",
      "only once",
      "never",
    ],
    correctAnswer: "before each iteration",
    explanation:
      "A while loop tests its condition before each iteration; if False, the loop body is skipped.",
    difficulty: "easy",
    type: "concept",
    tags: ["while loop", "condition"],
  },
  {
    id: "qcs-cs6-030",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs6",
    chapter: "Flow of Control",
    topic: "While Loops",
    question:
      "What is the output?\nn = 0\nwhile n < 3:\n    print(n)\n    n = n + 1",
    options: ["0 1 2", "1 2 3", "0 1 2 3", "infinite"],
    correctAnswer: "0 1 2",
    explanation:
      "n starts at 0 and is printed, then incremented. Loop stops when n = 3, so output is 0, 1, 2.",
    difficulty: "easy",
    type: "output",
    tags: ["while loop", "output prediction"],
  },

  // ==================== DATA HANDLING (cs7) — 40 questions ====================
  {
    id: "qcs-cs7-001",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Lists",
    question: "Lists in Python are enclosed in:",
    options: ["[]", "()", "{}", '""'],
    correctAnswer: "[]",
    explanation:
      "Lists are created using square brackets, e.g., [1, 2, 3].",
    difficulty: "easy",
    type: "concept",
    tags: ["lists", "syntax"],
  },
  {
    id: "qcs-cs7-002",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Tuples",
    question: "Tuples in Python are enclosed in:",
    options: ["()", "[]", "{}", '""'],
    correctAnswer: "()",
    explanation:
      "Tuples are created using parentheses, e.g., (1, 2, 3).",
    difficulty: "easy",
    type: "concept",
    tags: ["tuples", "syntax"],
  },
  {
    id: "qcs-cs7-003",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Dictionaries",
    question: "Dictionaries in Python are enclosed in:",
    options: ["{}", "[]", "()", '""'],
    correctAnswer: "{}",
    explanation:
      "Dictionaries use curly braces with key-value pairs, e.g., {'a': 1}.",
    difficulty: "easy",
    type: "concept",
    tags: ["dictionaries", "syntax"],
  },
  {
    id: "qcs-cs7-004",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Strings",
    question: "Strings in Python are enclosed in:",
    options: [
      "single or double quotes",
      "[]",
      "()",
      "{}",
    ],
    correctAnswer: "single or double quotes",
    explanation:
      "Strings can be written with either single ('...') or double (\"...\") quotes.",
    difficulty: "easy",
    type: "concept",
    tags: ["strings", "syntax"],
  },
  {
    id: "qcs-cs7-005",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "List Indexing",
    question: "What is the output of: print([1, 2, 3][1])?",
    options: ["2", "1", "3", "error"],
    correctAnswer: "2",
    explanation:
      "List indices start at 0, so index 1 of [1, 2, 3] is 2.",
    difficulty: "easy",
    type: "output",
    tags: ["lists", "indexing"],
  },
  {
    id: "qcs-cs7-006",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "String Indexing",
    question: 'What is the output of: print("hello"[0])?',
    options: ["h", "e", "0", "hello"],
    correctAnswer: "h",
    explanation:
      "Strings are indexed from 0, so 'hello'[0] is 'h'.",
    difficulty: "easy",
    type: "output",
    tags: ["strings", "indexing"],
  },
  {
    id: "qcs-cs7-007",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "len() Function",
    question: "What is the output of: print(len([1, 2, 3, 4]))?",
    options: ["4", "3", "5", "error"],
    correctAnswer: "4",
    explanation:
      "len() returns the number of items; the list has 4 elements.",
    difficulty: "easy",
    type: "output",
    tags: ["len", "lists"],
  },
  {
    id: "qcs-cs7-008",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Operators",
    question: "What is the output of: print(5 // 2)?",
    options: ["2", "2.5", "3", "1"],
    correctAnswer: "2",
    explanation:
      "// is floor division: 5 // 2 = 2 (the integer quotient, truncated down).",
    difficulty: "easy",
    type: "output",
    tags: ["operators", "floor division"],
  },
  {
    id: "qcs-cs7-009",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Operators",
    question: "What is the output of: print(5 % 2)?",
    options: ["1", "2", "0", "2.5"],
    correctAnswer: "1",
    explanation:
      "% is the modulus operator returning the remainder: 5 % 2 = 1.",
    difficulty: "easy",
    type: "output",
    tags: ["operators", "modulus"],
  },
  {
    id: "qcs-cs7-010",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Operators",
    question: "What is the output of: print(2 ** 3 ** 2)?",
    options: ["512", "64", "81", "12"],
    correctAnswer: "512",
    explanation:
      "** is right-associative: 3 ** 2 = 9 first, then 2 ** 9 = 512.",
    difficulty: "hard",
    type: "output",
    tags: ["operators", "exponentiation", "associativity"],
  },
  {
    id: "qcs-cs7-011",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "String Operations",
    question: 'What is the output of: print("abc" * 2)?',
    options: ["abcabc", "abc2", "abc abc", "error"],
    correctAnswer: "abcabc",
    explanation:
      "Multiplying a string by an integer repeats it: 'abc' * 2 = 'abcabc'.",
    difficulty: "easy",
    type: "output",
    tags: ["strings", "repetition"],
  },
  {
    id: "qcs-cs7-012",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "List Operations",
    question: "What is the output of: print([1, 2] + [3, 4])?",
    options: [
      "[1, 2, 3, 4]",
      "[1, 2][3, 4]",
      "error",
      "10",
    ],
    correctAnswer: "[1, 2, 3, 4]",
    explanation:
      "The + operator concatenates two lists, giving [1, 2, 3, 4].",
    difficulty: "easy",
    type: "output",
    tags: ["lists", "concatenation"],
  },
  {
    id: "qcs-cs7-013",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Mutable vs Immutable",
    question: "Which of the following is mutable in Python?",
    options: ["list", "tuple", "string", "int"],
    correctAnswer: "list",
    explanation:
      "Lists are mutable (can be changed after creation). Tuples, strings, and ints are immutable.",
    difficulty: "medium",
    type: "concept",
    tags: ["mutable", "data types"],
  },
  {
    id: "qcs-cs7-014",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Tuple Indexing",
    question: "What is the output of: print((1, 2, 3)[1])?",
    options: ["2", "1", "3", "error"],
    correctAnswer: "2",
    explanation:
      "Tuple indices start at 0, so (1, 2, 3)[1] is 2.",
    difficulty: "easy",
    type: "output",
    tags: ["tuples", "indexing"],
  },
  {
    id: "qcs-cs7-015",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Dictionaries",
    question: 'What is the output of: print({"a": 1}["a"])?',
    options: ["1", "a", "error", '{"a": 1}'],
    correctAnswer: "1",
    explanation:
      "Dictionary access by key: dict['a'] returns the value 1.",
    difficulty: "easy",
    type: "output",
    tags: ["dictionaries", "key access"],
  },
  {
    id: "qcs-cs7-016",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "List Methods",
    question: "Which method adds an element to the end of a list?",
    options: ["append()", "add()", "insert()", "push()"],
    correctAnswer: "append()",
    explanation:
      "list.append(x) adds element x to the end of the list.",
    difficulty: "easy",
    type: "concept",
    tags: ["list methods", "append"],
  },
  {
    id: "qcs-cs7-017",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "String Slicing",
    question: 'What is the output of: print("Hello"[1:4])?',
    options: ["ell", "ello", "Hel", "ell + o"],
    correctAnswer: "ell",
    explanation:
      "Slicing [1:4] gives characters at indices 1, 2, 3 → 'ell'.",
    difficulty: "medium",
    type: "output",
    tags: ["strings", "slicing"],
  },
  {
    id: "qcs-cs7-018",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Negative Indexing",
    question: 'What is the output of: print("Python"[-1])?',
    options: ["n", "P", "h", "error"],
    correctAnswer: "n",
    explanation:
      "Negative indices count from the end; -1 is the last character, 'n'.",
    difficulty: "easy",
    type: "output",
    tags: ["strings", "negative indexing"],
  },
  {
    id: "qcs-cs7-019",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "List Slicing",
    question: "What is the output of: print([1, 2, 3, 4][1:3])?",
    options: ["[2, 3]", "[1, 2]", "[3, 4]", "[1, 2, 3]"],
    correctAnswer: "[2, 3]",
    explanation:
      "Slicing [1:3] gives elements at indices 1 and 2 → [2, 3].",
    difficulty: "medium",
    type: "output",
    tags: ["lists", "slicing"],
  },
  {
    id: "qcs-cs7-020",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Built-in Functions",
    question: "Which function returns the length of a string in Python?",
    options: ["len()", "length()", "size()", "count()"],
    correctAnswer: "len()",
    explanation:
      "len() is the built-in function used to get the length of strings (and other sequences).",
    difficulty: "easy",
    type: "concept",
    tags: ["built-in functions", "len"],
  },
  {
    id: "qcs-cs7-021",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "String Methods",
    question: 'What is the output of: print("hello".upper())?',
    options: ["HELLO", "hello", "Hello", "error"],
    correctAnswer: "HELLO",
    explanation:
      "The .upper() method returns a copy of the string in uppercase.",
    difficulty: "easy",
    type: "output",
    tags: ["string methods", "upper"],
  },
  {
    id: "qcs-cs7-022",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "String Methods",
    question: 'What is the output of: print("HELLO".lower())?',
    options: ["hello", "HELLO", "Hello", "error"],
    correctAnswer: "hello",
    explanation:
      "The .lower() method returns a copy of the string in lowercase.",
    difficulty: "easy",
    type: "output",
    tags: ["string methods", "lower"],
  },
  {
    id: "qcs-cs7-023",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "String Methods",
    question: 'What is the output of: print("a,b,c".split(","))?',
    options: ["['a', 'b', 'c']", "abc", "error", "'a b c'"],
    correctAnswer: "['a', 'b', 'c']",
    explanation:
      ".split(',') splits the string at each comma, returning a list of substrings.",
    difficulty: "medium",
    type: "output",
    tags: ["string methods", "split"],
  },
  {
    id: "qcs-cs7-024",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "List Methods",
    question: "Which method removes the last element from a list?",
    options: ["pop()", "remove()", "delete()", "drop()"],
    correctAnswer: "pop()",
    explanation:
      "list.pop() removes and returns the last element of the list (by default).",
    difficulty: "medium",
    type: "concept",
    tags: ["list methods", "pop"],
  },
  {
    id: "qcs-cs7-025",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "String Methods",
    question:
      'What is the output of: print("hello world".replace("world", "python"))?',
    options: [
      "hello python",
      "hello world",
      "error",
      "hello",
    ],
    correctAnswer: "hello python",
    explanation:
      ".replace(old, new) returns a new string with all occurrences of 'old' replaced by 'new'.",
    difficulty: "medium",
    type: "output",
    tags: ["string methods", "replace"],
  },
  {
    id: "qcs-cs7-026",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "String Methods",
    question: 'What is the output of: print("  hi  ".strip())?',
    options: ["hi", "  hi  ", " hi ", "error"],
    correctAnswer: "hi",
    explanation:
      ".strip() removes leading and trailing whitespace, giving 'hi'.",
    difficulty: "medium",
    type: "output",
    tags: ["string methods", "strip"],
  },
  {
    id: "qcs-cs7-027",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Comparison",
    question: 'What is the output of: print("abc" == "abc")?',
    options: ["True", "False", "1", "error"],
    correctAnswer: "True",
    explanation:
      "The two strings are identical, so the == comparison returns True.",
    difficulty: "easy",
    type: "output",
    tags: ["comparison", "strings"],
  },
  {
    id: "qcs-cs7-028",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "in Operator",
    question: "What is the output of: print(3 in [1, 2, 3])?",
    options: ["True", "False", "3", "error"],
    correctAnswer: "True",
    explanation:
      "The 'in' operator checks membership; 3 is in [1, 2, 3], so it returns True.",
    difficulty: "easy",
    type: "output",
    tags: ["in operator", "membership", "lists"],
  },
  {
    id: "qcs-cs7-029",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "in Operator",
    question: 'What is the output of: print("a" in "cat")?',
    options: ["True", "False", "a", "error"],
    correctAnswer: "True",
    explanation:
      "'a' is found in 'cat', so the 'in' operator returns True.",
    difficulty: "easy",
    type: "output",
    tags: ["in operator", "membership", "strings"],
  },
  {
    id: "qcs-cs7-030",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "List Methods",
    question:
      "What is the output?\nx = [1, 2, 3]\nx.reverse()\nprint(x)",
    options: ["[3, 2, 1]", "[1, 2, 3]", "None", "error"],
    correctAnswer: "[3, 2, 1]",
    explanation:
      "list.reverse() reverses the list in place (returns None); printing x now shows [3, 2, 1].",
    difficulty: "medium",
    type: "output",
    tags: ["list methods", "reverse"],
  },
  {
    id: "qcs-cs7-031",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Built-in Functions",
    question: "What is the output of: print(sorted([3, 1, 2]))?",
    options: ["[1, 2, 3]", "[3, 2, 1]", "[3, 1, 2]", "None"],
    correctAnswer: "[1, 2, 3]",
    explanation:
      "sorted() returns a new list with elements in ascending order: [1, 2, 3].",
    difficulty: "easy",
    type: "output",
    tags: ["built-in functions", "sorted"],
  },
  {
    id: "qcs-cs7-032",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Built-in Functions",
    question: "What is the output of: print(max([3, 1, 2]))?",
    options: ["3", "1", "2", "error"],
    correctAnswer: "3",
    explanation:
      "max() returns the largest element of the iterable; here it's 3.",
    difficulty: "easy",
    type: "output",
    tags: ["built-in functions", "max"],
  },
  {
    id: "qcs-cs7-033",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Built-in Functions",
    question: "What is the output of: print(min([3, 1, 2]))?",
    options: ["1", "3", "2", "error"],
    correctAnswer: "1",
    explanation:
      "min() returns the smallest element of the iterable; here it's 1.",
    difficulty: "easy",
    type: "output",
    tags: ["built-in functions", "min"],
  },
  {
    id: "qcs-cs7-034",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Built-in Functions",
    question: "What is the output of: print(sum([1, 2, 3]))?",
    options: ["6", "3", "123", "error"],
    correctAnswer: "6",
    explanation:
      "sum() returns the total of all elements: 1 + 2 + 3 = 6.",
    difficulty: "easy",
    type: "output",
    tags: ["built-in functions", "sum"],
  },
  {
    id: "qcs-cs7-035",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Type Conversion",
    question: 'What is the output of: print(list("abc"))?',
    options: ["['a', 'b', 'c']", "abc", "error", "['abc']"],
    correctAnswer: "['a', 'b', 'c']",
    explanation:
      "list() converts an iterable into a list; each character becomes a separate element.",
    difficulty: "medium",
    type: "output",
    tags: ["type conversion", "list"],
  },
  {
    id: "qcs-cs7-036",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Dictionaries",
    question: "Which of the following creates an empty dictionary?",
    options: ["{}", "[]", "()", '""'],
    correctAnswer: "{}",
    explanation:
      "Empty curly braces {} create an empty dictionary (not an empty set).",
    difficulty: "easy",
    type: "concept",
    tags: ["dictionaries", "empty"],
  },
  {
    id: "qcs-cs7-037",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Dictionaries",
    question: "What is the output of: print(len({1: 2, 3: 4}))?",
    options: ["2", "4", "1", "error"],
    correctAnswer: "2",
    explanation:
      "len() on a dictionary returns the number of key-value pairs; here there are 2.",
    difficulty: "medium",
    type: "output",
    tags: ["dictionaries", "len"],
  },
  {
    id: "qcs-cs7-038",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "String Slicing",
    question: 'What is the output of: print("Hello"[::2])?',
    options: ["Hlo", "ello", "Helo", "Hlo"],
    correctAnswer: "Hlo",
    explanation:
      "[::2] takes every 2nd character starting from index 0: H, l, o → 'Hlo'.",
    difficulty: "hard",
    type: "output",
    tags: ["strings", "slicing", "step"],
  },
  {
    id: "qcs-cs7-039",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "Type Checking",
    question: "What is the output of: print(type(()))?",
    options: [
      "<class 'tuple'>",
      "<class 'list'>",
      "<class 'dict'>",
      "<class 'set'>",
    ],
    correctAnswer: "<class 'tuple'>",
    explanation:
      "An empty pair of parentheses () creates a tuple, so its type is <class 'tuple'>.",
    difficulty: "medium",
    type: "output",
    tags: ["type()", "tuples"],
  },
  {
    id: "qcs-cs7-040",
    subject: "cs",
    subjectName: "Computer Science",
    chapterId: "cs7",
    chapter: "Data Handling",
    topic: "List Repetition",
    question: "What is the output of: print([1, 2, 3] * 2)?",
    options: [
      "[1, 2, 3, 1, 2, 3]",
      "[2, 4, 6]",
      "[1, 2, 3, 2]",
      "error",
    ],
    correctAnswer: "[1, 2, 3, 1, 2, 3]",
    explanation:
      "Multiplying a list by an integer n repeats the list n times, giving [1, 2, 3, 1, 2, 3].",
    difficulty: "medium",
    type: "output",
    tags: ["lists", "repetition"],
  },
];
