import type { QuizMCQ } from "./quizzes-physics";

export const CHEMISTRY_QUIZZES: QuizMCQ[] = [
  // ==================== SOME BASIC CONCEPTS OF CHEMISTRY (c1) — 40 questions ====================
  {
    id: "qchem-c1-001",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Avogadro's Number",
    question: "The number of atoms in 1 mole of a substance is:",
    options: ["6.022 × 10²³", "6.022 × 10²²", "3.011 × 10²³", "1.2 × 10²⁴"],
    correctAnswer: "6.022 × 10²³",
    explanation:
      "Avogadro's number is 6.022 × 10²³, the number of particles (atoms/molecules) in one mole of a substance.",
    difficulty: "easy",
    type: "formula",
    tags: ["Avogadro's number", "mole concept"],
  },
  {
    id: "qchem-c1-002",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Avogadro's Number",
    question: "The value of Avogadro's number is:",
    options: ["6.022 × 10²³", "6.022 × 10²²", "9.1 × 10⁻³¹", "1.6 × 10⁻¹⁹"],
    correctAnswer: "6.022 × 10²³",
    explanation:
      "Avogadro's number = 6.022 × 10²³ per mole.",
    difficulty: "easy",
    type: "formula",
    tags: ["Avogadro's number"],
  },
  {
    id: "qchem-c1-003",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Molar Mass",
    question: "The molar mass of water (H₂O) is:",
    options: ["18 g/mol", "16 g/mol", "20 g/mol", "17 g/mol"],
    correctAnswer: "18 g/mol",
    explanation: "Molar mass = 2(1) + 16 = 18 g/mol.",
    difficulty: "easy",
    type: "numerical",
    tags: ["molar mass", "water"],
  },
  {
    id: "qchem-c1-004",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept",
    question: "The number of moles in 36 g of water is:",
    options: ["1", "2", "0.5", "18"],
    correctAnswer: "2",
    explanation: "Moles = mass/molar mass = 36/18 = 2 mol.",
    difficulty: "easy",
    type: "numerical",
    tags: ["mole concept", "water"],
  },
  {
    id: "qchem-c1-005",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Molar Mass",
    question: "The mass of 1 mole of CO₂ is:",
    options: ["28 g", "44 g", "32 g", "22 g"],
    correctAnswer: "44 g",
    explanation: "Molar mass of CO₂ = 12 + 2(16) = 44 g/mol.",
    difficulty: "easy",
    type: "numerical",
    tags: ["molar mass", "CO₂"],
  },
  {
    id: "qchem-c1-006",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept",
    question: "The number of atoms in 11 g of CO₂ is:",
    options: ["1.5 × 10²³", "3 × 10²³", "6 × 10²³", "4.5 × 10²³"],
    correctAnswer: "4.5 × 10²³",
    explanation:
      "11 g CO₂ = 11/44 = 0.25 mol. Each CO₂ has 3 atoms. Total atoms = 0.25 × 3 × 6.022 × 10²³ ≈ 4.5 × 10²³.",
    difficulty: "hard",
    type: "numerical",
    tags: ["mole concept", "atoms", "Avogadro's number"],
  },
  {
    id: "qchem-c1-007",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Empirical Formula",
    question: "The empirical formula of glucose (C₆H₁₂O₆) is:",
    options: ["CH₂O", "C₂H₄O₂", "CHO", "C₆H₁₂O₆"],
    correctAnswer: "CH₂O",
    explanation:
      "Dividing subscripts by the GCD (6) gives CH₂O, the empirical formula of glucose.",
    difficulty: "medium",
    type: "concept",
    tags: ["empirical formula", "glucose"],
  },
  {
    id: "qchem-c1-008",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Percentage Composition",
    question: "The percentage of oxygen in water (H₂O) is:",
    options: ["11.11%", "88.89%", "50%", "66.67%"],
    correctAnswer: "88.89%",
    explanation:
      "%O = (16/18) × 100 ≈ 88.89%.",
    difficulty: "medium",
    type: "numerical",
    tags: ["percentage composition", "water"],
  },
  {
    id: "qchem-c1-009",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept",
    question: "The number of molecules in 0.5 mole of O₂ is:",
    options: [
      "3.011 × 10²³",
      "6.022 × 10²³",
      "1.5 × 10²³",
      "12 × 10²³",
    ],
    correctAnswer: "3.011 × 10²³",
    explanation:
      "0.5 × 6.022 × 10²³ = 3.011 × 10²³ molecules.",
    difficulty: "easy",
    type: "numerical",
    tags: ["mole concept", "Avogadro's number"],
  },
  {
    id: "qchem-c1-010",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Molarity",
    question: "Molarity is defined as:",
    options: [
      "moles of solute per litre of solution",
      "grams of solute per litre",
      "moles per kg of solvent",
      "moles per mL",
    ],
    correctAnswer: "moles of solute per litre of solution",
    explanation:
      "Molarity (M) = moles of solute / volume of solution in litres.",
    difficulty: "easy",
    type: "formula",
    tags: ["molarity", "concentration"],
  },
  {
    id: "qchem-c1-011",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Laws of Chemical Combination",
    question: "The law of conservation of mass was proposed by:",
    options: ["Lavoisier", "Dalton", "Proust", "Avogadro"],
    correctAnswer: "Lavoisier",
    explanation:
      "Lavoisier proposed that mass is neither created nor destroyed in a chemical reaction.",
    difficulty: "easy",
    type: "concept",
    tags: ["laws of chemical combination", "Lavoisier"],
  },
  {
    id: "qchem-c1-012",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Laws of Chemical Combination",
    question: "The law of definite proportions was given by:",
    options: ["Lavoisier", "Proust", "Dalton", "Gay-Lussac"],
    correctAnswer: "Proust",
    explanation:
      "Proust's law of definite proportions states that a compound always contains the same elements in a fixed ratio by mass.",
    difficulty: "easy",
    type: "concept",
    tags: ["laws of chemical combination", "Proust"],
  },
  {
    id: "qchem-c1-013",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Atomic Mass",
    question: "The atomic mass of carbon is:",
    options: ["6", "12", "14", "16"],
    correctAnswer: "12",
    explanation:
      "Carbon-12 is the standard; its atomic mass is exactly 12 u.",
    difficulty: "easy",
    type: "concept",
    tags: ["atomic mass", "carbon"],
  },
  {
    id: "qchem-c1-014",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept",
    question: "The number of moles in 22 g of CO₂ is:",
    options: ["0.5", "1", "2", "0.25"],
    correctAnswer: "0.5",
    explanation: "Moles = 22/44 = 0.5 mol.",
    difficulty: "easy",
    type: "numerical",
    tags: ["mole concept", "CO₂"],
  },
  {
    id: "qchem-c1-015",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept",
    question: "The mass of 0.5 mole of Na (Na = 23) is:",
    options: ["11.5 g", "23 g", "46 g", "5.75 g"],
    correctAnswer: "11.5 g",
    explanation: "Mass = moles × molar mass = 0.5 × 23 = 11.5 g.",
    difficulty: "easy",
    type: "numerical",
    tags: ["mole concept", "sodium"],
  },
  {
    id: "qchem-c1-016",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept",
    question:
      "Which of the following has the maximum number of atoms? (1 g each of H, O, N, C)",
    options: ["H", "O", "N", "C"],
    correctAnswer: "H",
    explanation:
      "Number of atoms = mass/molar mass × Nₐ. Lower molar mass means more moles. H (1 g/mol) gives the most atoms.",
    difficulty: "medium",
    type: "numerical",
    tags: ["mole concept", "atoms"],
  },
  {
    id: "qchem-c1-017",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept",
    question: "The number of atoms in 4 g of He (He = 4) is:",
    options: [
      "6.022 × 10²³",
      "3.011 × 10²³",
      "1.2 × 10²⁴",
      "6.022 × 10²²",
    ],
    correctAnswer: "6.022 × 10²³",
    explanation:
      "4 g He = 1 mol. He is monatomic, so atoms = 1 × 6.022 × 10²³ = 6.022 × 10²³.",
    difficulty: "medium",
    type: "numerical",
    tags: ["mole concept", "helium", "atoms"],
  },
  {
    id: "qchem-c1-018",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Empirical Formula",
    question: "The empirical formula of benzene (C₆H₆) is:",
    options: ["CH", "C₂H₂", "C₆H₆", "C₃H₃"],
    correctAnswer: "CH",
    explanation:
      "Dividing subscripts by 6 gives CH as the empirical formula of benzene.",
    difficulty: "medium",
    type: "concept",
    tags: ["empirical formula", "benzene"],
  },
  {
    id: "qchem-c1-019",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Molar Mass",
    question: "The molar mass of NaCl is:",
    options: ["23", "35.5", "58.5", "11.5"],
    correctAnswer: "58.5",
    explanation: "Molar mass of NaCl = 23 + 35.5 = 58.5 g/mol.",
    difficulty: "easy",
    type: "numerical",
    tags: ["molar mass", "NaCl"],
  },
  {
    id: "qchem-c1-020",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept",
    question: "The number of molecules in 8 g of O₂ is:",
    options: [
      "1.5 × 10²³",
      "3 × 10²³",
      "6 × 10²³",
      "0.5 × 10²³",
    ],
    correctAnswer: "1.5 × 10²³",
    explanation:
      "8 g O₂ = 8/32 = 0.25 mol. Molecules = 0.25 × 6.022 × 10²³ ≈ 1.5 × 10²³.",
    difficulty: "medium",
    type: "numerical",
    tags: ["mole concept", "oxygen"],
  },
  {
    id: "qchem-c1-021",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Laws of Chemical Combination",
    question: "Gay-Lussac's law of gaseous volumes relates to:",
    options: [
      "volumes of gases in reactions",
      "masses of reactants",
      "temperature only",
      "pressure only",
    ],
    correctAnswer: "volumes of gases in reactions",
    explanation:
      "Gay-Lussac's law states that gases react in simple whole-number ratios by volume at the same T and P.",
    difficulty: "medium",
    type: "concept",
    tags: ["laws of chemical combination", "Gay-Lussac"],
  },
  {
    id: "qchem-c1-022",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Avogadro's Law",
    question:
      "Avogadro's law states that equal volumes of gases at the same T and P have:",
    options: [
      "equal mass",
      "equal number of molecules",
      "equal density",
      "equal atoms",
    ],
    correctAnswer: "equal number of molecules",
    explanation:
      "Avogadro's law: equal volumes of all gases under identical conditions contain equal numbers of molecules.",
    difficulty: "medium",
    type: "concept",
    tags: ["Avogadro's law"],
  },
  {
    id: "qchem-c1-023",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Limiting Reagent",
    question: "The limiting reagent in a reaction is the one that:",
    options: [
      "is in excess",
      "is completely consumed first",
      "is a catalyst",
      "has the highest molar mass",
    ],
    correctAnswer: "is completely consumed first",
    explanation:
      "The limiting reagent is the reactant that is completely consumed first, limiting the amount of product formed.",
    difficulty: "medium",
    type: "concept",
    tags: ["limiting reagent", "stoichiometry"],
  },
  {
    id: "qchem-c1-024",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Molar Volume",
    question: "The volume occupied by 1 mole of an ideal gas at STP is:",
    options: ["22.4 L", "11.2 L", "2.24 L", "24.4 L"],
    correctAnswer: "22.4 L",
    explanation:
      "At STP (0 °C, 1 atm), 1 mole of any ideal gas occupies 22.4 L (molar volume).",
    difficulty: "easy",
    type: "formula",
    tags: ["molar volume", "STP"],
  },
  {
    id: "qchem-c1-025",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Molar Volume",
    question: "The number of moles in 5.6 L of a gas at STP is:",
    options: ["0.25", "0.5", "1", "0.125"],
    correctAnswer: "0.25",
    explanation: "Moles = volume/22.4 = 5.6/22.4 = 0.25 mol.",
    difficulty: "medium",
    type: "numerical",
    tags: ["molar volume", "STP"],
  },
  {
    id: "qchem-c1-026",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Percentage Composition",
    question: "The percentage of hydrogen in water (H₂O) is:",
    options: ["11.11%", "88.89%", "5.56%", "22.22%"],
    correctAnswer: "11.11%",
    explanation: "%H = (2/18) × 100 ≈ 11.11%.",
    difficulty: "medium",
    type: "numerical",
    tags: ["percentage composition", "water"],
  },
  {
    id: "qchem-c1-027",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Molar Mass",
    question: "The molar mass of H₂SO₄ is:",
    options: ["49", "98", "96", "100"],
    correctAnswer: "98",
    explanation: "Molar mass of H₂SO₄ = 2(1) + 32 + 4(16) = 98 g/mol.",
    difficulty: "easy",
    type: "numerical",
    tags: ["molar mass", "H₂SO₄"],
  },
  {
    id: "qchem-c1-028",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept",
    question:
      "The number of oxygen atoms in 1 mole of CO₂ is:",
    options: ["1", "2", "6.022 × 10²³", "1.2 × 10²⁴"],
    correctAnswer: "1.2 × 10²⁴",
    explanation:
      "1 mol CO₂ contains 2 mol O atoms = 2 × 6.022 × 10²³ ≈ 1.2 × 10²⁴ oxygen atoms.",
    difficulty: "medium",
    type: "numerical",
    tags: ["mole concept", "atoms", "Avogadro's number"],
  },
  {
    id: "qchem-c1-029",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Atomic Mass Unit",
    question: "1 amu is defined as:",
    options: [
      "1/12 the mass of a carbon-12 atom",
      "mass of a hydrogen atom",
      "mass of a proton",
      "1 gram",
    ],
    correctAnswer: "1/12 the mass of a carbon-12 atom",
    explanation:
      "1 atomic mass unit (amu or u) = 1/12 of the mass of a carbon-12 atom ≈ 1.66 × 10⁻²⁴ g.",
    difficulty: "medium",
    type: "concept",
    tags: ["amu", "atomic mass unit", "carbon-12"],
  },
  {
    id: "qchem-c1-030",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Empirical Formula",
    question:
      "A compound contains 40% C, 6.67% H, 53.33% O. Its empirical formula is:",
    options: ["CH₂O", "C₂H₄O₂", "CHO", "CH₄O"],
    correctAnswer: "CH₂O",
    explanation:
      "Moles: C = 40/12 = 3.33, H = 6.67/1 = 6.67, O = 53.33/16 = 3.33. Ratio 1:2:1, giving CH₂O.",
    difficulty: "hard",
    type: "numerical",
    tags: ["empirical formula", "percentage composition"],
  },
  {
    id: "qchem-c1-031",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Molar Mass",
    question: "The molecular mass of ethane (C₂H₆) is:",
    options: ["28", "30", "32", "14"],
    correctAnswer: "30",
    explanation: "Molecular mass of C₂H₆ = 2(12) + 6(1) = 30 u.",
    difficulty: "easy",
    type: "numerical",
    tags: ["molar mass", "ethane"],
  },
  {
    id: "qchem-c1-032",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept",
    question: "The number of moles in 9.8 g of H₂SO₄ is:",
    options: ["0.1", "0.5", "1", "0.2"],
    correctAnswer: "0.1",
    explanation: "Moles = 9.8/98 = 0.1 mol.",
    difficulty: "easy",
    type: "numerical",
    tags: ["mole concept", "H₂SO₄"],
  },
  {
    id: "qchem-c1-033",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Molarity",
    question:
      "The molarity of a solution containing 4 g NaOH in 1 L of solution is:",
    options: ["0.1 M", "1 M", "0.4 M", "4 M"],
    correctAnswer: "0.1 M",
    explanation:
      "Moles of NaOH = 4/40 = 0.1 mol. Molarity = 0.1/1 = 0.1 M.",
    difficulty: "medium",
    type: "numerical",
    tags: ["molarity", "NaOH"],
  },
  {
    id: "qchem-c1-034",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Molar Volume",
    question: "The number of molecules in 22.4 L of any gas at STP is:",
    options: [
      "6.022 × 10²³",
      "3 × 10²³",
      "1.5 × 10²³",
      "12 × 10²³",
    ],
    correctAnswer: "6.022 × 10²³",
    explanation:
      "22.4 L at STP = 1 mole, which contains Avogadro's number of molecules (6.022 × 10²³).",
    difficulty: "medium",
    type: "formula",
    tags: ["molar volume", "STP", "Avogadro's number"],
  },
  {
    id: "qchem-c1-035",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept",
    question: "The mass of one molecule of water is approximately:",
    options: ["18 g", "18 amu", "3 × 10⁻²³ g", "18 mg"],
    correctAnswer: "3 × 10⁻²³ g",
    explanation:
      "Mass of one molecule = molar mass / Nₐ = 18 / (6.022 × 10²³) ≈ 3 × 10⁻²³ g.",
    difficulty: "hard",
    type: "numerical",
    tags: ["mole concept", "molecular mass", "Avogadro's number"],
  },
  {
    id: "qchem-c1-036",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Molarity",
    question:
      "The number of moles of solute in 250 mL of 0.2 M solution is:",
    options: ["0.05", "0.5", "0.2", "0.1"],
    correctAnswer: "0.05",
    explanation: "Moles = M × V(L) = 0.2 × 0.25 = 0.05 mol.",
    difficulty: "medium",
    type: "numerical",
    tags: ["molarity", "stoichiometry"],
  },
  {
    id: "qchem-c1-037",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Limiting Reagent",
    question:
      "In 2H₂ + O₂ → 2H₂O, with 2 g H₂ and 32 g O₂, the limiting reagent is:",
    options: ["H₂", "O₂", "both", "neither"],
    correctAnswer: "H₂",
    explanation:
      "2 g H₂ = 1 mol needs 0.5 mol (16 g) O₂. We have excess O₂ (32 g), so H₂ is limiting.",
    difficulty: "hard",
    type: "numerical",
    tags: ["limiting reagent", "stoichiometry"],
  },
  {
    id: "qchem-c1-038",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Laws of Chemical Combination",
    question: "The law of multiple proportions was given by:",
    options: ["Dalton", "Proust", "Lavoisier", "Gay-Lussac"],
    correctAnswer: "Dalton",
    explanation:
      "Dalton's law of multiple proportions: when two elements form more than one compound, the masses combine in small whole-number ratios.",
    difficulty: "medium",
    type: "concept",
    tags: ["laws of chemical combination", "Dalton"],
  },
  {
    id: "qchem-c1-039",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept",
    question: "The mass of 0.5 mole of CH₄ is:",
    options: ["8 g", "16 g", "4 g", "32 g"],
    correctAnswer: "8 g",
    explanation: "Mass = 0.5 × 16 = 8 g (molar mass of CH₄ = 16).",
    difficulty: "easy",
    type: "numerical",
    tags: ["mole concept", "methane"],
  },
  {
    id: "qchem-c1-040",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c1",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept",
    question: "The number of moles of atoms in 4.4 g of CO₂ is:",
    options: ["0.3", "0.1", "0.5", "0.15"],
    correctAnswer: "0.3",
    explanation:
      "4.4 g CO₂ = 0.1 mol CO₂. Each molecule has 3 atoms, so atoms = 0.1 × 3 = 0.3 mol.",
    difficulty: "hard",
    type: "numerical",
    tags: ["mole concept", "atoms", "CO₂"],
  },

  // ==================== STRUCTURE OF ATOM (c2) — 40 questions ====================
  {
    id: "qchem-c2-001",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Atomic Number",
    question: "Atomic number is the number of:",
    options: ["protons", "neutrons", "protons + neutrons", "electrons + neutrons"],
    correctAnswer: "protons",
    explanation:
      "Atomic number (Z) equals the number of protons in the nucleus; in a neutral atom, also the number of electrons.",
    difficulty: "easy",
    type: "concept",
    tags: ["atomic number", "protons"],
  },
  {
    id: "qchem-c2-002",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Mass Number",
    question: "Mass number is the:",
    options: [
      "number of protons",
      "number of neutrons",
      "number of protons + neutrons",
      "number of electrons",
    ],
    correctAnswer: "number of protons + neutrons",
    explanation:
      "Mass number (A) = number of protons + number of neutrons in the nucleus.",
    difficulty: "easy",
    type: "concept",
    tags: ["mass number", "nucleons"],
  },
  {
    id: "qchem-c2-003",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Isotopes",
    question: "Isotopes have the same ___ but different ___.",
    options: [
      "mass number, atomic number",
      "atomic number, mass number",
      "protons, electrons",
      "neutrons, protons",
    ],
    correctAnswer: "atomic number, mass number",
    explanation:
      "Isotopes have the same number of protons (same Z) but different numbers of neutrons (different A).",
    difficulty: "medium",
    type: "concept",
    tags: ["isotopes", "atomic number", "mass number"],
  },
  {
    id: "qchem-c2-004",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Electronic Configuration",
    question: "The maximum number of electrons in a shell is given by:",
    options: ["2n", "n²", "2n²", "n"],
    correctAnswer: "2n²",
    explanation:
      "The maximum number of electrons in the nth shell is 2n² (K=2, L=8, M=18, N=32).",
    difficulty: "easy",
    type: "formula",
    tags: ["electronic configuration", "shells"],
  },
  {
    id: "qchem-c2-005",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Electronic Configuration",
    question: "The maximum number of electrons in the M shell is:",
    options: ["8", "18", "32", "2"],
    correctAnswer: "18",
    explanation: "For n = 3, max electrons = 2n² = 2 × 9 = 18.",
    difficulty: "medium",
    type: "numerical",
    tags: ["electronic configuration", "M shell"],
  },
  {
    id: "qchem-c2-006",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Bohr Model",
    question: "Bohr's model was primarily developed for which atom?",
    options: ["Hydrogen", "Helium", "Sodium", "Carbon"],
    correctAnswer: "Hydrogen",
    explanation:
      "Bohr's model successfully explained the spectrum of the hydrogen atom (and hydrogen-like species).",
    difficulty: "easy",
    type: "concept",
    tags: ["Bohr model", "hydrogen"],
  },
  {
    id: "qchem-c2-007",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Bohr Model",
    question: "The energy of an electron in the nth orbit of hydrogen is given by:",
    options: [
      "-2.18 × 10⁻¹⁸ × n² J",
      "-2.18 × 10⁻¹⁸/n² J",
      "+2.18 × 10⁻¹⁸/n² J",
      "-13.6/n² J",
    ],
    correctAnswer: "-2.18 × 10⁻¹⁸/n² J",
    explanation:
      "Eₙ = -2.18 × 10⁻¹⁸/n² J (or -13.6/n² eV). Energy is negative (bound state) and decreases in magnitude with n.",
    difficulty: "hard",
    type: "formula",
    tags: ["Bohr model", "energy levels"],
  },
  {
    id: "qchem-c2-008",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Orbitals",
    question: "The number of orbitals in a d subshell is:",
    options: ["3", "5", "7", "1"],
    correctAnswer: "5",
    explanation:
      "For l = 2 (d subshell), there are 2l + 1 = 5 orbitals.",
    difficulty: "medium",
    type: "formula",
    tags: ["orbitals", "d subshell"],
  },
  {
    id: "qchem-c2-009",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Orbitals",
    question: "The maximum number of electrons in a p subshell is:",
    options: ["2", "6", "10", "14"],
    correctAnswer: "6",
    explanation:
      "p subshell (l = 1) has 3 orbitals × 2 electrons each = 6 electrons max.",
    difficulty: "easy",
    type: "formula",
    tags: ["orbitals", "p subshell"],
  },
  {
    id: "qchem-c2-010",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Quantum Numbers",
    question: "Which quantum number gives the shape of an orbital?",
    options: ["Principal", "Azimuthal", "Magnetic", "Spin"],
    correctAnswer: "Azimuthal",
    explanation:
      "The azimuthal (angular momentum) quantum number l determines the shape of the orbital (s, p, d, f).",
    difficulty: "medium",
    type: "concept",
    tags: ["quantum numbers", "azimuthal quantum number"],
  },
  {
    id: "qchem-c2-011",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Quantum Numbers",
    question: "Which quantum number gives the orientation of an orbital?",
    options: ["Principal", "Azimuthal", "Magnetic", "Spin"],
    correctAnswer: "Magnetic",
    explanation:
      "The magnetic quantum number mₗ gives the orientation of the orbital in space.",
    difficulty: "medium",
    type: "concept",
    tags: ["quantum numbers", "magnetic quantum number"],
  },
  {
    id: "qchem-c2-012",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Orbitals",
    question: "The number of orbitals in an s subshell is:",
    options: ["1", "3", "5", "7"],
    correctAnswer: "1",
    explanation: "s subshell (l = 0) has 2l + 1 = 1 orbital.",
    difficulty: "easy",
    type: "formula",
    tags: ["orbitals", "s subshell"],
  },
  {
    id: "qchem-c2-013",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Hund's Rule",
    question: "Hund's rule states that:",
    options: [
      "electrons pair up before filling singly",
      "electrons fill singly with parallel spin first",
      "lower energy orbitals fill first",
      "no two electrons can have the same set of quantum numbers",
    ],
    correctAnswer: "electrons fill singly with parallel spin first",
    explanation:
      "Hund's rule: electrons occupy degenerate orbitals singly with parallel spins before pairing begins.",
    difficulty: "medium",
    type: "concept",
    tags: ["Hund's rule", "electronic configuration"],
  },
  {
    id: "qchem-c2-014",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Pauli's Principle",
    question: "Pauli's exclusion principle states that:",
    options: [
      "no two electrons in an atom can have the same set of four quantum numbers",
      "lower orbitals fill first",
      "electrons pair after singly filling",
      "orbitals have fixed shapes",
    ],
    correctAnswer: "no two electrons in an atom can have the same set of four quantum numbers",
    explanation:
      "Pauli's exclusion principle: no two electrons in the same atom can have identical sets of all four quantum numbers.",
    difficulty: "medium",
    type: "concept",
    tags: ["Pauli exclusion principle"],
  },
  {
    id: "qchem-c2-015",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Aufbau Principle",
    question: "Aufbau principle states that:",
    options: [
      "electrons fill lower energy orbitals first",
      "no two electrons have the same quantum numbers",
      "electrons pair after singly filling",
      "orbitals overlap",
    ],
    correctAnswer: "electrons fill lower energy orbitals first",
    explanation:
      "Aufbau (German for 'building up') principle: electrons fill orbitals in order of increasing energy.",
    difficulty: "medium",
    type: "concept",
    tags: ["Aufbau principle", "electronic configuration"],
  },
  {
    id: "qchem-c2-016",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Electronic Configuration",
    question: "The electronic configuration of sodium (Z = 11) is:",
    options: ["2, 8, 1", "2, 9", "2, 8, 2", "1, 8, 2"],
    correctAnswer: "2, 8, 1",
    explanation:
      "Na has 11 electrons: 2 in K, 8 in L, 1 in M shell, giving 2, 8, 1.",
    difficulty: "easy",
    type: "concept",
    tags: ["electronic configuration", "sodium"],
  },
  {
    id: "qchem-c2-017",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Electronic Configuration",
    question: "The electronic configuration of oxygen (Z = 8) is:",
    options: ["2, 6", "2, 5, 1", "2, 4, 2", "1, 7"],
    correctAnswer: "2, 6",
    explanation:
      "O has 8 electrons: 2 in K shell, 6 in L shell, giving 2, 6.",
    difficulty: "easy",
    type: "concept",
    tags: ["electronic configuration", "oxygen"],
  },
  {
    id: "qchem-c2-018",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Discovery of Electron",
    question: "The charge on an electron was determined by:",
    options: ["Millikan", "Thomson", "Rutherford", "Bohr"],
    correctAnswer: "Millikan",
    explanation:
      "Millikan's oil drop experiment measured the charge on an electron as approximately 1.6 × 10⁻¹⁹ C.",
    difficulty: "easy",
    type: "concept",
    tags: ["Millikan", "electron charge"],
  },
  {
    id: "qchem-c2-019",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Cathode Rays",
    question: "Cathode rays are streams of:",
    options: ["protons", "neutrons", "electrons", "alpha particles"],
    correctAnswer: "electrons",
    explanation:
      "Cathode rays (discovered by Thomson) are streams of fast-moving electrons emitted from the cathode.",
    difficulty: "easy",
    type: "concept",
    tags: ["cathode rays", "electrons"],
  },
  {
    id: "qchem-c2-020",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Canal Rays",
    question: "Canal rays are:",
    options: [
      "positively charged",
      "negatively charged",
      "neutral",
      "gamma rays",
    ],
    correctAnswer: "positively charged",
    explanation:
      "Canal (anode) rays consist of positively charged ions and led to the discovery of the proton.",
    difficulty: "medium",
    type: "concept",
    tags: ["canal rays", "protons"],
  },
  {
    id: "qchem-c2-021",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Rutherford's Experiment",
    question:
      "Rutherford's gold foil experiment led to the discovery of the:",
    options: ["electron", "proton", "neutron", "nucleus"],
    correctAnswer: "nucleus",
    explanation:
      "The scattering of alpha particles revealed a small, dense, positively charged nucleus at the centre of the atom.",
    difficulty: "easy",
    type: "concept",
    tags: ["Rutherford", "nucleus"],
  },
  {
    id: "qchem-c2-022",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Electronic Configuration",
    question: "The maximum number of electrons in the K shell is:",
    options: ["2", "8", "18", "32"],
    correctAnswer: "2",
    explanation: "For n = 1 (K shell), max electrons = 2n² = 2(1)² = 2.",
    difficulty: "easy",
    type: "formula",
    tags: ["electronic configuration", "K shell"],
  },
  {
    id: "qchem-c2-023",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Isotopes",
    question: "The number of neutrons in ¹⁴N (Z = 7) is:",
    options: ["7", "14", "21", "0"],
    correctAnswer: "7",
    explanation: "Mass number A = 14, Z = 7. Neutrons = A − Z = 14 − 7 = 7.",
    difficulty: "easy",
    type: "numerical",
    tags: ["isotopes", "neutrons", "nitrogen"],
  },
  {
    id: "qchem-c2-024",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Orbitals",
    question: "The number of d orbitals in the third shell is:",
    options: ["3", "5", "7", "1"],
    correctAnswer: "5",
    explanation:
      "The d subshell (l = 2) always contains 5 orbitals, regardless of the principal shell.",
    difficulty: "medium",
    type: "formula",
    tags: ["orbitals", "d subshell"],
  },
  {
    id: "qchem-c2-025",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Quantum Numbers",
    question: "For quantum number n = 3, the possible values of l are:",
    options: ["0, 1, 2", "0, 1, 2, 3", "1, 2, 3", "0, 1"],
    correctAnswer: "0, 1, 2",
    explanation:
      "l ranges from 0 to n − 1, so for n = 3, l = 0, 1, 2 (s, p, d).",
    difficulty: "medium",
    type: "formula",
    tags: ["quantum numbers", "principal quantum number"],
  },
  {
    id: "qchem-c2-026",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Electronic Configuration",
    question: "The number of electrons in the outermost shell of neon is:",
    options: ["2", "6", "8", "4"],
    correctAnswer: "8",
    explanation:
      "Neon (Z = 10): 2, 8. The outermost (L) shell has 8 electrons (octet, noble gas).",
    difficulty: "easy",
    type: "concept",
    tags: ["electronic configuration", "neon", "octet"],
  },
  {
    id: "qchem-c2-027",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Isoelectronic Species",
    question: "Isoelectronic species have the same:",
    options: [
      "number of electrons",
      "number of protons",
      "atomic number",
      "mass number",
    ],
    correctAnswer: "number of electrons",
    explanation:
      "Isoelectronic species are atoms/ions with the same number of electrons (e.g., Na⁺, Mg²⁺, Al³⁺, Ne all have 10 electrons).",
    difficulty: "medium",
    type: "concept",
    tags: ["isoelectronic species"],
  },
  {
    id: "qchem-c2-028",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Bohr Model",
    question: "Bohr's orbits are called:",
    options: [
      "stationary states",
      "dynamic states",
      "excited states",
      "ground states",
    ],
    correctAnswer: "stationary states",
    explanation:
      "Bohr called his allowed orbits 'stationary states' because electrons in them do not radiate energy.",
    difficulty: "medium",
    type: "concept",
    tags: ["Bohr model", "stationary states"],
  },
  {
    id: "qchem-c2-029",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Energy Levels",
    question: "As n increases, the energy of an electron in hydrogen:",
    options: [
      "increases (becomes less negative)",
      "decreases (becomes more negative)",
      "remains the same",
      "becomes zero",
    ],
    correctAnswer: "increases (becomes less negative)",
    explanation:
      "E = -13.6/n² eV. As n grows, E approaches 0 from below, so energy increases (less negative).",
    difficulty: "medium",
    type: "concept",
    tags: ["energy levels", "Bohr model"],
  },
  {
    id: "qchem-c2-030",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Wave-Particle Duality",
    question:
      "The wavelength associated with a moving particle is given by:",
    options: [
      "de Broglie equation",
      "Bohr equation",
      "Heisenberg equation",
      "Schrödinger equation",
    ],
    correctAnswer: "de Broglie equation",
    explanation:
      "de Broglie's equation λ = h/mv gives the wavelength of a particle of mass m moving with velocity v.",
    difficulty: "medium",
    type: "concept",
    tags: ["de Broglie", "wave-particle duality"],
  },
  {
    id: "qchem-c2-031",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Heisenberg's Principle",
    question: "Heisenberg's uncertainty principle relates:",
    options: [
      "position and momentum",
      "energy and time only",
      "charge and mass",
      "position and velocity",
    ],
    correctAnswer: "position and momentum",
    explanation:
      "Heisenberg's principle: Δx · Δp ≥ h/4π. Position and momentum cannot both be known precisely at the same time.",
    difficulty: "hard",
    type: "concept",
    tags: ["Heisenberg", "uncertainty principle"],
  },
  {
    id: "qchem-c2-032",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Atomic Number",
    question: "The atomic number of carbon is:",
    options: ["4", "6", "8", "12"],
    correctAnswer: "6",
    explanation: "Carbon has 6 protons, so its atomic number Z = 6.",
    difficulty: "easy",
    type: "concept",
    tags: ["atomic number", "carbon"],
  },
  {
    id: "qchem-c2-033",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Orbitals",
    question: "The total number of orbitals in the n = 3 shell is:",
    options: ["9", "3", "6", "16"],
    correctAnswer: "9",
    explanation:
      "n = 3 has s (1) + p (3) + d (5) = 9 orbitals. (Also = n² = 9.)",
    difficulty: "medium",
    type: "numerical",
    tags: ["orbitals", "shells"],
  },
  {
    id: "qchem-c2-034",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Shape of Orbitals",
    question: "The shape of an s orbital is:",
    options: ["spherical", "dumbbell", "double dumbbell", "complex"],
    correctAnswer: "spherical",
    explanation:
      "s orbitals (l = 0) are spherically symmetric about the nucleus.",
    difficulty: "easy",
    type: "concept",
    tags: ["orbitals", "shape", "s orbital"],
  },
  {
    id: "qchem-c2-035",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Shape of Orbitals",
    question: "The shape of a p orbital is:",
    options: ["spherical", "dumbbell", "double dumbbell", "circular"],
    correctAnswer: "dumbbell",
    explanation: "p orbitals (l = 1) have a dumbbell shape with two lobes.",
    difficulty: "easy",
    type: "concept",
    tags: ["orbitals", "shape", "p orbital"],
  },
  {
    id: "qchem-c2-036",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Electronic Configuration",
    question:
      "The number of unpaired electrons in nitrogen (Z = 7) is:",
    options: ["1", "2", "3", "0"],
    correctAnswer: "3",
    explanation:
      "N config: 1s² 2s² 2p³. By Hund's rule, the three 2p electrons occupy separate orbitals singly, giving 3 unpaired electrons.",
    difficulty: "medium",
    type: "numerical",
    tags: ["electronic configuration", "unpaired electrons", "Hund's rule"],
  },
  {
    id: "qchem-c2-037",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Noble Gases",
    question: "Which of the following has a completely filled outermost shell?",
    options: ["He", "H", "Li", "Na"],
    correctAnswer: "He",
    explanation:
      "Helium has a fully filled K shell (2 electrons), making it stable and unreactive like other noble gases.",
    difficulty: "easy",
    type: "concept",
    tags: ["noble gases", "electronic configuration"],
  },
  {
    id: "qchem-c2-038",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Ionization Energy",
    question: "The energy required to remove an electron from an atom is called:",
    options: [
      "ionization energy",
      "electron affinity",
      "electronegativity",
      "lattice energy",
    ],
    correctAnswer: "ionization energy",
    explanation:
      "Ionization energy is the minimum energy needed to remove the most loosely bound electron from an isolated gaseous atom.",
    difficulty: "easy",
    type: "concept",
    tags: ["ionization energy"],
  },
  {
    id: "qchem-c2-039",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Energy States",
    question: "An electron in the ground state has ___ energy compared to an excited state.",
    options: ["higher", "lower", "equal", "zero"],
    correctAnswer: "lower",
    explanation:
      "The ground state (n = 1) has the lowest (most negative) energy; excited states have higher energy.",
    difficulty: "medium",
    type: "concept",
    tags: ["ground state", "excited state", "energy levels"],
  },
  {
    id: "qchem-c2-040",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c2",
    chapter: "Structure of Atom",
    topic: "Atomic Number",
    question: "The number of protons in ²³Na is:",
    options: ["11", "12", "23", "34"],
    correctAnswer: "11",
    explanation:
      "Sodium has atomic number Z = 11, so it has 11 protons (and 12 neutrons, since A = 23).",
    difficulty: "easy",
    type: "numerical",
    tags: ["atomic number", "sodium", "protons"],
  },

  // ==================== CHEMICAL BONDING AND MOLECULAR STRUCTURE (c4) — 40 questions ====================
  {
    id: "qchem-c4-001",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Ionic Bond",
    question: "A bond formed by the complete transfer of electrons is:",
    options: ["ionic", "covalent", "coordinate", "metallic"],
    correctAnswer: "ionic",
    explanation:
      "In an ionic bond, one atom transfers electron(s) to another, forming oppositely charged ions held by electrostatic attraction.",
    difficulty: "easy",
    type: "concept",
    tags: ["ionic bond", "chemical bonding"],
  },
  {
    id: "qchem-c4-002",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Covalent Bond",
    question: "A bond formed by the sharing of electrons is:",
    options: ["ionic", "covalent", "metallic", "hydrogen"],
    correctAnswer: "covalent",
    explanation:
      "In a covalent bond, two atoms share one or more pairs of electrons to achieve stable configurations.",
    difficulty: "easy",
    type: "concept",
    tags: ["covalent bond", "chemical bonding"],
  },
  {
    id: "qchem-c4-003",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Coordinate Bond",
    question: "A coordinate bond is a type of:",
    options: ["ionic bond", "covalent bond", "metallic bond", "hydrogen bond"],
    correctAnswer: "covalent bond",
    explanation:
      "A coordinate (dative) bond is a special covalent bond where both shared electrons come from one atom.",
    difficulty: "medium",
    type: "concept",
    tags: ["coordinate bond", "covalent bond"],
  },
  {
    id: "qchem-c4-004",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Coordinate Bond",
    question: "In a coordinate bond, the shared electron pair comes from:",
    options: [
      "both atoms",
      "one atom only",
      "neither atom",
      "the metal only",
    ],
    correctAnswer: "one atom only",
    explanation:
      "In a coordinate bond, one atom (donor) contributes both electrons; the other (acceptor) shares them.",
    difficulty: "medium",
    type: "concept",
    tags: ["coordinate bond", "donor", "acceptor"],
  },
  {
    id: "qchem-c4-005",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Octet Rule",
    question: "The octet rule was proposed by:",
    options: ["Lewis", "Kossel", "Pauling", "Bohr"],
    correctAnswer: "Lewis",
    explanation:
      "G. N. Lewis proposed the octet rule: atoms tend to gain, lose, or share electrons to attain 8 in their outer shell.",
    difficulty: "medium",
    type: "concept",
    tags: ["octet rule", "Lewis"],
  },
  {
    id: "qchem-c4-006",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Lone Pairs",
    question: "The number of lone pairs in a water molecule is:",
    options: ["1", "2", "3", "0"],
    correctAnswer: "2",
    explanation:
      "Oxygen in H₂O has 6 valence electrons; 2 are used in O–H bonds, leaving 2 lone pairs.",
    difficulty: "easy",
    type: "numerical",
    tags: ["lone pairs", "water"],
  },
  {
    id: "qchem-c4-007",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "VSEPR Theory",
    question: "The shape of a CH₄ molecule is:",
    options: ["tetrahedral", "pyramidal", "planar", "linear"],
    correctAnswer: "tetrahedral",
    explanation:
      "CH₄ has 4 bonding pairs and no lone pairs on C, giving a tetrahedral shape with bond angle 109.5°.",
    difficulty: "easy",
    type: "concept",
    tags: ["VSEPR", "shape", "methane"],
  },
  {
    id: "qchem-c4-008",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "VSEPR Theory",
    question: "The shape of an NH₃ molecule is:",
    options: ["tetrahedral", "pyramidal", "linear", "planar"],
    correctAnswer: "pyramidal",
    explanation:
      "NH₃ has 3 bond pairs and 1 lone pair on N, giving a trigonal pyramidal shape with bond angle ~107°.",
    difficulty: "medium",
    type: "concept",
    tags: ["VSEPR", "shape", "ammonia"],
  },
  {
    id: "qchem-c4-009",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "VSEPR Theory",
    question: "The shape of an H₂O molecule is:",
    options: ["linear", "bent", "tetrahedral", "pyramidal"],
    correctAnswer: "bent",
    explanation:
      "H₂O has 2 bond pairs and 2 lone pairs on O, giving a bent (V-shaped) structure with angle ~104.5°.",
    difficulty: "medium",
    type: "concept",
    tags: ["VSEPR", "shape", "water"],
  },
  {
    id: "qchem-c4-010",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Hybridisation",
    question: "The hybridisation of carbon in CH₄ is:",
    options: ["sp", "sp²", "sp³", "sp³d"],
    correctAnswer: "sp³",
    explanation:
      "C in CH₄ forms 4 equivalent sigma bonds → sp³ hybridisation → tetrahedral geometry.",
    difficulty: "medium",
    type: "concept",
    tags: ["hybridisation", "sp³", "methane"],
  },
  {
    id: "qchem-c4-011",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Hybridisation",
    question: "The hybridisation of carbon in acetylene (C₂H₂) is:",
    options: ["sp", "sp²", "sp³", "sp³d"],
    correctAnswer: "sp",
    explanation:
      "Each C in C₂H₂ forms 2 sigma bonds (1 to H, 1 to C) → sp hybridisation → linear geometry.",
    difficulty: "hard",
    type: "concept",
    tags: ["hybridisation", "sp", "acetylene"],
  },
  {
    id: "qchem-c4-012",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Hybridisation",
    question: "The hybridisation of carbon in ethylene (C₂H₄) is:",
    options: ["sp", "sp²", "sp³", "sp³d"],
    correctAnswer: "sp²",
    explanation:
      "Each C in C₂H₄ forms 3 sigma bonds → sp² hybridisation → trigonal planar geometry around each C.",
    difficulty: "hard",
    type: "concept",
    tags: ["hybridisation", "sp²", "ethylene"],
  },
  {
    id: "qchem-c4-013",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Sigma and Pi Bonds",
    question: "The number of sigma bonds in ethane (C₂H₆) is:",
    options: ["6", "7", "1", "8"],
    correctAnswer: "7",
    explanation:
      "C₂H₆ has 6 C–H sigma bonds and 1 C–C sigma bond = 7 sigma bonds in total.",
    difficulty: "medium",
    type: "numerical",
    tags: ["sigma bonds", "ethane"],
  },
  {
    id: "qchem-c4-014",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Sigma and Pi Bonds",
    question: "The number of pi bonds in acetylene (C₂H₂) is:",
    options: ["1", "2", "3", "0"],
    correctAnswer: "2",
    explanation:
      "C₂H₂ has a triple bond (1 sigma + 2 pi) between carbons, so there are 2 pi bonds.",
    difficulty: "medium",
    type: "numerical",
    tags: ["pi bonds", "acetylene"],
  },
  {
    id: "qchem-c4-015",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "VSEPR Theory",
    question: "VSEPR theory predicts molecular shape based on:",
    options: [
      "lone pair repulsion",
      "atomic size",
      "electronegativity",
      "ionization energy",
    ],
    correctAnswer: "lone pair repulsion",
    explanation:
      "VSEPR (Valence Shell Electron Pair Repulsion) theory states that electron pairs (bonding and lone) arrange to minimise repulsion, determining shape.",
    difficulty: "medium",
    type: "concept",
    tags: ["VSEPR", "lone pair repulsion"],
  },
  {
    id: "qchem-c4-016",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Bond Angles",
    question: "The bond angle in CH₄ is:",
    options: ["90°", "109.5°", "120°", "180°"],
    correctAnswer: "109.5°",
    explanation:
      "Tetrahedral CH₄ has a bond angle of 109.5° (sp³ hybridisation).",
    difficulty: "easy",
    type: "formula",
    tags: ["bond angle", "methane", "tetrahedral"],
  },
  {
    id: "qchem-c4-017",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Bond Angles",
    question: "The bond angle in NH₃ is approximately:",
    options: ["90°", "107°", "109.5°", "120°"],
    correctAnswer: "107°",
    explanation:
      "Lone pair–bond pair repulsion compresses the angle from 109.5° to about 107° in NH₃.",
    difficulty: "medium",
    type: "formula",
    tags: ["bond angle", "ammonia"],
  },
  {
    id: "qchem-c4-018",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Bond Angles",
    question: "The bond angle in H₂O is approximately:",
    options: ["104.5°", "107°", "109.5°", "120°"],
    correctAnswer: "104.5°",
    explanation:
      "Two lone pairs compress the angle from 109.5° to about 104.5° in H₂O.",
    difficulty: "medium",
    type: "formula",
    tags: ["bond angle", "water"],
  },
  {
    id: "qchem-c4-019",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Bond Angles",
    question: "Which of the following has the highest bond angle?",
    options: ["CH₄", "NH₃", "H₂O", "CO₂"],
    correctAnswer: "CO₂",
    explanation:
      "CO₂ is linear with a bond angle of 180°, the highest among the options.",
    difficulty: "medium",
    type: "concept",
    tags: ["bond angle", "linear molecule"],
  },
  {
    id: "qchem-c4-020",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Formal Charge",
    question: "The formal charge on an atom is calculated as:",
    options: [
      "V − L − B/2",
      "V + L − B",
      "L − V + B/2",
      "V − L + B",
    ],
    correctAnswer: "V − L − B/2",
    explanation:
      "Formal charge = valence electrons (V) − lone pair electrons (L) − ½ bonding electrons (B).",
    difficulty: "hard",
    type: "formula",
    tags: ["formal charge"],
  },
  {
    id: "qchem-c4-021",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Hydrogen Bonding",
    question: "Hydrogen bonding is strongest when H is bonded to:",
    options: ["F, O, N", "C, H, O", "F, Cl, Br", "Na, K, Ca"],
    correctAnswer: "F, O, N",
    explanation:
      "H bonded to highly electronegative atoms F, O, or N forms strong hydrogen bonds due to large dipole.",
    difficulty: "medium",
    type: "concept",
    tags: ["hydrogen bonding", "electronegativity"],
  },
  {
    id: "qchem-c4-022",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Dipole Moment",
    question: "The dipole moment of H₂O is approximately:",
    options: ["1.85 D", "1.5 D", "0 D", "1.08 D"],
    correctAnswer: "1.85 D",
    explanation:
      "H₂O has a dipole moment of about 1.85 D due to its bent shape and polar O–H bonds.",
    difficulty: "hard",
    type: "formula",
    tags: ["dipole moment", "water"],
  },
  {
    id: "qchem-c4-023",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Polarity",
    question: "Which of the following is a nonpolar molecule?",
    options: ["HCl", "H₂O", "CO₂", "NH₃"],
    correctAnswer: "CO₂",
    explanation:
      "CO₂ is linear and symmetric, so the two C=O bond dipoles cancel, making the molecule nonpolar.",
    difficulty: "medium",
    type: "concept",
    tags: ["polarity", "nonpolar", "CO₂"],
  },
  {
    id: "qchem-c4-024",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Dipole Moment",
    question: "The dipole moment of BF₃ is:",
    options: ["0", "1.5 D", "2 D", "3 D"],
    correctAnswer: "0",
    explanation:
      "BF₃ is trigonal planar and symmetric; the three B–F bond dipoles cancel, giving a net dipole moment of 0.",
    difficulty: "hard",
    type: "numerical",
    tags: ["dipole moment", "BF₃", "symmetry"],
  },
  {
    id: "qchem-c4-025",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Resonance",
    question: "The resonance structure of benzene shows:",
    options: [
      "alternating single and double bonds",
      "delocalized electrons",
      "ionic bonds",
      "no bonding",
    ],
    correctAnswer: "delocalized electrons",
    explanation:
      "Benzene's π electrons are delocalized over all six carbons, giving equivalent C–C bonds intermediate between single and double.",
    difficulty: "medium",
    type: "concept",
    tags: ["resonance", "benzene", "delocalization"],
  },
  {
    id: "qchem-c4-026",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Lone Pairs",
    question: "The number of lone pairs on N in NH₃ is:",
    options: ["0", "1", "2", "3"],
    correctAnswer: "1",
    explanation:
      "N in NH₃ has 5 valence electrons; 3 are used in N–H bonds, leaving 1 lone pair.",
    difficulty: "easy",
    type: "numerical",
    tags: ["lone pairs", "ammonia"],
  },
  {
    id: "qchem-c4-027",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Types of Bonds",
    question: "The type of bond in NaCl is:",
    options: ["ionic", "covalent", "metallic", "hydrogen"],
    correctAnswer: "ionic",
    explanation:
      "Na donates an electron to Cl, forming Na⁺ and Cl⁻ ions held by ionic (electrostatic) attraction.",
    difficulty: "easy",
    type: "concept",
    tags: ["ionic bond", "NaCl"],
  },
  {
    id: "qchem-c4-028",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Types of Bonds",
    question: "The type of bond in H₂ is:",
    options: ["ionic", "covalent", "metallic", "hydrogen"],
    correctAnswer: "covalent",
    explanation:
      "Two H atoms share a pair of electrons to form a nonpolar covalent bond.",
    difficulty: "easy",
    type: "concept",
    tags: ["covalent bond", "hydrogen molecule"],
  },
  {
    id: "qchem-c4-029",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Coordinate Bond",
    question:
      "The bond between N and the fourth H in NH₄⁺ is:",
    options: ["coordinate", "ionic", "metallic", "hydrogen"],
    correctAnswer: "coordinate",
    explanation:
      "In NH₄⁺, the N donates its lone pair to H⁺, forming a coordinate (dative) bond.",
    difficulty: "medium",
    type: "concept",
    tags: ["coordinate bond", "ammonium ion"],
  },
  {
    id: "qchem-c4-030",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Bond Order",
    question: "The bond order of N₂ is:",
    options: ["1", "2", "3", "4"],
    correctAnswer: "3",
    explanation:
      "N₂ has a triple bond (one sigma + two pi), so bond order = 3.",
    difficulty: "medium",
    type: "numerical",
    tags: ["bond order", "nitrogen"],
  },
  {
    id: "qchem-c4-031",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Bond Angles",
    question: "Which of the following has the lowest bond angle?",
    options: ["CH₄", "NH₃", "H₂O", "CO₂"],
    correctAnswer: "H₂O",
    explanation:
      "H₂O has two lone pairs causing maximum repulsion, so it has the lowest bond angle (~104.5°).",
    difficulty: "medium",
    type: "concept",
    tags: ["bond angle", "lone pairs"],
  },
  {
    id: "qchem-c4-032",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Molecular Geometry",
    question: "Which of the following molecules is linear?",
    options: ["H₂O", "CO₂", "NH₃", "CH₄"],
    correctAnswer: "CO₂",
    explanation:
      "CO₂ (O=C=O) has sp hybridised C with no lone pairs, giving a linear shape (180°).",
    difficulty: "easy",
    type: "concept",
    tags: ["molecular geometry", "linear", "CO₂"],
  },
  {
    id: "qchem-c4-033",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Hybridisation",
    question: "The hybridisation of N in NH₃ is:",
    options: ["sp", "sp²", "sp³", "sp³d"],
    correctAnswer: "sp³",
    explanation:
      "N in NH₃ has 4 electron pairs (3 bond + 1 lone), so it is sp³ hybridised (tetrahedral electron geometry).",
    difficulty: "medium",
    type: "concept",
    tags: ["hybridisation", "sp³", "ammonia"],
  },
  {
    id: "qchem-c4-034",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Hybridisation",
    question: "The hybridisation of O in H₂O is:",
    options: ["sp", "sp²", "sp³", "sp³d"],
    correctAnswer: "sp³",
    explanation:
      "O in H₂O has 4 electron pairs (2 bond + 2 lone), so it is sp³ hybridised.",
    difficulty: "medium",
    type: "concept",
    tags: ["hybridisation", "sp³", "water"],
  },
  {
    id: "qchem-c4-035",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Sigma Bonds",
    question: "A sigma bond is formed by:",
    options: [
      "head-on (axial) overlap",
      "sideways overlap",
      "no overlap",
      "ionic interaction",
    ],
    correctAnswer: "head-on (axial) overlap",
    explanation:
      "Sigma bonds are formed by end-to-end (axial) overlap of orbitals, giving strong bonds along the internuclear axis.",
    difficulty: "medium",
    type: "concept",
    tags: ["sigma bond", "orbital overlap"],
  },
  {
    id: "qchem-c4-036",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Pi Bonds",
    question: "A pi bond is formed by:",
    options: [
      "head-on overlap",
      "sideways overlap",
      "no overlap",
      "ionic interaction",
    ],
    correctAnswer: "sideways overlap",
    explanation:
      "Pi bonds are formed by sideways (lateral) overlap of p orbitals above and below the bond axis.",
    difficulty: "medium",
    type: "concept",
    tags: ["pi bond", "orbital overlap"],
  },
  {
    id: "qchem-c4-037",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Hydrogen Bonding",
    question: "The strongest hydrogen bond is present in:",
    options: ["H₂O", "HF", "NH₃", "CH₄"],
    correctAnswer: "HF",
    explanation:
      "F is the most electronegative element, so H–F···H forms the strongest individual hydrogen bond.",
    difficulty: "hard",
    type: "concept",
    tags: ["hydrogen bonding", "HF"],
  },
  {
    id: "qchem-c4-038",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Coordinate Bond",
    question: "Which of the following contains a coordinate bond?",
    options: ["NH₄⁺", "O₂", "N₂", "Cl₂"],
    correctAnswer: "NH₄⁺",
    explanation:
      "In NH₄⁺, N donates a lone pair to H⁺, forming one coordinate (dative) bond; the other three N–H bonds are normal covalent bonds.",
    difficulty: "medium",
    type: "concept",
    tags: ["coordinate bond", "ammonium ion"],
  },
  {
    id: "qchem-c4-039",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Sigma and Pi Bonds",
    question: "The number of sigma bonds in ethylene (C₂H₄) is:",
    options: ["3", "4", "5", "6"],
    correctAnswer: "5",
    explanation:
      "C₂H₄ has 4 C–H sigma bonds + 1 C–C sigma bond = 5 sigma bonds (and 1 pi bond).",
    difficulty: "medium",
    type: "numerical",
    tags: ["sigma bonds", "ethylene"],
  },
  {
    id: "qchem-c4-040",
    subject: "chemistry",
    subjectName: "Chemistry",
    chapterId: "c4",
    chapter: "Chemical Bonding and Molecular Structure",
    topic: "Lattice Energy",
    question: "Lattice energy is associated mainly with:",
    options: [
      "ionic compounds",
      "covalent compounds",
      "metals",
      "noble gases",
    ],
    correctAnswer: "ionic compounds",
    explanation:
      "Lattice energy is the energy released when gaseous ions form one mole of a solid ionic compound; it is a key feature of ionic bonding.",
    difficulty: "medium",
    type: "concept",
    tags: ["lattice energy", "ionic compounds"],
  },
];
