"use client";
import { useState } from "react";
import { Play, Plus, ArrowUp, ArrowDown, Trash2, Link2, Music2, Sparkles, Heart } from "lucide-react";
import { useMusicStore } from "@/lib/music-store";
import { buildSoundtrack } from "@/lib/study-music/catalog";
import { trackName, type MusicTrack } from "@/lib/study-music/model";
import { toast } from "@/lib/notifications/notification-api";
import { MusicThumbnail } from "./thumbnail";

export function MySongs({ search, onImport }: { search: string; onImport: () => void }) {
  const songs = useMusicStore(s => s.library.songs);
  const favorites = useMusicStore(s => s.library.favorites), playlists = useMusicStore(s => s.library.playlists);
  const [dragged, setDragged] = useState<number | null>(null);
  const filtered = songs.filter(t => `${trackName(t)} ${t.artist}`.toLowerCase().includes(search.toLowerCase()));
  return <section><div className="sm-section-heading"><div><h2>My Songs <span>{songs.length}</span></h2><p className="sm-muted">Your links. Your order. Your study rhythm.</p></div><button className="sm-btn sm-primary" onClick={onImport}><Link2 size={17}/> Import from YouTube</button></div>
    {!songs.length ? <div className="sm-empty"><Music2 size={34}/><h3>Your personal soundtrack starts here.</h3><p>Paste a YouTube video link, preview its title and channel, then save it to My Songs.</p><button className="sm-btn" onClick={onImport}>Add your first song <Plus size={16}/></button></div> : !filtered.length ? <div className="sm-empty">No songs match your search.</div> : <div className="sm-song-list">{filtered.map(track => { const index = songs.findIndex(t => t.id === track.id); return <div key={track.id} className="sm-song-row" draggable={!search} onDragStart={() => setDragged(index)} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); if (dragged !== null) { let from = dragged; while (from !== index) { const direction = index > from ? 1 : -1; useMusicStore.getState().moveSong(from, direction); from += direction; } } setDragged(null); }}>
      <button className="sm-song-art" aria-label={`Play ${trackName(track)}`} onClick={() => useMusicStore.getState().playTrack(track, songs)}><MusicThumbnail track={track}/></button><div className="sm-song-copy"><input aria-label={`Display title for ${track.title}`} maxLength={160} defaultValue={trackName(track)} key={track.displayTitle ?? track.title} onBlur={e => useMusicStore.getState().renameSong(track.id, e.target.value)}/><small>{track.artist}</small><span className="sm-small sm-muted">Original: {track.title}</span></div><div className="sm-row-actions"><button className="sm-icon" aria-label={`Play ${trackName(track)}`} onClick={() => useMusicStore.getState().playTrack(track, songs)}><Play size={17}/></button><button className="sm-icon" aria-label={`Queue ${trackName(track)}`} onClick={() => useMusicStore.getState().addToQueue(track)}><Plus size={17}/></button><button className="sm-icon" disabled={index === 0} aria-label={`Move ${trackName(track)} up`} onClick={() => useMusicStore.getState().moveSong(index, -1)}><ArrowUp size={16}/></button><button className="sm-icon" disabled={index === songs.length - 1} aria-label={`Move ${trackName(track)} down`} onClick={() => useMusicStore.getState().moveSong(index, 1)}><ArrowDown size={16}/></button><button className="sm-icon" aria-label={`Remove ${trackName(track)}`} onClick={() => { if (window.confirm(`Remove ${trackName(track)} from My Songs?`)) useMusicStore.getState().removeSong(track.id); }}><Trash2 size={16}/></button></div>
      <div className="sm-row-actions"><button className="sm-icon" aria-label={`Favorite ${trackName(track)}`} aria-pressed={favorites.includes(track.id)} onClick={()=>useMusicStore.getState().favorite(track.id)}><Heart size={16} fill={favorites.includes(track.id)?"currentColor":"none"}/></button><details className="sm-menu"><summary aria-label={`More actions for ${trackName(track)}`}>•••</summary><div><button onClick={()=>useMusicStore.getState().addToQueue(track,true)}>Play next</button>{playlists.map(p=><button key={p.id} onClick={()=>{useMusicStore.getState().playlistAdd(p.id,track.id);toast.success(`Added to ${p.name}`);}}>Add to {p.name}</button>)}<a href={`https://www.youtube.com/watch?v=${track.id}`} target="_blank" rel="noopener noreferrer">Open on YouTube</a></div></details></div>
    </div>; })}</div>}
  </section>;
}

export function SoundtrackBuilder({ tracks }: { tracks: MusicTrack[] }) {
  const [mood, setMood] = useState("focus"), [minutes, setMinutes] = useState(50), [subject, setSubject] = useState("");
  const favorites = useMusicStore(s => s.library.favorites);
  return <section className="sm-panel sm-soundtrack"><div><small className="sm-kicker">MADE FOR THIS MOMENT</small><h2>A soundtrack for your study session.</h2><p className="sm-muted">A temporary queue assembled from your library and the catalog. Not AI-generated music.</p></div><form onSubmit={e => { e.preventDefault(); const queue = buildSoundtrack(tracks, mood, favorites, Math.max(3, Math.min(8, Math.ceil(minutes / 20)))); if (queue.length) { useMusicStore.getState().playTrack(queue[0], queue); toast.success(`Your ${subject || "study"} soundtrack is ready`, { description: "Track lengths vary. Use the focus timer to measure your study session." }); } }}><label>Study context<input placeholder="Physics · Laws of Motion" value={subject} maxLength={120} onChange={e => setSubject(e.target.value)}/></label><label>Mood<select value={mood} onChange={e => setMood(e.target.value)}><option value="focus">Deep focus</option><option value="reading">Reading</option><option value="calm">Calm</option><option value="energetic">More energy</option></select></label><label>Session minutes<input type="number" min={15} max={180} value={minutes} onChange={e => setMinutes(Number(e.target.value))}/></label><button className="sm-btn sm-primary" disabled={!Number.isFinite(minutes) || minutes < 15 || minutes > 180}><Sparkles size={17}/> Build soundtrack</button></form></section>;
}
