"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BookOpen, Brain, CalendarDays, Check, Clock3, FileText, Globe, Lightbulb, Sparkles, Target } from "lucide-react";
import { getCurriculum } from "@/lib/curriculum-helper";
import { setupSchema, type Setup } from "@/lib/exam-ready/model";
import { plan, strategy } from "@/lib/exam-ready/planner";
import { formatTime, recommendStudyBudget, stageLabels } from "@/lib/exam-ready/experience";
import { examRequest } from "./use-session";
import { Materials } from "./tools";
import { LAMVisual, Plate } from "./presentation";

const localDate = (time: number) => new Date(time - new Date(time).getTimezoneOffset() * 60000).toISOString().slice(0, 16);
const confidence = ["Don’t know", "A little", "50/50", "I know this", "Strong here"];
const modes: { id: Setup["materials"]; title: string; text: string; icon: typeof Brain }[] = [
    { id: "all", title: "Mix of everything", text: "Your material + Scholar. Connect the best available sources.", icon: Sparkles },
    { id: "scholar-web", title: "Scholar + open web", text: "Reviewed Scholar content and curated, permitted public sources.", icon: Globe },
    { id: "scholar", title: "Scholar resources", text: "Use Scholar’s shared study catalog.", icon: BookOpen },
    { id: "personal-scholar", title: "My material + Scholar", text: "Combine your notes, uploads and shared content.", icon: FileText },
    { id: "personal", title: "My materials only", text: "Stay within readable personal sources and session notes.", icon: Target },
    { id: "custom", title: "Choose specific sources", text: "Teach only from sources you explicitly select below.", icon: Lightbulb },
];
export function SetupFlow({ grade, guest, busy, initial, onStart, onCancel }: { grade: 9 | 11; guest: boolean; busy: boolean; initial?: Setup; onStart: (s: Setup) => void; onCancel: () => void }) {
    const [error, setError] = useState("");
    const [setupDraft, setSetup] = useState<Setup>(() => initial ?? { exam: "My upcoming exam", grade, board: "CBSE", examAt: Date.now() + 86400000, minutes: 120, format: "school", style: "step-by-step", chapters: [], materials: "all", resourceIds: [], blocks: [], diagnostic: true });
    const [automaticBudget, setAutomaticBudget] = useState(!initial);
    const curriculum = getCurriculum(grade), [subject, setSubject] = useState(initial?.chapters[0]?.subjectId ?? curriculum[0].id), [query, setQuery] = useState(""), [relativeDate, setRelativeDate] = useState(false), [now] = useState(Date.now), [daily, setDaily] = useState(2);
    const availability = recommendStudyBudget(setupDraft.examAt, now, daily);
    const setup = automaticBudget ? { ...setupDraft, ...availability } : setupDraft;
    const update = <K extends keyof Setup>(key: K, value: Setup[K]) => {
        if (key === "minutes" || key === "blocks") {
            setAutomaticBudget(false);
            const blocks = key === "blocks" ? value as Setup["blocks"] : [];
            setSetup({ ...setup, [key]: value, ...(key === "minutes" ? { blocks: [] } : blocks.length ? { minutes: Math.max(15, Math.min(43200, blocks.reduce((sum, block) => sum + block.minutes, 0))) } : {}) });
        }
        else setSetup(s => ({ ...s, [key]: value }));
    };
    useEffect(() => { if (guest || initial) return; let active = true; examRequest("/api/personalization").then(v => { const p = v.preferences; if (active && p) setSetup(s => ({ ...s, board: p.board ?? s.board, style: p.style === "Short and direct" ? "concise" : p.style === "Examples first" ? "examples" : "step-by-step", exam: p.exam?.name ?? s.exam, examAt: p.exam?.date && Date.parse(`${p.exam.date}T09:00:00`) > Date.now() ? Date.parse(`${p.exam.date}T09:00:00`) : s.examAt })); }).catch(() => undefined); return () => { active = false; }; }, [guest, initial]);
    const preview = useMemo(() => setup.chapters.length ? plan(setup, Math.max(60, Math.floor(Math.min(setup.minutes * 60, (setup.examAt - now) / 1000)))) : [], [setup, now]);
    const stages = [...new Set(preview.map(t => t.kind))];
    const urgency = strategy(setup.minutes, (setup.examAt - now) / 60000);
    function build() {
        const parsed = setupSchema.safeParse(setup);
        if (!parsed.success) { setError(parsed.error.issues[0].message); return; }
        if (setup.examAt <= Date.now()) { setError("Choose an upcoming exam time."); return; }
        setError(""); onStart(parsed.data);
    }
    function scheduleDays() {
        if (!Number.isFinite(daily) || daily < .25 || daily > 8) { setError("Choose between 0.25 and 8 study hours per day."); return; }
        const { blocks, minutes } = recommendStudyBudget(setup.examAt, now, daily);
        if (!blocks.length) { setError("Daily blocks need an exam at least two days away. Choose a focused study budget for a nearer exam."); return; }
        setError("");
        setAutomaticBudget(false);
        setSetup(s => ({ ...s, blocks, minutes }));
    }
    return <div className="er-builder"><div className="er-builder-heading"><div><span className="er-eyebrow">Your preparation, built around you</span><h2>Tell us the exam. <em>We’ll find your path.</em></h2><p className="er-muted">Your deadline, real study time and starting confidence shape every step.</p></div><button onClick={onCancel} disabled={busy}>← Back</button></div><div className="er-builder-grid"><div className="er-builder-main">
        <Plate title="Subject and exam details" icon={BookOpen}><div className="er-fields"><label>Exam name<input value={setup.exam} maxLength={120} onChange={e => update("exam", e.target.value)}/></label><label>Board / exam<input value={setup.board} maxLength={60} onChange={e => update("board", e.target.value)}/></label><label>Class<input readOnly value={`Class ${grade}`}/></label><label>Exam format<select value={setup.format} onChange={e => update("format", e.target.value as Setup["format"])}><option value="school">School / theory</option><option value="mcq">MCQ</option><option value="mixed">MCQ + written</option><option value="short-answer">Written answers</option></select></label></div></Plate>
        <Plate title="When is your exam?" icon={CalendarDays}><div className="er-actions"><button aria-pressed={!relativeDate} onClick={() => setRelativeDate(false)}>Date and time</button><button aria-pressed={relativeDate} onClick={() => setRelativeDate(true)}>I know the time remaining</button></div><div className="er-fields">{relativeDate ? <label>Hours until exam<input type="number" min={.25} max={7200} step={.25} value={Math.round((setup.examAt - now) / 3600000 * 100) / 100} onChange={e => update("examAt", Math.round(now + Number(e.target.value) * 3600000))}/></label> : <label>Exam date and time<input type="datetime-local" value={localDate(setup.examAt)} onChange={e => { if (e.target.value) update("examAt", Date.parse(e.target.value)); }}/></label>}<div className="er-deadline"><small>Until your exam</small><strong>{formatTime((setup.examAt - now) / 1000)}</strong><span>We plan backwards from this.</span></div></div></Plate>
        <Plate title="How much time do you really have?" icon={Clock3}>
            <div className="er-budget-guidance" role="status"><strong>{automaticBudget ? "Suggested study budget" : "Your chosen study budget"}: {formatTime(setup.minutes * 60)}</strong><p>{automaticBudget ? setup.blocks.length ? `${daily} hours per day across ${setup.blocks.length} study blocks before your exam. The suggestion updates when your exam date changes.` : "A focused study budget based on your deadline—not every hour until the exam." : "Your manual choice is kept when the exam date changes. The plan still cannot run beyond the deadline."}</p><button aria-pressed={automaticBudget} onClick={() => { if (automaticBudget) setSetup(setup); setAutomaticBudget(!automaticBudget); }}>{automaticBudget ? "Set my own budget" : "Use automatic suggestion"}</button></div>
            <div className="er-budget-presets">{[15,30,60,120,240,360,480].map(n => <button key={n} aria-pressed={setup.minutes === n} onClick={() => update("minutes", n)}><strong>{n < 60 ? `${n} min` : `${n / 60} hr`}</strong><small>{n <= 30 ? "Essentials" : n <= 120 ? "Focused sprint" : "Deep preparation"}</small></button>)}</div>
            <div className="er-fields"><label>Custom study budget (minutes)<input type="number" min={15} max={43200} value={setup.minutes} onChange={e => update("minutes", Number(e.target.value))}/></label><label>Teaching style<select value={setup.style} onChange={e => update("style", e.target.value as Setup["style"])}><option value="step-by-step">Step by step</option><option value="concise">Short and direct</option><option value="examples">Examples first</option></select></label></div>
            <details><summary>Preparing over several days? Adjust study blocks</summary><div className="er-actions"><label>Hours per day<input type="number" min={.25} max={8} step={.25} value={daily} onChange={e => setDaily(Number(e.target.value))}/></label><button onClick={scheduleDays}>Create daily blocks</button></div>{setup.blocks.map((b, i) => <div className="er-block" key={i}><label>Start<input type="datetime-local" value={localDate(b.start)} onChange={e => { if (e.target.value) update("blocks", setup.blocks.map((x, j) => j === i ? { ...x, start: Date.parse(e.target.value) } : x)); }}/></label><label>Minutes<input type="number" min={5} max={480} value={b.minutes} onChange={e => update("blocks", setup.blocks.map((x, j) => j === i ? { ...x, minutes: Number(e.target.value) } : x))}/></label><button onClick={() => update("blocks", setup.blocks.filter((_, j) => j !== i))}>Remove</button></div>)}<button disabled={setup.blocks.length >= 60} onClick={() => update("blocks", [...setup.blocks, { start: now + setup.blocks.length * 86400000, minutes: 60 }])}>Add study block</button></details>
            <label className="er-check"><input type="checkbox" checked={setup.diagnostic} onChange={e => update("diagnostic", e.target.checked)}/>Calibrate with a short diagnostic (omitted in emergency mode)</label>
        </Plate>
        <Plate title="Choose chapters and your starting confidence" icon={Target}><div className="er-subject-switch">{curriculum.map(s => <button key={s.id} aria-pressed={s.id === subject} onClick={() => setSubject(s.id)}>{s.name}</button>)}</div><label>Find a chapter<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search this subject…"/></label><div className="er-chapter-list">{curriculum.find(s => s.id === subject)!.chapters.filter(c => c.title.toLowerCase().includes(query.toLowerCase())).map(c => { const chosen = setup.chapters.find(x => x.subjectId === subject && x.chapterId === c.id); return <div className="er-chapter" key={c.id}><label className="er-check"><input type="checkbox" checked={!!chosen} disabled={!chosen && setup.chapters.length >= 16} onChange={e => update("chapters", e.target.checked ? [...setup.chapters, { subjectId: subject, chapterId: c.id, confidence: 3 }] : setup.chapters.filter(x => x !== chosen))}/>{c.title}</label>{chosen && <div className="er-confidence" role="group" aria-label={`Confidence for ${c.title}`}>{confidence.map((label, i) => <button key={label} aria-pressed={chosen.confidence === i + 1} onClick={() => update("chapters", setup.chapters.map(x => x === chosen ? { ...x, confidence: i + 1 } : x))}>{label}</button>)}</div>}</div>; })}</div><small>{setup.chapters.length}/16 chapters selected · Confidence guides the start, checked answers guide readiness.</small></Plate>
    </div><div className="er-builder-sources"><Plate title="Choose your study materials" icon={FileText}><p className="er-muted">LAM always teaches. These choices control what it may teach from.</p><div className="er-material-modes">{modes.map(m => <button key={m.id} aria-pressed={setup.materials === m.id} onClick={() => update("materials", m.id)}><m.icon size={23}/><strong>{m.title}</strong><small>{m.text}</small>{setup.materials === m.id && <Check className="er-mode-check" size={15}/>}</button>)}</div><p className="er-muted">Material-only choices never silently fill gaps with outside knowledge. Link-only content is not readable evidence.</p><details open><summary>Add or select your material</summary><Materials compact shortTime={Math.min(setup.minutes, (setup.examAt - now) / 60000) <= 30} subjectId={subject} chapterId={setup.chapters.filter(c => c.subjectId === subject).length === 1 ? setup.chapters.find(c => c.subjectId === subject)?.chapterId : undefined} grade={grade} guest={guest} mode={setup.materials} selected={setup.resourceIds} onSelect={ids => update("resourceIds", ids)}/></details>{guest && <p className="er-callout">Private uploads and live AI require an account. You can build a real local plan and explore the teaching preview.</p>}</Plate></div><aside className="er-builder-preview"><Plate title="Preview your preparation" icon={Sparkles}><LAMVisual state={busy ? "planning" : "attentive"}/><h3>Your teacher. Your time. A clear next step.</h3><ul className="er-preview-features">{["Active teaching with LAM", "Adaptive mission and study timer", "Prioritised sources beside the lesson", "Inline questions and corrections", "Notes, formula dock and mistake memory", "Final review → Scholar Mock Exam"].map(t => <li key={t}><Check size={15}/>{t}</li>)}</ul><span className="er-pill">{urgency}</span><div className="er-plan-preview">{stages.length ? stages.map((kind, i) => <span key={kind}><b>{i + 1}</b>{stageLabels[kind]}</span>) : <p>Select a chapter to preview your mission.</p>}</div><p className="er-muted">{setup.minutes <= 30 ? "Essential concepts, rapid questions and a short final check. No forced breaks or long videos." : "Teaching, practice and recall are weighted toward the chapters that need you most."}</p>{error && <p className="er-error" role="alert">{error}</p>}<button className="er-primary er-build-button" onClick={build} disabled={busy}>{busy ? <><span className="er-spinner"/>Building your preparation…</> : <><Sparkles size={18}/>{initial ? "Update preparation" : "Build my preparation"}<ArrowRight size={18}/></>}</button><small>Uses your actual time budget, not a fixed timetable.</small></Plate></aside></div></div>;
}
