"use client";
import { useState } from "react";
import { ArrowRight, Bookmark, Check, FlaskConical, Lightbulb, Sparkles, TriangleAlert } from "lucide-react";
import { ExamContent as ScholarAIContent } from "./content";
import { currentTask, type ExamSession, type Lesson, type Question } from "@/lib/exam-ready/model";
import { stageLabels } from "@/lib/exam-ready/experience";
import { LAMVisual, Plate } from "./presentation";
import { useLamActivity } from "@/components/lam/lam-avatar";

// Explicit math delimiters are rendered normally. Do not reinterpret an entire
// explanatory sentence containing an equals sign as an unreadable equation.
export function TeacherPanel({ session, lesson, guest, busy, onTeach, onAnswer, onNext, onNote }: { session: ExamSession; lesson?: Lesson; guest: boolean; busy: boolean; onTeach: (pace?: string, request?: string) => void; onAnswer: (q: Question, answer: string) => Promise<boolean>; onNext: (skip?: boolean) => void; onNote: (text: string) => void }) {
    const task = currentTask(session), [doubt, setDoubt] = useState(""), [previewChecked, setPreviewChecked] = useState(false), [previewFeedback, setPreviewFeedback] = useState<boolean | null>(null);
    const checkpoint = lesson?.questions.find(q => !session.attempts.some(a => a.questionId === q.id));
    const last = session.attempts.filter(a => lesson?.questions.some(q => q.id === a.questionId)).at(-1);
    const needsCheck = !!lesson?.questions.length && !last && (!guest || !previewChecked);
    const focusTarget = doubt.trim() ? "input" : ["practice", "recall", "diagnostic", "mock"].includes(task?.kind ?? "") ? "question" : lesson?.concept?.formula ? "formula" : "content";
    const avatarState = useLamActivity(busy ? "thinking" : doubt.trim() ? "listening" : previewFeedback === true ? "happy" : previewFeedback === false ? "helpful" : last?.correct ? "happy" : last && !last.correct ? "helpful" : task?.kind === "mock" ? "exam_focus" : ["practice", "recall", "diagnostic"].includes(task?.kind ?? "") ? "quizzing" : task?.kind === "revise" ? "reviewing" : "teaching", busy, true, focusTarget, "calm", session.setup.examAt);
    return <section className="er-teacher" aria-label="Chapter teaching workspace"><div className="er-lesson-heading"><span className="er-eyebrow">{task ? stageLabels[task.kind] : "Review"} · {task?.topic}</span><h2>{task?.title ?? "Your final preparation"}</h2><p>{task?.objective}</p><details><summary>Why this step?</summary><p>{task?.reason}</p><p>{task?.checkpoint}</p></details></div>
        <div className="er-teacher-message er-plate"><LAMVisual small state={avatarState} target={focusTarget}/><div><div className="er-card-title"><h3>{guest ? "Your offline chapter guide" : "Let’s learn this together."}</h3><span className="er-pill">{guest ? "Offline curriculum guide" : lesson?.grounding ?? "Preparing lesson"}</span></div>{guest && <p className="er-preview-notice">This guide follows your selected chapter and checkpoint. It is not live AI teaching; local checks never count as verified readiness. Sign in for personalised LAM teaching.</p>}{busy && <p className="er-working" role="status"><span className="er-spinner"/>LAM is working. Your last lesson stays visible.</p>}{lesson ? <ScholarAIContent content={lesson.text}/> : <><p>{task?.objective} LAM will explain the idea, work through an example, and ask a question before you move on.</p><div className="er-lesson-skeleton"><i/><i/><i/></div><button disabled={busy} onClick={() => onTeach("normal")}>Start / retry this lesson <Sparkles size={15}/></button></>}</div></div>
        <div className="er-teaching-controls">{[["normal", "Teach this step"], ["faster", "Faster"], ["deeper", "Deeper"], ["example", "Example"], ["another method", "Another method"], ["don’t understand", "I’m confused"], ["quiz", "Quiz"], ["from scratch", "From scratch"]].map(([pace, label]) => <button key={pace} disabled={busy} onClick={() => onTeach(pace)}>{pace === "normal" && <Sparkles size={14}/>} {label}</button>)}</div>
        {lesson?.concept && <div className="er-teaching-blocks"><Plate title="Key concept & formula" icon={Lightbulb} action={<button className="er-icon-button" aria-label="Add concept to notes" onClick={() => onNote(`${lesson.concept!.title}\n${lesson.concept!.explanation}\n${lesson.concept!.formula ?? ""}`)}><Bookmark size={16}/></button>}><h4>{lesson.concept.title}</h4><ScholarAIContent content={lesson.concept.explanation}/>{lesson.concept.formula && <div className="er-formula-feature"><ScholarAIContent content={lesson.concept.formula}/></div>}{lesson.concept.symbols && <p className="er-symbols">{lesson.concept.symbols}</p>}{lesson.concept.conditions && <p className="er-observation">{lesson.concept.conditions}</p>}</Plate>{lesson.example && <Plate title={lesson.example.title} icon={FlaskConical}><ScholarAIContent content={lesson.example.problem}/><ol className="er-worked-steps">{lesson.example.steps.map((step, i) => <li key={i}><span>{i + 1}</span><ScholarAIContent content={step}/></li>)}</ol><div className="er-observation"><ScholarAIContent content={lesson.example.result}/></div></Plate>}</div>}
        {lesson?.takeaway && <p className="er-takeaway"><Lightbulb size={18}/>{lesson.takeaway}</p>}
        {checkpoint && <QuickCheck key={checkpoint.id + (guest ? "-demo" : "")} question={checkpoint} guest={guest} busy={busy} onAnswer={onAnswer} onReviewed={correct => { if (correct !== null) setPreviewChecked(true); setPreviewFeedback(correct); }}/>}
        {!checkpoint && lesson?.questions.length ? <Plate title="Checks completed" icon={Check}><p>You’ve checked every question in this lesson. Recall it in your own words or try a fresh quiz.</p><button disabled={busy} onClick={() => onTeach("quiz")}>Give me another check</button></Plate> : null}
        {last && <div className="er-answer-feedback" data-correct={last.correct} role="status"><strong>{last.correct ? "Correct — here’s why." : "Let’s repair this gap."}</strong><ScholarAIContent content={`${last.expected}\n\n${last.explanation}`}/>{!last.correct && <button disabled={busy} onClick={() => onTeach("another method", `Repair my mistake in ${last.topic}. Explain a different way and ask a fresh question.`)}>Try another method</button>}</div>}
        <form className="er-composer" onSubmit={e => { e.preventDefault(); if (doubt.trim()) { onTeach("normal", doubt); setDoubt(""); } }}><label className="sr-only" htmlFor="er-doubt">Ask a follow-up question</label><input id="er-doubt" value={doubt} maxLength={1800} onChange={e => setDoubt(e.target.value)} placeholder={guest ? "Explore a preview, or sign in to ask your own question…" : "Ask a follow-up, request an example, or tell LAM what’s unclear…"}/><button className="er-primary" disabled={busy || !doubt.trim()} type="submit">Ask LAM <ArrowRight size={16}/></button></form>
        {lesson?.citations.length ? <details className="er-citations"><summary>Grounded in {lesson.citations.length} retrieved sources</summary>{lesson.citations.map(c => <p key={c.id}>{c.url ? <a href={c.url} target="_blank" rel="noopener noreferrer">{c.title}</a> : c.title} · {c.heading}{c.page ? ` · p. ${c.page}` : ""}</p>)}</details> : null}
        {needsCheck && <p className="er-muted" role="status">Try a checkpoint question first, or choose “Already know / skip”. Checking a card alone does not show mastery.</p>}
        <footer className="er-actions er-next"><button disabled={busy || session.status === "completed"} onClick={() => onNext(true)}>Already know / skip</button><button disabled={busy || session.status === "completed" || needsCheck} className="er-primary" onClick={() => onNext()}>Finish checkpoint <ArrowRight size={17}/></button></footer>
    </section>;
}
function QuickCheck({ question: q, guest, busy, onAnswer, onReviewed }: { question: Question; guest: boolean; busy: boolean; onAnswer: (q: Question, answer: string) => Promise<boolean>; onReviewed: (correct: boolean | null) => void }) {
    const [answer, setAnswer] = useState(""), [demoResult, setDemoResult] = useState<boolean | null>(null);
    useLamActivity(demoResult === null ? "idle" : q.kind === "short" ? "reviewing" : demoResult ? "happy" : "helpful", false, true, "question");
    return <Plate className="er-checkpoint" title={guest ? "Local checkpoint" : "Quick check"} icon={Lightbulb}>
        <small>{guest ? "Offline guide · not saved as verified performance" : q.source}</small><h3>{q.question}</h3>
        {q.options ? <div className="er-options">{q.options.map((option, i) => <button key={option} aria-pressed={answer === option} disabled={busy || demoResult !== null} onClick={() => setAnswer(option)}><span>{String.fromCharCode(65 + i)}</span>{option}</button>)}</div> : <label>Your answer<textarea maxLength={3000} value={answer} onChange={e => setAnswer(e.target.value)}/></label>}
        <div className="er-actions"><button className="er-primary" disabled={!answer.trim() || busy || demoResult !== null} onClick={async () => { if (guest) { setDemoResult(q.kind === "short" || answer === q.answer); onReviewed(q.kind === "short" ? null : answer === q.answer); } else if (await onAnswer(q, answer)) setAnswer(""); }}>{guest && q.kind === "short" ? "Compare with curriculum guide" : "Check answer"} <Check size={15}/></button>{demoResult !== null && <button onClick={() => { setDemoResult(null); setAnswer(""); onReviewed(null); }}>Try again</button>}</div>
        {demoResult !== null && <div className="er-answer-feedback" data-correct={q.kind === "short" ? undefined : demoResult} role="status"><strong>{demoResult ? <Check size={17}/> : <TriangleAlert size={17}/>} {q.kind === "short" ? "Self-review — compare your reasoning." : demoResult ? "Correct!" : "A gap worth noticing."}</strong><ScholarAIContent content={q.explanation}/><small>Local guidance only. Your recorded readiness is unchanged.</small></div>}
    </Plate>;
}
