import { DEFAULT_APPEARANCE } from "@/lib/appearance/appearance-defaults";
import { appearanceCore, type AppearanceCoreSettings } from "@/lib/appearance/appearance-schema";

export type AppearancePreset = { id: string; name: string; description: string; swatch: string; patch: Partial<AppearanceCoreSettings> };

export const APPEARANCE_PRESETS: AppearancePreset[] = [
  { id: "scholar-default", name: "Scholar Default", description: "The current Scholar design, unchanged.", swatch: "linear-gradient(135deg,#111827,#312e81)", patch: appearanceCore(DEFAULT_APPEARANCE) },
  { id: "midnight-glass", name: "Midnight Glass", description: "Deep navy with balanced glass.", swatch: "linear-gradient(135deg,#020617,#172554,#4c1d95)", patch: { themeMode: "dark", wallpaper: { ...DEFAULT_APPEARANCE.wallpaper, kind: "gradient", value: "midnight" }, colors: { ...DEFAULT_APPEARANCE.colors, primary: "#8b5cf6", secondary: "#22d3ee" }, surfaces: { ...DEFAULT_APPEARANCE.surfaces, glassStyle: "strong", opacity: 72, blur: 24 } } },
  { id: "deep-space", name: "Deep Space", description: "Quiet cosmic depth for long sessions.", swatch: "radial-gradient(circle at 30% 10%,#312e81,#020617 65%)", patch: { themeMode: "dark", wallpaper: { ...DEFAULT_APPEARANCE.wallpaper, kind: "scholar", value: "deep-space", overlay: 18 }, colors: { ...DEFAULT_APPEARANCE.colors, primary: "#60a5fa", secondary: "#a78bfa" } } },
  { id: "minimal-dark", name: "Minimal Dark", description: "Static surfaces with little decoration.", swatch: "linear-gradient(135deg,#09090b,#27272a)", patch: { themeMode: "dark", wallpaper: { ...DEFAULT_APPEARANCE.wallpaper, kind: "none", value: "none" }, surfaces: { ...DEFAULT_APPEARANCE.surfaces, glassStyle: "off", panelStyle: "solid", shadow: "none", glow: 0 }, motion: { ...DEFAULT_APPEARANCE.motion, level: "reduced", parallax: false, glassShimmer: false } } },
  { id: "minimal-light", name: "Minimal Light", description: "Clean light study surfaces.", swatch: "linear-gradient(135deg,#fff,#e2e8f0)", patch: { themeMode: "light", wallpaper: { ...DEFAULT_APPEARANCE.wallpaper, kind: "none", value: "none" }, surfaces: { ...DEFAULT_APPEARANCE.surfaces, glassStyle: "off", panelStyle: "solid", shadow: "subtle" } } },
  { id: "oled-black", name: "OLED Black", description: "Near-black backgrounds and restrained effects.", swatch: "linear-gradient(135deg,#000,#0a0a0a)", patch: { themeMode: "oled", wallpaper: { ...DEFAULT_APPEARANCE.wallpaper, kind: "none", value: "none" }, surfaces: { ...DEFAULT_APPEARANCE.surfaces, opacity: 94, blur: 8, glow: 0 } } },
  { id: "aurora", name: "Aurora", description: "Teal and violet atmospheric colour.", swatch: "linear-gradient(135deg,#042f2e,#0f766e,#5b21b6)", patch: { themeMode: "dark", wallpaper: { ...DEFAULT_APPEARANCE.wallpaper, kind: "scholar", value: "aurora", overlay: 12 }, colors: { ...DEFAULT_APPEARANCE.colors, primary: "#2dd4bf", secondary: "#c084fc" } } },
  { id: "warm-study", name: "Warm Study", description: "Soft amber tones for evening reading.", swatch: "linear-gradient(135deg,#451a03,#92400e,#f59e0b)", patch: { themeMode: "dark", wallpaper: { ...DEFAULT_APPEARANCE.wallpaper, kind: "scholar", value: "warm-study", overlay: 22 }, colors: { ...DEFAULT_APPEARANCE.colors, primary: "#f59e0b", secondary: "#fb7185" }, reading: { ...DEFAULT_APPEARANCE.reading, theme: "warm" } } },
  { id: "cool-focus", name: "Cool Focus", description: "Calm cyan surfaces and reduced motion.", swatch: "linear-gradient(135deg,#082f49,#164e63,#155e75)", patch: { themeMode: "dark", wallpaper: { ...DEFAULT_APPEARANCE.wallpaper, kind: "gradient", value: "cool-focus" }, colors: { ...DEFAULT_APPEARANCE.colors, primary: "#22d3ee", secondary: "#38bdf8" }, motion: { ...DEFAULT_APPEARANCE.motion, level: "reduced" } } },
  { id: "paper-notebook", name: "Paper Notebook", description: "Book typography on a warm paper surface.", swatch: "linear-gradient(135deg,#fffaf0,#ead7b7)", patch: { themeMode: "light", wallpaper: { ...DEFAULT_APPEARANCE.wallpaper, kind: "scholar", value: "paper" }, typography: { ...DEFAULT_APPEARANCE.typography, bodyFont: "book", headingFont: "book" }, reading: { ...DEFAULT_APPEARANCE.reading, theme: "paper" }, surfaces: { ...DEFAULT_APPEARANCE.surfaces, glassStyle: "off", panelStyle: "solid" } } },
  { id: "exam-mode", name: "Exam Mode", description: "High readability without decorative motion.", swatch: "linear-gradient(135deg,#111827,#1f2937,#f8fafc)", patch: { themeMode: "dark", examAppearance: true, wallpaper: { ...DEFAULT_APPEARANCE.wallpaper, kind: "none", value: "none", videoEnabled: false }, motion: { ...DEFAULT_APPEARANCE.motion, level: "off", pageTransitions: false, hoverMotion: false, backgroundAnimation: false }, accessibility: { ...DEFAULT_APPEARANCE.accessibility, increaseTextContrast: true, thickFocus: true } } },
  { id: "high-contrast", name: "High Contrast", description: "Stronger borders, focus, and text contrast.", swatch: "linear-gradient(135deg,#000 50%,#fff 50%)", patch: { themeMode: "oled", accessibility: { ...DEFAULT_APPEARANCE.accessibility, highContrast: true, increaseTextContrast: true, underlineLinks: true, thickFocus: true, largeTargets: true } } },
];

export function applyPreset(current: AppearanceCoreSettings, preset: AppearancePreset): AppearanceCoreSettings {
  return { ...current, ...structuredClone(preset.patch), preset: preset.id, schemaVersion: 1 } as AppearanceCoreSettings;
}
