import { beforeEach, expect, mock, test } from "bun:test";
import { createSession } from "../src/lib/exam-ready/planner";
import type { ExamSession, Setup } from "../src/lib/exam-ready/model";
mock.module("server-only",()=>({}));
let user:string|null="owner",allowed=true,rows=new Map<string,{owner:string;state:ExamSession;revision:number;lease:boolean}>(),aiCalls=0;
const db={
  $queryRaw:async(strings:TemplateStringsArray,...values:unknown[])=>{const sql=strings.join("?");if(sql.includes('FROM "User"'))return [{id:values[0]}];if(sql.includes("COUNT"))return [{count:BigInt([...rows.values()].filter(r=>r.owner===values[0]).length)}];if(sql.includes('"id"=?')){const r=rows.get(values[0] as string);return r&&r.owner===values[1]?[{state:structuredClone(r.state),revision:r.revision}]:[];}return [...rows.values()].filter(r=>r.owner===values[0]).map(r=>({state:structuredClone(r.state),revision:r.revision}));},
  $executeRaw:async(strings:TemplateStringsArray,...values:unknown[])=>{const sql=strings.join("?");if(sql.includes("INSERT")){rows.set(values[0] as string,{owner:values[1] as string,state:JSON.parse(values[2] as string),revision:0,lease:false});return 1;}const save=sql.includes('SET "state"'),[id,owner,revision]=save?values.slice(1):values;const r=rows.get(id as string);if(!r||r.owner!==owner||r.revision!==revision)return 0;if(save){if(sql.includes('AND "leaseUntil">NOW()')?!r.lease:r.lease)return 0;r.state=JSON.parse(values[0] as string);r.revision++;r.lease=false;return 1;}if(sql.includes("INTERVAL")){if(r.lease)return 0;r.lease=true;return 1;}r.lease=false;return 1;},
  $transaction:async(fn:(tx:unknown)=>unknown)=>fn(db),
};
mock.module("@/lib/db",()=>({db}));
mock.module("@/lib/auth/session",()=>({getSessionUser:async()=>user?{id:user}:null}));
mock.module("@/lib/exam-ready/access",()=>({examAccess:async()=>({allowed,source:"temporary_free",freeUntil:null})}));
mock.module("@/lib/security/rate-limit",()=>({enforceRateLimit:async()=>{},RateLimitError:class extends Error{}}));
mock.module("@/lib/subscriptions/entitlements",()=>({resolveUserEntitlements:async()=>({entitlementsLoaded:true,entitlements:[]})}));
mock.module("@/lib/exam-ready/teacher",()=>({teachingStyles:["normal","quiz"],teacherContext:(_s:unknown,_pace:string,question:string)=>question,lessonKey:()=>"v1-0:test",teach:async()=>{aiCalls++;return {text:"A real chapter explanation, with a checkpoint.",formulas:["F = ma"],grounding:"general AI explanation",citations:[],questions:[{id:"q1",subjectId:"physics",chapterId:"p5",topic:"Inertia",kind:"mcq",question:"Which statement explains inertia?",options:["a","b","c","d"],answer:"b",explanation:"Inertia resists a change in motion.",source:"Scholar AI-generated"}]};},completeJSON:async(_user:string,prompt:string)=>prompt.includes("Create exactly")?{text:"A chapter-specific mock test with source restrictions.",formulas:[],questions:Array.from({length:Number(prompt.match(/Create exactly (\d+)/)?.[1]??2)},(_,i)=>({subjectId:"physics",chapterId:"p5",topic:"Inertia",kind:"mcq",question:`Application question ${i+1}: which inertia statement?`,options:["a","b","c","d"],answer:"b",explanation:"Check the concept carefully."}))}:{correct:false,feedback:"Needs work"}}));
mock.module("@/lib/exam-ready/materials",()=>({selectMaterials:async()=>({resources:[],sources:[],restricted:false})}));
const list=await import("../src/app/api/exam-ready/route"),detail=await import("../src/app/api/exam-ready/[id]/route"),teacher=await import("../src/app/api/exam-ready/[id]/teacher/route");
const examMock=await import("../src/app/api/exam-ready/[id]/mock/route");
const now=Date.now(),config:Setup={exam:"Physics",grade:11,board:"CBSE",examAt:now+86400000,minutes:120,format:"mixed",style:"step-by-step",chapters:[{subjectId:"physics",chapterId:"p5",confidence:2}],materials:"personal",resourceIds:[],blocks:[],diagnostic:true};
const request=(body:unknown,method="POST",origin="http://localhost")=>new Request("http://localhost/api/exam-ready",{method,headers:{"Content-Type":"application/json",origin},body:JSON.stringify(body)});
const context=(id="s")=>({params:Promise.resolve({id})});
beforeEach(()=>{user="owner";allowed=true;rows=new Map();aiCalls=0;});
test("account creation persists owned aggregate without exposing answers",async()=>{const r=await list.POST(request(config));expect(r.status).toBe(201);expect(rows.size).toBe(1);expect([...rows.values()][0].owner).toBe("owner");});
test("guest can see rollout policy, not account sessions",async()=>{rows.set("s",{owner:"victim",state:createSession("s",config),revision:0,lease:false});user=null;const r=await list.GET();expect((await r.json()).sessions).toEqual([]);expect((await list.POST(request(config))).status).toBe(401);});
test("cross-site mutation blocked before persistence",async()=>{expect((await list.POST(request(config,"POST","https://evil.example"))).status).toBe(403);expect(rows.size).toBe(0);});
test("disabled feature blocks server mutation",async()=>{allowed=false;expect((await list.POST(request(config))).status).toBe(403);});
test("grade entitlement remains enforced despite temporary free Exam Ready",async()=>{const setup={...config,grade:9,chapters:[{subjectId:"maths",chapterId:"m1",confidence:2}]};expect((await list.POST(request(setup))).status).toBe(403);});
test("cross-user read, edit and teaching return 404",async()=>{rows.set("s",{owner:"victim",state:createSession("s",config),revision:0,lease:false});expect((await detail.GET(new Request("http://localhost/api/exam-ready/s"),context())).status).toBe(404);expect((await detail.PATCH(request({revision:0,action:{type:"notes",text:"steal",important:false}},"PATCH"),context())).status).toBe(404);expect((await teacher.POST(request({revision:0,pace:"normal"}),context())).status).toBe(404);expect(aiCalls).toBe(0);});
test("stale revision cannot overwrite newer notes",async()=>{rows.set("s",{owner:"owner",state:createSession("s",config),revision:2,lease:false});expect((await detail.PATCH(request({revision:1,action:{type:"notes",text:"old",important:false}},"PATCH"),context())).status).toBe(409);expect(rows.get("s")!.state.notes).toBe("");});
test("teaching persists and hides answer key until submission",async()=>{rows.set("s",{owner:"owner",state:createSession("s",config),revision:0,lease:false});const r=await teacher.POST(request({revision:0,pace:"normal"}),context());expect(r.status).toBe(200);const v=await r.json();expect(v.session.lessons["v1-0:test"].questions[0].answer).toBe("");expect(rows.get("s")!.state.lessons["v1-0:test"].questions[0].answer).toBe("b");expect(rows.get("s")!.lease).toBe(false);});
test("cached teacher turn avoids another provider call",async()=>{rows.set("s",{owner:"owner",state:createSession("s",config),revision:0,lease:false});await teacher.POST(request({revision:0,pace:"normal"}),context());expect((await teacher.POST(request({revision:1,pace:"normal"}),context())).status).toBe(200);expect(aiCalls).toBe(1);});
test("client cannot supply its own score or correct flag",async()=>{rows.set("s",{owner:"owner",state:createSession("s",config),revision:0,lease:false});await teacher.POST(request({revision:0,pace:"normal"}),context());const r=await detail.PATCH(request({revision:1,action:{type:"answer",questionId:"q1",answer:"a",correct:true,score:100}},"PATCH"),context());expect(r.status).toBe(200);expect((await r.json()).session.attempts[0].correct).toBe(false);});
test("answers outside the active question set rejected",async()=>{rows.set("s",{owner:"owner",state:createSession("s",config),revision:0,lease:false});expect((await detail.PATCH(request({revision:0,action:{type:"answer",questionId:"victim-question",answer:"x"}},"PATCH"),context())).status).toBe(409);});

test("mock questions cannot be scored through the teaching checkpoint endpoint",async()=>{rows.set("s",{owner:"owner",state:createSession("s",{...config,format:"mcq"}),revision:0,lease:false});const paper=await (await examMock.POST(request({type:"generate"}),context())).json();const r=await detail.PATCH(request({revision:1,action:{type:"answer",questionId:paper.questions[0].id,answer:"b"}},"PATCH"),context());expect(r.status).toBe(409);expect(rows.get("s")!.state.attempts).toHaveLength(0);});
test("lease blocks racing checklist writes",async()=>{rows.set("s",{owner:"owner",state:createSession("s",config),revision:0,lease:true});expect((await detail.PATCH(request({revision:0,action:{type:"next"}},"PATCH"),context())).status).toBe(409);});
test("bounded request reader rejects excessive notes",async()=>{expect((await list.POST(request({...config,exam:"x".repeat(30000)}))).status).toBe(413);});
test("mock cannot read or generate another account's session",async()=>{rows.set("s",{owner:"victim",state:createSession("s",config),revision:0,lease:false});expect((await examMock.POST(request({type:"generate"}),context())).status).toBe(404);});
test("mock adapter saves exact paper and grades server answers",async()=>{const state=createSession("s",{...config,format:"mcq"});rows.set("s",{owner:"owner",state,revision:0,lease:false});const generated=await examMock.POST(request({type:"generate"}),context());expect(generated.status).toBe(200);const paper=await generated.json();expect(paper.questions.length).toBe(paper.config.numQuestions);const responses=Object.fromEntries(paper.questions.map((q:{id:string})=>[q.id,"a"]));const r=await examMock.POST(request({type:"submit",responses,score:100}),context());expect(r.status).toBe(200);const result=await r.json();expect(result.score).toBe(0);expect(result.session.mock.verified).toBe(true);expect(result.session.attempts.every((a:{kind:string;correct:boolean})=>a.kind==="mock"&&!a.correct)).toBe(true);});
test("mock resubmission cannot duplicate evidence",async()=>{rows.set("s",{owner:"owner",state:createSession("s",{...config,format:"mcq"}),revision:0,lease:false});await examMock.POST(request({type:"generate"}),context());await examMock.POST(request({type:"submit",responses:{}}),context());expect((await examMock.POST(request({type:"submit",responses:{}}),context())).status).toBe(409);});
