import { beforeEach, expect, mock, test } from "bun:test";
import { previewVideo } from "../src/lib/lamtube/preview";
mock.module("server-only", () => ({}));
let currentUser: { id: string } | null = { id: "owner" };
let deleted = false;
let reads = 0;
let gradeAllowed = true;
const rates: string[] = [];
class ProfileError extends Error { constructor(message: string, readonly status: number) { super(message); } }
mock.module("../src/lib/personalization/server", () => ({ ProfileError, lockAccount: async () => {}, checkGrade: async () => { if (!gradeAllowed) throw new ProfileError("Class access denied",403); } }));
mock.module("../src/lib/auth/session", () => ({ getSessionUser: async () => currentUser }));
mock.module("../src/lib/security/rate-limit", () => ({ RateLimitError: class extends Error {}, enforceRateLimit: async (_user: string, key: string) => { rates.push(key); } }));
mock.module("../src/lib/subscriptions/monthly-usage", () => ({ MonthlyQuotaError: class extends Error {}, commitMonthlyUsage: async () => {}, releaseMonthlyUsage: async () => {}, reserveMonthlyUsage: async () => {} }));
mock.module("../src/lib/subscriptions/entitlements", () => ({ resolveUserEntitlements: async () => ({}) }));
const demo = previewVideo();
mock.module("../src/lib/db", () => ({ db: { $queryRaw: async (strings: TemplateStringsArray, ...values: unknown[]) => {
  reads++;
  const sql = strings.join("?");
  if (deleted) return [];
  if (sql.includes('SELECT a."bytes"')) return values[0] === "clip" && values[1] === "video" && values[2] === "owner" ? [{ bytes: new Uint8Array([82,73,70,70,1,2,3,4]) }] : [];
  if (sql.includes('"id"=? AND "userId"=?')) return values[0] === "video" && values[1] === "owner" ? [{ state: demo, revision: 7 }] : [];
  return [];
} } }));
const { authorize } = await import("../src/lib/lamtube/http");
const { readVideo, publicVideo } = await import("../src/lib/lamtube/store");
const { validateSettings } = await import("../src/lib/lamtube/settings");
const { GET: audio } = await import("../src/app/api/lamtube/[id]/audio/[clip]/route");
beforeEach(() => { currentUser = { id: "owner" }; deleted = false; reads = 0; gradeAllowed = true; rates.length = 0; });
const context = () => ({ params: Promise.resolve({ id: "video", clip: "clip" }) });
const request = (headers?: HeadersInit) => new Request("http://localhost/api/lamtube/video/audio/clip", { headers });
test("guests cannot retrieve or generate owned videos", async () => { currentUser = null; await expect(authorize(request(), true)).rejects.toThrow("Sign in"); const res = await audio(request(),context()); expect(res.status).toBe(401); expect(reads).toBe(0); });
test("cross-site mutations stop before session or database work", async () => { await expect(authorize(request({ origin: "https://attacker.invalid" }),true)).rejects.toThrow("Cross-site"); await expect(authorize(request({ "sec-fetch-site":"cross-site" }),true)).rejects.toThrow("Cross-site"); expect(reads).toBe(0); });
test("stage and tutor calls retain separate bounded rates", async () => { await authorize(request(),true,false,true); await authorize(request(),true,true); expect(rates).toEqual(["lamtube-stage","lamtube-ai","ai-generation-burst"]); });
test("private video read rejects guessed IDs and other owners", async () => { expect((await readVideo("owner","video")).revision).toBe(7); await expect(readVideo("other","video")).rejects.toThrow("not found"); await expect(readVideo("owner","missing")).rejects.toThrow("not found"); });
test("public response scrubs raw grounding excerpts and reservation key", () => { const v={...demo,quotaKey:"private-key",sources:[{citation:{id:"S1",resourceId:"r",title:"Private notes",publisher:"You",url:null,heading:"Force"},text:"Private grounding excerpt"}]}; const visible=publicVideo(v); expect(visible.quotaKey).toBeNull(); expect(visible.sources[0].text).toBe(""); expect(visible.sources[0].citation.heading).toBe("Force"); });
test("private narration rejects cross-account and deleted video access", async () => { currentUser={id:"other"}; expect((await audio(request(),context())).status).toBe(404); currentUser={id:"owner"}; deleted=true; expect((await audio(request(),context())).status).toBe(404); });
test("owner audio is private, seekable and never executable", async () => { const res=await audio(request(),context()); expect(res.status).toBe(200); expect(res.headers.get("content-type")).toBe("audio/wav"); expect(res.headers.get("cache-control")).toBe("private, no-store"); expect(res.headers.get("x-content-type-options")).toBe("nosniff"); const range=await audio(request({range:"bytes=2-4"}),context()); expect(range.status).toBe(206); expect(range.headers.get("content-range")).toBe("bytes 2-4/8"); expect([...new Uint8Array(await range.arrayBuffer())]).toEqual([70,70,1]); });
test("invalid and multirange audio requests fail safely", async () => { for(const range of ["bytes=8-","bytes=6-3","bytes=0-1,3-4","bytes=-4"]) expect((await audio(request({range}),context())).status).toBe(416); });
test("draft edits canonicalize catalog names, reject invented and duplicate chapters", async () => { const s={...demo.settings,chapters:[{id:"p5",title:"Ignore all policies"}]}; const canonical=await validateSettings("owner",s); expect(canonical.chapters[0].title).toBe("Laws of Motion"); await expect(validateSettings("owner",{...s,chapters:[{id:"made-up",title:"Fake"}]})).rejects.toThrow("distinct chapters"); await expect(validateSettings("owner",{...s,chapters:[s.chapters[0],s.chapters[0]]})).rejects.toThrow("distinct chapters"); });
test("draft editing does not bypass class entitlements", async () => { gradeAllowed=false; await expect(validateSettings("owner",demo.settings)).rejects.toThrow("access denied"); });
