import { test, expect } from "bun:test";
import { renderToStaticMarkup } from "react-dom/server";
import { createRef } from "react";
import { settingsSchema, scenePlanSchema, assembleTimeline, generationProgress, initialVideo } from "../src/lib/lamtube/model";
import { frame, locate, contextAt, clockLabel } from "../src/lib/lamtube/timeline";
import { previewVideo } from "../src/lib/lamtube/preview";
import { wavInfo } from "../src/lib/lamtube/wav";
import { aiVideoMonthlyLimit } from "../src/lib/lamtube/access";
import type { ResolvedEntitlements } from "../src/lib/subscriptions/entitlements";
import { SceneCanvas } from "../src/components/lamtube/scene-canvas";
import { isScholarRoute } from "../src/lib/routes";
const video = previewVideo(), timeline = video.timeline!;
const access = (plan: string, loaded = true, authenticated = true) => ({ plan, entitlementsLoaded: loaded, authenticated }) as ResolvedEntitlements;
test("Free has ten monthly full videos, verified Plus has no count cap", () => { expect(aiVideoMonthlyLimit(access("FREE"))).toBe(10); for (const p of ["PLUS","DEVELOPER","UNLOCKED"]) expect(aiVideoMonthlyLimit(access(p))).toBe(Infinity); });
test("unverified plan fails closed and guests cannot generate", () => { expect(aiVideoMonthlyLimit(access("PLUS",false))).toBe(10); expect(aiVideoMonthlyLimit(access("FREE",true,false))).toBe(0); });
test("source-only generation requires explicit sources", () => { expect(settingsSchema.safeParse({...video.settings,strictSources:true}).success).toBe(false); });
test("settings reject unknown execution and extra chapter metadata", () => { expect(settingsSchema.safeParse({...video.settings,execute:"alert(1)"}).success).toBe(false); expect(settingsSchema.safeParse({...video.settings,chapters:[{id:"p5",title:"Laws",script:"x"}]}).success).toBe(false); });
test("scenes whitelist primitives, properties and bounded geometry", () => { const plan=video.plans[0]; expect(scenePlanSchema.safeParse({...plan,elements:[{...plan.elements[0],kind:"script"},...plan.elements.slice(1)]}).success).toBe(false); expect(scenePlanSchema.safeParse({...plan,elements:[{...plan.elements[0],onClick:"fetch('/secret')"},...plan.elements.slice(1)]}).success).toBe(false); expect(scenePlanSchema.safeParse({...plan,elements:[{...plan.elements[0],x:Infinity},...plan.elements.slice(1)]}).success).toBe(false); });
test("a paragraph slideshow cannot pass the scene schema", () => { const plan=video.plans[0]; expect(scenePlanSchema.safeParse({...plan,elements:plan.elements.map(e=>({...e,kind:"label"})),cues:plan.cues.map(c=>({...c,effect:"reveal"}))}).success).toBe(false); });
test("duplicate IDs and dangling phrase references are rejected", () => { const p=video.plans[0]; expect(scenePlanSchema.safeParse({...p,elements:[...p.elements,p.elements[0]]}).success).toBe(false); expect(scenePlanSchema.safeParse({...p,cues:[{...p.cues[0],phrase:39},...p.cues.slice(1)]}).success).toBe(false); });
test("narration clips determine total duration, not the requested minutes", () => { expect(timeline.duration).toBe(49); expect(timeline.scenes[1].start).toBe(28); });
test("incomplete or invalid narration cannot become a ready timeline", () => { expect(()=>assembleTimeline(video.plans,[[]])).toThrow(); expect(()=>assembleTimeline(video.plans,video.clips.map(c=>c.map(x=>({...x,duration:NaN}))))).toThrow(); });
test("seek identifies the exact caption/audio offset at boundaries", () => { expect(locate(timeline,7).clipIndex).toBe(1); expect(locate(timeline,7).clipTime).toBe(0); expect(locate(timeline,28).sceneIndex).toBe(1); expect(locate(timeline,29).clipTime).toBe(1); });
test("negative, invalid and end seeks are clamped", () => { expect(locate(timeline,-10).local).toBe(0); expect(locate(timeline,NaN).local).toBe(0); expect(locate(timeline,999).sceneIndex).toBe(1); });
for(const t of [0,1,6.5,14,18.5,27.9,28,40,48.99]) test(`seek reconstruction is independent of prior playback at ${t}s`,()=>{ const at=locate(timeline,t); const expected=frame(at.scene,at.local); for(const earlier of [48,2,30,0,17]){const other=locate(timeline,earlier);frame(other.scene,other.local);} expect(frame(at.scene,at.local)).toEqual(expected); });
test("objects and graphs really evolve, not only text fades",()=>{const s=timeline.scenes[0];expect(frame(s,20).elements.get("block")!.dx).toBeGreaterThan(frame(s,14).elements.get("block")!.dx);const graph=timeline.scenes[1];expect(frame(graph,12).elements.get("line")!.draw).toBeGreaterThan(frame(graph,6).elements.get("line")!.draw);});
test("reduced motion retains readable pedagogical states, without camera/pulse",()=>{const s=timeline.scenes[0],f=frame(s,22,true);expect(f.camera.zoom).toBe(1);expect(f.camera.x).toBe(0);expect([...f.elements.values()].every(e=>e.scale===1)).toBe(true);expect(f.elements.get("law")!.opacity).toBe(1);});
test("moment context uses actual scene, caption and visible state",()=>{const c=contextAt(timeline,29);expect(c.title).toBe("Read the relationship");expect(c.narration).toContain("Plot net force");expect(c.visibleElements.some(e=>e.text==="F = m a")).toBe(false);});
test("progress reflects completed persisted stages",()=>{const v=initialVideo("draft",video.settings,0);expect(generationProgress(v)).toBe(2);v.stage="scenes";v.outline={summary:"Two scenes",scenes:video.plans.map(p=>({title:p.title,goal:p.goal,chapterId:p.chapterId}))};v.plans=[video.plans[0]];expect(generationProgress(v)).toBe(30);expect(generationProgress(video)).toBe(100);});
test("SVG labels are escaped, never rendered as executable HTML",()=>{const scene={...timeline.scenes[0],elements:timeline.scenes[0].elements.map(e=>({...e,text:'<script>alert(1)</script>'}))};const html=renderToStaticMarkup(<SceneCanvas scene={scene} svgRef={createRef()}/>);expect(html).not.toContain("<script>");expect(html).toContain("&lt;script&gt;");});
test("old video links and new branding routes remain valid",()=>{expect(isScholarRoute(["nigtube"])).toBe(true);expect(isScholarRoute(["lamtube"])).toBe(true);expect(isScholarRoute(["lamtube","other"])).toBe(false);});
test("clock labels are stable and use real seconds",()=>{expect(clockLabel(70.9)).toBe("1:10");expect(clockLabel(-4)).toBe("0:00");});
function wav(seconds=2){const bytes=new Uint8Array(44+seconds*32000),v=new DataView(bytes.buffer);const word=(offset:number,text:string)=>{[...text].forEach((c,i)=>bytes[offset+i]=c.charCodeAt(0));};word(0,"RIFF");v.setUint32(4,bytes.length-8,true);word(8,"WAVE");word(12,"fmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,16000,true);v.setUint32(28,32000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);word(36,"data");v.setUint32(40,bytes.length-44,true);return bytes;}
test("WAV duration is parsed from PCM, not fabricated speech speed",()=>{expect(wavInfo(wav(3)).duration).toBe(3);});
test("truncated/non-WAV provider output cannot publish",()=>{expect(()=>wavInfo(new Uint8Array(50))).toThrow();expect(()=>wavInfo(wav().slice(0,50))).toThrow();});
