import {beforeEach,describe,expect,mock,test} from "bun:test";
import type {LearningProfile,CustomEbook} from "@prisma/client";
import {NextRequest,NextResponse} from "next/server";
import {DEFAULT_PREFERENCES,BONUS_BYTES} from "../src/lib/personalization/schema";
mock.module("server-only",()=>({}));
const backgroundTasks: (()=>unknown)[]=[];
mock.module("next/server",()=>({NextRequest,NextResponse,after:(task:()=>unknown)=>backgroundTasks.push(task)}));
let actor:string|null="owner";let plus=false;let failBooks=false;let aiCalls=0;let analysisDenied=false;
let pdfScripts=false;let normalReservations=0;let normalReleases=0;let parserTransfers=0;let createAttempts=0;
type StoredBook=CustomEbook & {resource?:{id:string;visibility:string;ownerUserId:string;job:unknown}};
const profiles=new Map<string,LearningProfile>();const books=new Map<string,StoredBook>();const events:string[]=[];
const fresh=(userId:string):LearningProfile=>({userId,required:true,version:1,revision:0,status:"NOT_STARTED",stage:0,preferences:JSON.parse(JSON.stringify(DEFAULT_PREFERENCES)),result:{},jobToken:null,jobStartedAt:null,completedAt:null,skippedAt:null,bonusUsedBytes:0,bonusClosedAt:null,updatedAt:new Date()});
const profileDb={
  findUnique:async({where}:{where:{userId:string}})=>profiles.get(where.userId)??null,
  upsert:async({where}:{where:{userId:string}})=>{if(!profiles.has(where.userId))profiles.set(where.userId,fresh(where.userId));return profiles.get(where.userId)!;},
  update:async({where,data}:{where:{userId:string};data:Record<string,unknown>})=>{const previous=profiles.get(where.userId)!;const next={...previous,...data,revision:typeof data.revision==="object" ? previous.revision+1 : previous.revision,bonusUsedBytes:typeof data.bonusUsedBytes==="object" ? previous.bonusUsedBytes+Number((data.bonusUsedBytes as {increment:number}).increment) : previous.bonusUsedBytes} as LearningProfile;profiles.set(where.userId,next);return next;},
  updateMany:async({where,data}:{where:{userId:string;jobToken:string};data:Record<string,unknown>})=>{if(profiles.get(where.userId)?.jobToken!==where.jobToken)return{count:0};await profileDb.update({where,data});return{count:1};},
};
const bookDb={
  findUnique:async({where}:{where:{userId_importKey:{userId:string;importKey:string}}})=>[...books.values()].find(b=>b.userId===where.userId_importKey.userId && b.importKey===where.userId_importKey.importKey)??null,
  findFirst:async({where}:{where:{userId:string;OR:{importDigest?:string;importKey?:string}[]}})=>[...books.values()].find(b=>b.userId===where.userId && !b.deletedAt && where.OR.some(item=>item.importDigest===b.importDigest || item.importKey===b.importKey))??null,
  aggregate:async()=>({_sum:{sizeBytes:0}}),
  create:async({data}:{data:Record<string,unknown>})=>{createAttempts++;if(failBooks)throw new Error("write failed");const nested=data.resource as {create:Record<string,unknown>}|undefined;const book={id:crypto.randomUUID(),deletedAt:null,...data,...(nested?{resource:{id:crypto.randomUUID(),...nested.create}}:{})} as StoredBook;books.set(book.id,book);return book;},
  findMany:async({where}:{where:{userId:string}})=>[...books.values()].filter(b=>b.userId===where.userId && !b.deletedAt),
};
const tx={learningProfile:profileDb,customEbook:bookDb,storedFile:{aggregate:async()=>({_sum:{sizeBytes:0}})},studyResource:{findFirst:async()=>null},user:{findUniqueOrThrow:async()=>({currentScholarClass:11}),update:async()=>({})},$queryRaw:async()=>[]};
let queue=Promise.resolve();
const db={...tx,practiceAttempt:{count:async()=>2},revisionItem:{count:async()=>3},$transaction:<T>(fn:(transaction:typeof tx)=>Promise<T>)=>{const next=queue.then(async()=>{const snapshot=new Map([...profiles].map(([k,v])=>[k,structuredClone(v)]));const stored=new Map(books);try{return await fn(tx);}catch(e){profiles.clear();for(const [k,v]of snapshot)profiles.set(k,v);books.clear();for(const [k,v]of stored)books.set(k,v);throw e;}});queue=next.then(()=>{},()=>{});return next;}};
mock.module("../src/lib/db",()=>({db}));
mock.module("../src/lib/auth/session",()=>({getSessionUser:async()=>actor ? {id:actor}:null}));
mock.module("../src/lib/subscriptions/entitlements",()=>({resolveUserEntitlements:async()=>({entitlementsLoaded:true,entitlements:plus?["class_9_access"]:[],storageLimitBytes:10_000_000})}));
mock.module("../src/lib/subscriptions/audit",()=>({recordAudit:async(event:string)=>{events.push(event);}}));
class RateLimitError extends Error{}
mock.module("../src/lib/security/rate-limit",()=>({RateLimitError,enforceRateLimit:async(_id:string,action:string)=>{if(action==="personalization-analysis" && analysisDenied)throw new RateLimitError();}}));
mock.module("../src/lib/ai/scholar-groq",()=>({generateScholarGroqJSON:async()=>{aiCalls++;throw new Error("provider unavailable");}}));
class MonthlyQuotaError extends Error {code="MONTHLY_LIMIT";limit=3;}
mock.module("../src/lib/subscriptions/monthly-usage",()=>({MonthlyQuotaError,reserveMonthlyUsage:async()=>{normalReservations++;return{replayed:false};},commitMonthlyUsage:async()=>{},releaseMonthlyUsage:async()=>{normalReleases++;},getMonthlyUsage:async()=>({ebookUploads:{used:0,limit:3}})}));
mock.module("pdfjs-dist/legacy/build/pdf.mjs",()=>({getDocument:({data}:{data:Uint8Array})=>{structuredClone(data,{transfer:[data.buffer]});parserTransfers++;return{promise:Promise.resolve({numPages:1,hasJSActions:async()=>pdfScripts,getPage:async()=>({getTextContent:async()=>({items:[{str:"A sufficiently long and genuinely extracted study paragraph."}]}),cleanup:()=>{}})}),destroy:async()=>{}};}}));
// Execute the real extraction adapter after durable dispatch; leasing/indexing
// are covered separately by resource-jobs.test.ts, not replaced by this double.
mock.module("../src/lib/resources/jobs",()=>({processResourceJob:async(resourceId:string,ownerUserId:string)=>{const book=[...books.values()].find(b=>b.resource?.id===resourceId && b.userId===ownerUserId);if(!book)return false;const {extractPdf}=await import("../src/lib/resources/pdf");const pdf=await extractPdf(book.pdfBytes);Object.assign(book,{pageCount:pdf.pageCount,text:pdf.text,pageTexts:pdf.pages,processingStatus:pdf.needsOcr?"needs_ocr":"ready"});return true;}}));
const {GET,PATCH}=await import("../src/app/api/personalization/route");
const {POST}=await import("../src/app/api/personalization/analyze/route");
const {storeBonusBook}=await import("../src/lib/personalization/server");
const ebookRoute=await import("../src/app/api/ebooks/route");
const request=(body:unknown)=>new NextRequest("http://localhost/api/personalization",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
const bookData={title:"Notes",originalFileName:"notes.pdf",sizeBytes:100,pageCount:1,text:"Study material",pageTexts:["Study material"],pdfBytes:Buffer.from("%PDF-1.7")};
beforeEach(()=>{actor="owner";plus=false;failBooks=false;aiCalls=0;analysisDenied=false;pdfScripts=false;normalReservations=0;normalReleases=0;parserTransfers=0;createAttempts=0;profiles.clear();books.clear();events.length=0;backgroundTasks.length=0;queue=Promise.resolve();});
describe("Personalization server boundaries",()=>{
  test("Guest cannot read or mutate profile",async()=>{actor=null;expect((await GET()).status).toBe(401);expect((await PATCH(request({action:"begin",revision:0}))).status).toBe(401);expect((await POST(request({revision:0}))).status).toBe(401);});
  test("first login absent profile is required; seeded existing account invited",async()=>{expect((await (await GET()).json()).required).toBe(true);profiles.set("owner",{...fresh("owner"),required:false});expect((await (await GET()).json()).required).toBe(false);});
  test("server draft survives subsequent reads",async()=>{expect((await PATCH(request({action:"begin",revision:0,stage:1}))).status).toBe(200);expect((await PATCH(request({action:"save",revision:1,stage:7,preferences:{...DEFAULT_PREFERENCES,dailyGoal:45}}))).status).toBe(200);const data=await(await GET()).json();expect(data.stage).toBe(7);expect(data.preferences.dailyGoal).toBe(45);expect(data.revision).toBe(2);});
  test("expired exams remain readable and never prevent global skip",async()=>{profiles.set("owner",{...fresh("owner"),preferences:{...DEFAULT_PREFERENCES,dailyGoal:45,style:"Short and direct",exam:{name:"Past exam",date:"2000-01-01",subjects:[]}}});const saved=await(await GET()).json();expect(saved.preferences.dailyGoal).toBe(45);expect(saved.preferences.exam.name).toBe("Past exam");expect((await PATCH(request({action:"skip",revision:0}))).status).toBe(200);expect((await(await GET()).json()).preferences.style).toBe("Short and direct");});
  test("user cannot select another owner in payload",async()=>{expect((await PATCH(request({action:"begin",revision:0,userId:"victim"}))).status).toBe(400);expect(profiles.has("victim")).toBe(false);});
  test("reads and saves scope to session account",async()=>{profiles.set("victim",{...fresh("victim"),preferences:{...DEFAULT_PREFERENCES,dailyGoal:200}});expect((await(await GET()).json()).preferences.dailyGoal).toBe(30);await PATCH(request({action:"begin",revision:0}));expect((profiles.get("victim")!.preferences as {dailyGoal:number}).dailyGoal).toBe(200);});
  test("fake completed status cannot be posted",async()=>expect((await PATCH(request({action:"complete",revision:0}))).status).toBe(400));
  test("invalid body and unsupported grade are rejected",async()=>{expect((await PATCH(request({action:"save",revision:0,preferences:{grade:12}}))).status).toBe(400);expect((await PATCH(request({action:"save",revision:0,preferences:{grade:9}}))).status).toBe(403);});
  test("oversized JSON rejected before profile writes",async()=>{expect((await PATCH(request({padding:"x".repeat(20000)}))).status).toBe(413);expect(profiles.size).toBe(0);});
  test("multi-tab stale writes cannot overwrite answers",async()=>{await PATCH(request({action:"begin",revision:0}));expect((await PATCH(request({action:"save",revision:0,stage:9}))).status).toBe(409);expect(profiles.get("owner")!.stage).toBe(0);});
  test("skip permanently closes remaining bonus; begin cannot reset it",async()=>{await PATCH(request({action:"begin",revision:0}));await PATCH(request({action:"skip",revision:1}));await PATCH(request({action:"begin",revision:2}));expect(profiles.get("owner")!.bonusClosedAt).not.toBeNull();await expect(storeBonusBook("owner","import-ref-key-1","digest",bookData)).rejects.toThrow("closed");});
  test("bonus actual bytes charged only on atomic successful creation",async()=>{profiles.set("owner",{...fresh("owner"),status:"IN_PROGRESS"});await storeBonusBook("owner","import-ref-key-1","digest",bookData);expect(profiles.get("owner")!.bonusUsedBytes).toBe(100);expect([...books.values()][0].allocation).toBe("onboarding");});
  test("failed write leaves bonus unchanged and no file",async()=>{profiles.set("owner",{...fresh("owner"),status:"IN_PROGRESS"});failBooks=true;await expect(storeBonusBook("owner","import-ref-key-1","digest",bookData)).rejects.toThrow();expect(profiles.get("owner")!.bonusUsedBytes).toBe(0);expect(books.size).toBe(0);});
  test("parallel same-key replay uses space once and returns same book",async()=>{profiles.set("owner",{...fresh("owner"),status:"IN_PROGRESS"});const [a,b]=await Promise.all([storeBonusBook("owner","import-ref-key-1","digest",bookData),storeBonusBook("owner","import-ref-key-1","digest",bookData)]);expect(a.id).toBe(b.id);expect(profiles.get("owner")!.bonusUsedBytes).toBe(100);});
  test("replay cannot replace PDF and allowance cannot exceed 50MB",async()=>{profiles.set("owner",{...fresh("owner"),status:"IN_PROGRESS"});await storeBonusBook("owner","import-ref-key-1","digest",bookData);await expect(storeBonusBook("owner","import-ref-key-1","different",bookData)).rejects.toThrow("already used");profiles.get("owner")!.bonusUsedBytes=BONUS_BYTES-50;await expect(storeBonusBook("owner","import-ref-key-2","digest",bookData)).rejects.toThrow("remaining");});
  test("cross-user import keys never reuse someone else's book",async()=>{for(const id of ["owner","other"])profiles.set(id,{...fresh(id),status:"IN_PROGRESS"});const a=await storeBonusBook("owner","import-ref-key-1","digest",bookData);const b=await storeBonusBook("other","import-ref-key-1","digest",bookData);expect(a.id).not.toBe(b.id);expect(b.userId).toBe("other");});
  test("analysis completes on provider failure with real deterministic result",async()=>{process.env.GROQ_API_KEY="test-only-not-a-real-key";await PATCH(request({action:"begin",revision:0}));const response=await POST(request({revision:1}));expect(response.status).toBe(200);const text=await response.text();expect(text).toContain('"stage":"dashboard"');expect(text).toContain('"ai":"fallback"');expect(profiles.get("owner")!.status).toBe("COMPLETED");expect(aiCalls).toBe(1);delete process.env.GROQ_API_KEY;});
  test("completed job replay returns saved result without another AI call",async()=>{await PATCH(request({action:"begin",revision:0}));await(await POST(request({revision:1,useAI:false}))).text();const response=await POST(request({revision:1}));expect((await response.json()).profile.status).toBe("COMPLETED");expect(aiCalls).toBe(0);});
  test("active job conflicts and analysis rate limit enforced",async()=>{profiles.set("owner",{...fresh("owner"),status:"ANALYZING",jobStartedAt:new Date(),jobToken:"existing"});expect((await POST(request({revision:0}))).status).toBe(409);profiles.set("owner",{...fresh("owner"),status:"IN_PROGRESS"});analysisDenied=true;expect((await POST(request({revision:0}))).status).toBe(429);});
  test("analysis rejects changed entitlement and closes allowance at completion",async()=>{profiles.set("owner",{...fresh("owner"),status:"IN_PROGRESS",preferences:{...DEFAULT_PREFERENCES,grade:9}});expect((await POST(request({revision:0}))).status).toBe(403);profiles.set("owner",{...fresh("owner"),status:"IN_PROGRESS"});await(await POST(request({revision:0,useAI:false}))).text();expect(profiles.get("owner")!.bonusClosedAt).not.toBeNull();});
  test("losing Class 9 access never prevents global skip",async()=>{profiles.set("owner",{...fresh("owner"),status:"IN_PROGRESS",preferences:{...DEFAULT_PREFERENCES,grade:9}});expect((await PATCH(request({action:"skip",revision:0,preferences:{...DEFAULT_PREFERENCES,grade:9}}))).status).toBe(200);expect(profiles.get("owner")!.status).toBe("SKIPPED");});
  test("audit lifecycle contains event names not answers",async()=>{await PATCH(request({action:"begin",revision:0}));await(await POST(request({revision:1,useAI:false}))).text();expect(events).toEqual(["personalization_started","personalization_completed"]);});
  const uploadRequest=(contents="%PDF-1.7 actual PDF bytes",allocation="onboarding",key="import-ref-key-1")=>{const form=new FormData();form.set("file",new File([contents],"notes.pdf",{type:"application/pdf"}));form.set("allocation",allocation);form.set("sizeBytes","1");return new NextRequest("http://localhost/api/ebooks",{method:"POST",headers:{"x-idempotency-key":key,"x-scholar-import":"initial-setup"},body:form});};
  test("existing PDF route charges actual bytes, not client declared size or monthly allowance",async()=>{profiles.set("owner",{...fresh("owner"),status:"IN_PROGRESS"});const response=await ebookRoute.POST(uploadRequest());expect(response.status).toBe(201);expect(profiles.get("owner")!.bonusUsedBytes).toBe(Buffer.byteLength("%PDF-1.7 actual PDF bytes"));expect(normalReservations).toBe(0);});
  test("onboarding upload dispatches its atomic private resource even without a subsequent resource lookup",async()=>{profiles.set("owner",{...fresh("owner"),status:"IN_PROGRESS"});const response=await ebookRoute.POST(uploadRequest());expect(response.status).toBe(201);const book=[...books.values()][0];expect(book.processingStatus).toBe("processing");expect(book.pageCount).toBe(0);expect(book.resource?.visibility).toBe("PRIVATE");expect(book.resource?.ownerUserId).toBe("owner");expect(book.resource?.job).toBeDefined();expect(backgroundTasks).toHaveLength(1);expect(parserTransfers).toBe(0);await backgroundTasks[0]();expect(book.processingStatus).toBe("ready");expect(parserTransfers).toBe(1);});
  test("fake PDF signature rejected and closed bonus does not reopen",async()=>{profiles.set("owner",{...fresh("owner"),status:"IN_PROGRESS"});expect((await ebookRoute.POST(uploadRequest("not a PDF"))).status).toBe(415);profiles.get("owner")!.bonusClosedAt=new Date();expect((await ebookRoute.POST(uploadRequest())).status).toBe(409);});
  test("normal upload releases monthly reservation if durable creation fails",async()=>{failBooks=true;const response=await ebookRoute.POST(uploadRequest("%PDF-1.7 normal bytes","standard"));expect(response.status).toBe(503);expect(await response.text()).not.toContain("write failed");expect(createAttempts).toBe(1);expect(books.size).toBe(0);expect(normalReservations).toBe(1);expect(normalReleases).toBe(1);expect(backgroundTasks).toHaveLength(0);});
  test("PDF worker transfer does not erase the original uploaded E-Book",async()=>{const contents="%PDF-1.7 original study document";expect((await ebookRoute.POST(uploadRequest(contents,"standard"))).status).toBe(201);const book=[...books.values()][0];expect(Buffer.from(book.pdfBytes).toString()).toBe(contents);expect(backgroundTasks).toHaveLength(1);await backgroundTasks[0]();expect(parserTransfers).toBe(1);expect(book.processingStatus).toBe("ready");expect(book.text).toContain("genuinely extracted study paragraph");expect(Buffer.from(book.pdfBytes).toString()).toBe(contents);expect(normalReleases).toBe(0);});
  test("successful upload replay returns persisted PDF after bonus closes without double charge",async()=>{profiles.set("owner",{...fresh("owner"),status:"IN_PROGRESS"});const first=await(await ebookRoute.POST(uploadRequest())).json();const used=profiles.get("owner")!.bonusUsedBytes;profiles.get("owner")!.bonusClosedAt=new Date();const replay=await(await ebookRoute.POST(uploadRequest())).json();expect(replay.ebook.id).toBe(first.ebook.id);expect(profiles.get("owner")!.bonusUsedBytes).toBe(used);});
});
