"use client";
import { getCurriculum } from "@/lib/curriculum-helper";
import { CHALLENGES,GOALS,REASONS,STYLES,type Preferences } from "@/lib/personalization/schema";
import { PERSONALITY_COPY } from "@/lib/live-tutor/types";
import { GlassSurface } from "@/components/liquid-glass/glass-surface";

export const QUESTION_TITLES=["Your studies, your starting point.","What are you working toward?","Where should we put our energy?","What gets in your way?","An explanation that clicks.","Meet your kind of LAM.","Make room for a little progress.","A date on the horizon?","What brings you to Scholar?"];
export const QUESTION_SUBTITLES=["Choose your class and the subjects you actually study. Scholar currently supports Class 9 and 11 CBSE.","Your goals change recommendations, not your access to premium or unsupported exam content.","Put subjects needing help first. Your strengths still get a place in the plan.","This is about useful study support, never a diagnosis.","A content preference, not a label about how your brain works.","The same LAM personalities you already know, with guidance that suits you.","A realistic daily target beats an impossible timetable. Notifications remain under your control.","Optional. We'll keep your upcoming exam visible, not promise a predicted score.","We'll put the most useful next steps within reach, without hiding the rest of Scholar."];
function Choices({items,selected,onChoose,label}:{items:{id:string;label:string;detail?:string}[];selected:string[];onChoose:(id:string)=>void;label:string}) {
  return <div role="group" aria-label={label} className="your-scholar-choices">{items.map(item=><GlassSurface as="button" material="control" type="button" key={item.id} aria-pressed={selected.includes(item.id)} className="your-scholar-choice" onClick={()=>onChoose(item.id)}><span>{item.label}{item.detail ? <small>{item.detail}</small> : null}</span><span className="your-scholar-choice-check" aria-hidden="true">{selected.includes(item.id) ? "✓" : "+"}</span></GlassSurface>)}</div>;
}
export function QuestionStage({stage,value,onChange,feedback,hasClass9}:{stage:number;value:Preferences;onChange:(p:Preferences)=>void;feedback:(text:string)=>void;hasClass9:boolean}) {
  const subjects=getCurriculum(value.grade).map(s=>({id:s.id,label:s.name}));
  const selectedSubjects=subjects.filter(s=>value.subjects.includes(s.id));
  const patch=(p:Partial<Preferences>)=>onChange({...value,...p});
  const multiple=(key:"subjects"|"goals"|"strong"|"weak"|"challenges"|"secondaryStyles"|"reasons",id:string)=>{
    const chosen=value[key].includes(id as never);const next=chosen ? value[key].filter(v=>v!==id) : [...value[key],id];
    patch({[key]:next,...(key === "subjects" ? {strong:value.strong.filter(v=>next.includes(v)),weak:value.weak.filter(v=>next.includes(v)),exam:value.exam ? {...value.exam,subjects:value.exam.subjects.filter(v=>next.includes(v))} : null} : {}),...(key === "weak" ? {strong:value.strong.filter(v=>v!==id)} : {}),...(key === "strong" ? {weak:value.weak.filter(v=>v!==id)} : {})} as Partial<Preferences>);
    if(!chosen && key === "weak") feedback(`${subjects.find(s=>s.id===id)?.label} will come first in practice, revision, and LAM recommendations.`);
    if(!chosen && key === "goals") feedback(id.startsWith("JEE") ? "JEE-oriented practice will be easier to find. Existing Plus gates still apply." : `Your ${id.toLowerCase()} goal will shape your next steps.`);
    if(!chosen && key === "challenges") feedback(["Remembering","Revision"].includes(id) ? "Scholar will bring retrieval practice and revision closer." : "Scholar will turn this into a practical next step, not a score or label.");
  };
  const items=(values:readonly string[])=>values.map(s=>({id:s,label:s}));
  return <div className="your-scholar-question">
    {stage===1 ? <>
      <h3>Your class</h3><div className="your-scholar-choices">{([9,11] as const).map(grade=><GlassSurface as="button" type="button" material="control" key={grade} aria-pressed={value.grade===grade} disabled={grade===9 && !hasClass9} className="your-scholar-choice" onClick={()=>patch({grade,subjects:[],strong:[],weak:[],exam:null})}>Class {grade}{grade===9 && !hasClass9 ? " · Plus" : ""}</GlassSurface>)}</div>
      <h3>Your curriculum</h3><Choices label="Curriculum" items={items(["CBSE","State","Other"])} selected={[value.board]} onChoose={id=>patch({board:id as Preferences["board"]})}/>
      {value.board!=="CBSE" ? <p className="your-scholar-note">We can help with general concepts, but Scholar's mapped curriculum remains CBSE. Other boards don't unlock their own syllabus.</p> : null}
      <h3>Your subjects</h3><Choices label="Study subjects" items={subjects} selected={value.subjects} onChoose={id=>multiple("subjects",id)}/>
    </> : null}
    {stage===2 ? <><Choices label="Study goals" items={items(GOALS)} selected={value.goals} onChoose={id=>multiple("goals",id)}/>{value.goals.some(g=>["NEET","CUET"].includes(g)) ? <p className="your-scholar-note">Scholar can suggest supported concept and practice tools. Dedicated NEET/CUET syllabus packs are not available.</p> : null}</> : null}
    {stage===3 ? <><h3>Your strongest subjects</h3><Choices label="Strong subjects" items={selectedSubjects} selected={value.strong} onChoose={id=>multiple("strong",id)}/><h3>Subjects needing the most help</h3><Choices label="Priority subjects" items={selectedSubjects} selected={value.weak} onChoose={id=>multiple("weak",id)}/><p className="your-scholar-note">Choose in priority order. Choose again to remove; no dragging needed.{!selectedSubjects.length ? " Go back and choose subjects, or continue with a balanced plan." : ""}</p></> : null}
    {stage===4 ? <Choices label="Study challenges" items={items(CHALLENGES)} selected={value.challenges} onChoose={id=>multiple("challenges",id)}/> : null}
    {stage===5 ? <><h3>Your first preference</h3><Choices label="Explanation preference" items={items(STYLES)} selected={[value.style]} onChoose={id=>{patch({style:id as Preferences["style"]});feedback(id==="Short and direct" ? "LAM will start concise. You can always ask it to go deeper." : `LAM will start with ${id.toLowerCase()} explanations.`);}}/><h3>Also useful · optional</h3><Choices label="Secondary explanations" items={items(STYLES).filter(s=>s.id!==value.style)} selected={value.secondaryStyles} onChoose={id=>multiple("secondaryStyles",id)}/></> : null}
    {stage===6 ? <><Choices label="LAM personality" items={(["calm","exam","curious"] as const).map(id=>({id,label:PERSONALITY_COPY[id].label,detail:id==="calm" ? "Patient, clear, supportive." : id==="exam" ? "Focused, direct, exam-oriented." : "Explore the why behind the answer."}))} selected={[value.personality]} onChoose={id=>{patch({personality:id as Preferences["personality"]});feedback("Your LAM preference will be ready when you open tutoring. Voice stays opt-in.");}}/><h3>How much guidance?</h3><Choices label="Guidance style" items={items(["gentle","balanced","strict"])} selected={[value.guidance]} onChoose={id=>patch({guidance:id as Preferences["guidance"]})}/></> : null}
    {stage===7 ? <><h3>Your usual study window</h3><Choices label="Study window" items={items(["Morning","Afternoon","Evening","Late night","Varies"])} selected={[value.studyWindow]} onChoose={id=>patch({studyWindow:id as Preferences["studyWindow"]})}/><div className="your-scholar-input-grid"><label>Time available each day · minutes<input type="number" min={5} max={240} value={value.minutes} onChange={e=>patch({minutes:Number(e.target.value)})}/></label><label>Your daily target · minutes<input type="number" min={5} max={240} value={value.dailyGoal} onChange={e=>patch({dailyGoal:Number(e.target.value)})}/></label></div><h3>Preferred days · optional</h3><Choices label="Study days" items={["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map((label,i)=>({id:String(i),label}))} selected={value.days.map(String)} onChoose={id=>patch({days:value.days.includes(Number(id)) ? value.days.filter(v=>v!==Number(id)) : [...value.days,Number(id)]})}/></> : null}
    {stage===8 ? <><Choices label="Upcoming exam" items={items(["No exam yet","Add an exam"])} selected={[value.exam ? "Add an exam" : "No exam yet"]} onChoose={id=>patch({exam:id==="No exam yet" ? null : {name:"",date:"",subjects:[]}})}/>{value.exam ? <><div className="your-scholar-input-grid"><label>Exam name<input maxLength={80} value={value.exam.name} onChange={e=>patch({exam:{...value.exam!,name:e.target.value}})}/></label><label>Approximate date<input type="date" min={new Date().toISOString().slice(0,10)} value={value.exam.date} onChange={e=>patch({exam:{...value.exam!,date:e.target.value}})}/></label></div><h3>Exam subjects</h3><Choices label="Exam subjects" items={selectedSubjects} selected={value.exam.subjects} onChoose={id=>patch({exam:{...value.exam!,subjects:value.exam!.subjects.includes(id) ? value.exam!.subjects.filter(s=>s!==id) : [...value.exam!.subjects,id]}})}/></> : null}</> : null}
    {stage===9 ? <Choices label="Reasons for using Scholar" items={items(REASONS)} selected={value.reasons} onChoose={id=>multiple("reasons",id)}/> : null}
  </div>;
}
