import { InformationPage } from "@/components/information-page";
export const metadata = { title: "What's new | Scholar" };
export default function UpdatesPage() {
  return <InformationPage title="What's new" intro="A more dependable study workspace, built on the Scholar you already know.">
    <section><h2>September 2026 · Public accounts, a calmer welcome</h2><p>Scholar accounts are now open. A focused Liquid Glass sign-in screen puts email sign-in and account creation first, with Google sign-in wherever configured. Existing accounts can explicitly connect Google in Settings without replacing saved work or creating a second workspace. Email verification and password reset use single-use links when the email sender is configured. Your Scholar takes over after sign-in; Guest Mode, invited study-room participants and server-enforced Free/Plus access stay separate.</p></section>
    <section><h2>September 2026 · Your Scholar</h2><p>A new personalized arrival learns your study priorities, goals, explanation preferences and routine, then builds your own Scholar Today and tunes LAM's existing teaching defaults. Your Learning Profile stays editable in Settings. Bring optional PDFs with 50 MB of one-time setup import space; those books stay available afterward. A quiet planetary journey shows Scholar shaping your workspace, with a reliable preference-based plan even when optional AI refinement is unavailable. Every question and the entire setup remain skippable, and Scholar Plus is always optional.</p></section>
    <section><h2>September 2026 · Reliability and security hardening</h2><p>Scholar now handles AI streams, uploads, account access, Group Study actions, payment reviews and learning progress more defensively. Requests have clearer size and rate limits, interrupted AI answers fail cleanly instead of appearing complete, account and room data remain scoped to the right user, and concurrent actions are protected from duplicate or conflicting writes. We also refreshed the supported framework and image-processing dependencies, improved offline behaviour, and tightened browser security headers without changing your study workflow.</p></section>
    <section><h2>September 2026 · Scholar Liquid Glass</h2><p>Scholar now has one continuous glass interface. Navigation, menus, notifications, dialogs, controls, search fields and study panels are built from the same layered material, with edge light, depth and a subtle refraction at the edges of the surfaces you interact with most. The result should feel like one connected environment instead of separate cards. Everything stays quiet and readable: text and answers are never distorted, and the effect softens automatically on slower devices, older browsers, touch-only screens or when you ask for reduced motion or reduced transparency.</p></section>
    <section><h2>September 2026 · A redesigned shell and navigation</h2><p>The sidebar, top bar and mobile navigation are now floating glass surfaces with a clearer selected state and a more tactile press. On phones the bottom dock sits above your content, respects safe areas and disappears while the keyboard is open. Buttons, tabs, inputs and loading states share the same material, so a page no longer changes personality as you move around Scholar.</p></section>
    <section><h2>September 2026 · Scholar Plus, made coherent</h2><p>Scholar Plus now connects premium AI, JEE Focused Mode, early-access Experiments and Group Study hosting, selected Resources, Workspace insights, and higher monthly limits through one clear access system. Custom PDF E-Books are private to your account, Answer Lab accepts your own questions, and every locked feature explains what it unlocks before taking you to the relevant plan section.</p></section>
    <section><h2>September 2026 · LAM AI, rebuilt around Scholar</h2><p>LAM AI now combines a cinematic, distraction-free study canvas with Scholar's real accounts, AI providers, learning context and saved memory. Calm Tutor, Exam Coach and Curious Scientist each keep their own conversation history, while the useful things LAM learns about you remain shared. Voice stays opt-in, responses stream as they arrive, and actions such as saving Notes or opening study tools ask for confirmation first.</p></section>
    <section><h2>September 2026 · Mobile and responsive foundation</h2><p>Scholar now adapts its shared shell, dialogs, navigation, LAM AI, files, study tools, media pages, settings and Group Study layouts across phones, tablets and compact laptops. Safe-area and software-keyboard handling keep fixed controls clear of content, dense toolbars stay reachable without making the page scroll sideways, and desktop layouts retain their existing structure.</p></section>
    <section><h2>September 2026 · Group Study 3.0</h2><p>Group Study now behaves like one shared Scholar workspace. Hosts can guide the room between materials, Group LAM, quizzes, notes and focus sessions; choose Follow Host, Guided Freedom or Open Session; control which room features are available; and build a shared study path. Fast room chat, reactions, raise hand, optional voice and camera, and a compact live-friends dock remain available while everyone moves through the session. Microphone and camera access always require each participant's own action.</p></section>
    <section><h2>September 2026 · Group Study (Beta)</h2><p>Group Study is here: create or join a hosted study room with a shareable code. Hosts control the room, participants join with just a name — no account needed. Shared PDF materials, Group LAM study help, live chat with announcements, quizzes, polls, shared notes and synchronized focus sessions. Group Study hosting remains protected by its existing account entitlement and room ownership rules.</p></section>
    <section><h2>September 2026 · Reliability improvements</h2><p>AI response handling now distinguishes completed answers from interrupted output. Feature screens load as you open them, and session connection failures have a recovery path. Navigation, support information, mobile spacing, and background playback are being refined throughout the existing website.</p></section>
    <section><h2>Your work stays yours</h2><p>This update keeps the existing accounts, subscriptions, curriculum, and saved work. No database reset is part of the website overhaul. The technical worklog in the <a href="https://github.com/frienasduck/Scholar-V1/blob/main/worklog.md">project repository</a> records tested changes and remaining limitations.</p></section>
  </InformationPage>;
}
