import { InformationPage } from "@/components/information-page";
export const metadata = { title: "What's new | Scholar" };
export default function UpdatesPage() {
  return <InformationPage title="What's new" intro="A more dependable study workspace, built on the Scholar you already know.">
    <section><h2>September 2026 · Live Tutor, rebuilt around Scholar</h2><p>LAM Live Tutor now combines a cinematic, distraction-free study canvas with Scholar's real accounts, AI providers, learning context and saved memory. Calm Tutor, Exam Coach and Curious Scientist each keep their own conversation history, while the useful things LAM learns about you remain shared. Voice stays opt-in, responses stream as they arrive, and actions such as saving Notes or opening study tools ask for confirmation first.</p></section>
    <section><h2>September 2026 · Mobile and responsive foundation</h2><p>Scholar now adapts its shared shell, dialogs, navigation, Live Tutor, files, study tools, media pages, settings and Group Study layouts across phones, tablets and compact laptops. Safe-area and software-keyboard handling keep fixed controls clear of content, dense toolbars stay reachable without making the page scroll sideways, and desktop layouts retain their existing structure.</p></section>
    <section><h2>September 2026 · Group Study 3.0</h2><p>Group Study now behaves like one shared Scholar workspace. Hosts can guide the room between materials, Group LAM, quizzes, notes and focus sessions; choose Follow Host, Guided Freedom or Open Session; control which room features are available; and build a shared study path. Fast room chat, reactions, raise hand, optional voice and camera, and a compact live-friends dock remain available while everyone moves through the session. Microphone and camera access always require each participant's own action.</p></section>
    <section><h2>September 2026 · Group Study (Beta)</h2><p>Group Study is here: create or join a hosted study room with a shareable code. Hosts control the room, participants join with just a name — no account needed. Shared PDF materials, Group LAM study help, live chat with announcements, quizzes, polls, shared notes and synchronized focus sessions. Scholar remains in private beta: public registration is closed, and Guest Mode continues to work for everyone.</p></section>
    <section><h2>September 2026 · Reliability improvements</h2><p>AI response handling now distinguishes completed answers from interrupted output. Feature screens load as you open them, and session connection failures have a recovery path. Navigation, support information, mobile spacing, and background playback are being refined throughout the existing website.</p></section>
    <section><h2>Your work stays yours</h2><p>This update keeps the existing accounts, subscriptions, curriculum, and saved work. No database reset is part of the website overhaul. The technical worklog in the <a href="https://github.com/frienasduck/Scholar-V1/blob/main/worklog.md">project repository</a> records tested changes and remaining limitations.</p></section>
  </InformationPage>;
}
