import { currentTask, subjectChapter, type ExamSession, type Lesson } from "./model";

// Authored, curriculum-based offline content. Never persisted as AI output or
// scored evidence. Every mission has its own coverage instead of one fixed demo.
const motion = [
    { title: "Newton's first law (inertia)", text: "A body remains at rest or moves at constant velocity when its net external force is zero. Inertia is resistance to a change in velocity, not a force.", question: "A puck moves at constant velocity on a frictionless surface. What is its net force?", options: ["Zero", "In the direction of motion", "Opposite the motion", "Equal to its weight"], answer: "Zero", explanation: "Constant velocity means zero acceleration. The forces may exist, but their vector sum is zero.", problem: "A book rests on a horizontal table. Why does it not accelerate?", steps: ["Its weight acts downwards; the table's normal force acts upwards.", "These forces balance on this book, so the net force is zero."], result: "The book remains at rest. Balanced forces on one body are not an action–reaction pair." },
    { title: "Newton's second law (F = ma)", text: "Acceleration depends on the net external force and mass. For constant mass in an inertial frame, acceleration points in the direction of the net force.", question: "A net force of 15 N gives a body an acceleration of 3 m/s². What acceleration will 25 N give the same body?", options: ["3 m/s²", "5 m/s²", "6 m/s²", "9 m/s²"], answer: "5 m/s²", explanation: "First find the mass: $m = 15 / 3 = 5\\,\\mathrm{kg}$.\n\nThen $a = 25 / 5 = 5\\,\\mathrm{m/s^2}$. Use the same mass in both cases.", formula: "$$\\vec F_{net}=m\\vec a$$", problem: "A 4 kg object has a net horizontal force of 20 N. Find its acceleration.", steps: ["Use the net force, not just one applied force.", "$a = F/m = 20/4$"], result: "Acceleration is 5 m/s² in the direction of the net force." },
    { title: "Newton's third law and action-reaction pairs", text: "Interacting bodies exert equal and opposite forces on one another. The two forces act on different bodies, so they do not cancel in a single body's force diagram.", question: "A book pushes down on a table. Where does the reaction force act?", options: ["Upwards on the book", "Downwards on the book", "Upwards on the table", "There is no reaction"], answer: "Upwards on the book", explanation: "The table pushes upwards on the book. The book's push on the table and the table's push on the book form the pair, acting on different bodies.", problem: "A swimmer pushes water backwards. Explain the swimmer's forward motion.", steps: ["The swimmer exerts a backwards force on the water.", "The water exerts an equal forwards force on the swimmer."], result: "The forces belong to different bodies. The forwards force accelerates the swimmer." },
    { title: "Friction (static and kinetic)", text: "Static friction adjusts to prevent relative slipping, up to its limiting value. Kinetic friction acts when surfaces slide. Do not automatically set static friction equal to its maximum.", question: "A resting block has a limiting static friction of 10 N. A horizontal push of 4 N is applied. What is the friction force?", options: ["4 N opposite the push", "10 N opposite the push", "Zero", "14 N opposite the push"], answer: "4 N opposite the push", explanation: "The block remains at rest. Static friction matches the applied 4 N push; 10 N is its maximum, not its value in every situation.", formula: "$$f_s \\leq \\mu_s N,\\qquad f_k=\\mu_k N$$", problem: "A 2 kg block slides on a horizontal surface with kinetic friction coefficient 0.2. Use g = 10 m/s² to find friction.", steps: ["There is no vertical acceleration, so N = mg = 20 N.", "Kinetic friction = 0.2 × 20 = 4 N."], result: "Friction is 4 N opposite the sliding motion." },
    { title: "Conservation of linear momentum", text: "Total momentum of an isolated system is conserved when the net external impulse is zero. Individual bodies may change momentum through internal forces while the system total remains unchanged.", question: "Two carts collide in an isolated system. Which quantity must remain constant through the collision?", options: ["Total momentum", "Each cart's velocity", "Each cart's momentum", "Total kinetic energy in every collision"], answer: "Total momentum", explanation: "Internal forces transfer momentum between carts. With zero net external impulse, total momentum remains constant; kinetic energy need not be conserved in an inelastic collision.", formula: "$$p=mv,\\qquad \\Delta p=F_{net}\\Delta t$$", problem: "A 2 kg cart at 3 m/s sticks to a stationary 1 kg cart. Find their shared velocity, neglecting external impulse.", steps: ["Initial momentum = 2 × 3 + 1 × 0 = 6 kg·m/s.", "Final combined mass = 3 kg; velocity = 6/3 = 2 m/s."], result: "The combined carts move at 2 m/s in the initial direction." },
];

export function localMissionLesson(s: ExamSession, pace = "normal"): Lesson | undefined {
    const task = currentTask(s);
    if (!task || task.kind === "mock" || task.kind === "break") return undefined;
    const chapter = subjectChapter(s.setup, task.subjectId, task.chapterId);
    if (!chapter) return undefined;
    const details = chapter as typeof chapter & { commonMistakes?: string[]; quickSummary?: string[] };
    if (["personal", "custom"].includes(s.setup.materials)) return { text: "Live teaching from your private or selected material requires an account. Your local mission and notes are still available. No outside lesson has been substituted for your selected sources.", formulas: [], questions: [], citations: [], grounding: "material gap" };
    const topics = task.topics ?? chapter.concepts;
    const topic = topics[0] ?? chapter.title;
    const index = Math.max(0, chapter.concepts.indexOf(topic));
    const stageIndex = ["diagnostic", "learn", "repair", "practice", "recall", "mistakes", "revise"].indexOf(task.kind);
    const focus = task.subjectId === "physics" && task.chapterId === "p5" ? motion[(topics.length === 1 ? index : Math.max(0, stageIndex)) % motion.length] : undefined;
    const excerpt = (details.quickSummary ?? []).filter(line => topics.some(t => t.toLowerCase().split(/[^a-z]+/).filter(word => word.length > 4).some(word => line.toLowerCase().includes(word)))).slice(0, 3);
    const text = task.kind === "diagnostic" ? `Start with a baseline check for ${chapter.title}. Try the question before reading its feedback. Calibration is not a teaching lecture.` : task.kind === "practice" ? `Apply what you learned in ${chapter.title}. Attempt the question first, then check each step of the reasoning. This is application, not a chapter restart.` : task.kind === "recall" ? `Recall ${topics.join("; ")} without looking at your notes. Explain the idea in your own words before checking the answer.` : task.kind === "mistakes" ? `Review ${chapter.title}'s common traps: ${(details.commonMistakes ?? []).slice(0, 3).join("; ") || "check your assumptions, reasoning and units"}. Your recorded account mistakes will be used by live LAM.` : focus?.text ?? `This checkpoint covers: ${topics.join("; ")}.\n\n${excerpt.length ? excerpt.join("\n\n") : "Use the chapter resources to study this specific concept, explain it in your own words, and try its application. Sign in for a detailed live LAM lesson for this checkpoint."}`;
    const teaching = ["learn", "repair", "revise"].includes(task.kind);
    const stageCheck = !focus ? undefined : task.kind === "diagnostic" ? { title: "Net force and motion", question: "Which statement about motion and net force is correct?", options: ["Constant velocity can occur with zero net force", "Motion always requires a nonzero net force", "Zero net force means zero velocity", "Force and velocity must always have the same direction"], answer: "Constant velocity can occur with zero net force", explanation: "Net force changes velocity. A body can already be moving at constant velocity while its net force is zero." } : task.kind === "practice" ? { title: "Force application", question: "A 5 kg body experiences a net horizontal force of 20 N. What is its acceleration?", options: ["4 m/s²", "100 m/s²", "0.25 m/s²", "20 m/s²"], answer: "4 m/s²", explanation: "Use $a = F/m = 20/5 = 4\\,\\mathrm{m/s^2}$. Acceleration points in the direction of the net force." } : task.kind === "recall" ? { title: "Momentum recall", question: "What condition lets you conserve a system's total momentum?", options: ["Zero net external impulse", "Zero force on each body", "Equal masses", "A perfectly elastic collision only"], answer: "Zero net external impulse", explanation: "The total momentum changes by the net external impulse. Internal interactions do not change the system's total momentum." } : task.kind === "mistakes" ? { title: "Static-friction trap", question: "When can you set static friction equal to its limiting value?", options: ["At impending slip", "Whenever the body is at rest", "Whenever a force is applied", "Only after the body starts sliding"], answer: "At impending slip", explanation: "Static friction adjusts below its limit while the body remains at rest. It reaches its limiting value at impending slip; sliding uses kinetic friction." } : focus;
    return {
        text: pace === "faster" && focus && teaching ? focus.text : text,
        concept: teaching ? { title: focus?.title ?? topic, explanation: focus?.text ?? chapter.summary, formula: focus?.formula, conditions: "Offline curriculum guidance. Sign in for adaptive AI explanations and verified evaluation." } : undefined,
        example: focus && teaching && pace !== "faster" ? { title: "Worked example", problem: focus.problem, steps: focus.steps, result: focus.result } : undefined,
        formulas: focus?.formula ? [focus.formula] : chapter.formulas ?? [],
        questions: [stageCheck ? { id: `preview:${task.id}:${stageCheck.title}`, subjectId: task.subjectId, chapterId: task.chapterId, topic: stageCheck.title, kind: "mcq", question: stageCheck.question, options: stageCheck.options, answer: stageCheck.answer, explanation: stageCheck.explanation, source: "Scholar question bank" } : { id: `preview:${task.id}:recall`, subjectId: task.subjectId, chapterId: task.chapterId, topic, kind: "short", question: `Explain ${topics.join("; ")} in your own words. Connect it to ${chapter.title}.`, answer: chapter.summary, explanation: `${chapter.summary}\n\nCompare your explanation with these curriculum points:\n\n${topics.join("\n\n")}`, source: "Scholar question bank" }],
        citations: [], grounding: "general AI explanation",
    };
}
